# Practice assignments {-}

> From 03-import

## Practice assignment: Import census

To practice these skills on your own, you'll create a new project and use new data. You'll work on it through multiple lessons, applying what you've learned along the way.

- Close your School Ratings project first!
- Create a **new Project** called "firstname-census-practice". You'll want to save that inside your "rwd" folder so you can use it later. We'll keep building on it.
- Create a new folder in your project called "data-raw".
- Download this CSV file and put it into your data-raw folder: [DEC_10_SF1_TX_County_population.csv](https://drive.google.com/file/d/1L51qQbdW3dHXTdlvlHx3z5p8Py5Cgv2a/view). The data is 2010 Census populations by county and race for Texas.
- Start a new R Notebook with a good title and filename.
- Write text to describe the data set.
- Import the data using `read_csv()` and print the data to the screen.
- Compare the imported data to the original csv file and note any problems you might see with the column names or data types that you might want to fix.
- Save, Knit, and Zip the project folder and upload to the "Practice: Import" assignment.

> From 04-Transfrom

## Practice assignment: Transforms on census

For this practice assignment, you'll continue with your "census-practice" project.

The goal here is: For each race in the data, find the county with the highest percentage for that race. You'll use the dplyr commands from this lesson to do it.

- Start a new notebook that imports the cleaned data from the last assignment. Start the notebook name with "02-" so you know the order to run them in the future.
- Use `mutate()` to create a new column for each race that calculates the percentage for that race. You might create columns names like "hispanic_prc" with the formula "(hispanic / total_populaton) * 100". Assign those values back to the "census" data frame.
- Create a series of code chunks, one for each race that does this: Arrange the data so the county with the highest percentage of that race is on top, then use `select()` to show these columns: The county, total population, that race total, and the percentage of that race.
- Make sure that each each action is clearly described in Markdown headlines and text, and that each code chunk is named. 

If you feel like you are repeating yourself a lot on this assignment and feel like there should be a better way, I assure you there is. We will get to that.

Save, Knit, Zip and upload your project to the "Practice: Transform with dplyr" assignment.

