# How to tackle a new dataset

> A work in progress. Just a start, really.

For those unfamiliar with exploring data, starting the process can be paralyzing.

Where do I start? What am I looking for? How do I explore when I don't know what I'm looking for?

Every situation is different, but there are some common techniques and some common sense that you can bring to every project.

## Start by listing questions

It's likely you've acquired data because you needed it to add context to a story or situation. Spend a little time at the beginning brainstorming as list of questions you want to answer. (You might ask a colleague to participate: the act of describing the data set will reveal questions for both of you.) I like to start my RNotebook with this list.

## Understand the distributions in your data

Explore key columns in your data to see how they vary.

> just a start

- summary()
- plot histogrames


## Time as a variable

If you have dates in your data, then you almost always want to see change over time for different variables.

- Summarize records by year or month as appropriate and plot Bar/Column charts to show how the number of records have changed.

Is there any significant change in any of the categorical data over time?
