# Notes about future sessions {-}

## Maps {-}

- Draw ideas from [this tutorial](https://workshop.mhermans.net/thematic-maps-r/) and Machlis.
- Andrew Tran's [mapping session from NICAR](https://github.com/andrewbtran/NICAR/tree/master/2019/mapping)

## Joins {-}

Add this as a short lesson on joining and merging files.

## Data packages {-}

Add a chapter that lists various data packages and such.


## Matt Waite's class for ggplot ideas {-}

### 06 has these {-}

- reorder
- introduce scales (same)
- add themes for styling. [more themes in the ggplot documentation](https://ggplot2.tidyverse.org/reference/ggtheme.html)
- Save as an png

### 07 has {-}

- stacked bar chart
- uses fill

### 08 has {-}

- uses [cfbstats]((http://www.cfbstats.com/2018/leader/national/team/offense/split01/category25/sort01.html) for data
- line chart
- adding average, highlight and annotations to line chart
- changing size of graphics with `repr` library to change the size of the graphic, but I'm not sure why.

### 09 {-}

Scatterplots using sports data

- Uses ggrepel to move labels from on top of points
- Uses a join to combine data
- Uses Pearson coefficient to note predective stat.

### 10: waffle {-}

- Uses sports data to make a [waffle chart](https://github.com/hrbrmstr/waffle), which is pretty cool. A better way than a pie chart to compare two values, or even multiples of a whole.

### 11 Facet wrap {-}

- uses line charts of a cfb stat over time to separate by team. Might use sports data to show this. Or, if I had something like school enrollment over time? Alcohol sales of specific bars?

### 12 is animate {-}

I can't get this to work. Not sure it is essential. We'll see.

### 13 is about zscores {-}

I dont want to go here.

### 14 more zscors {-}

I skipped it.

### 15 was soccer {-}

missing the data. might be in the repo now.

### 16 was themes {-}

This is good. I can use this, though I'm skipping the Illustrator part.

### 17 is residuals {-}

This is over my head.

### 18 is simulations {-}

This could be useful. Or not.

### 19 is tables as in formattables {-}

this is good. Might be better than tabyl.

[a helpful guide](https://www.displayr.com/formattable/)

### Waffle iron fixes {-}

Making waffle irons to PDF for Illustrator. Not important to me.