project:
  type: book
  output-dir: docs

book:
  title: "Reporting with Data in R"
  author: "Christian McDonald & Jo Lukito"
  date: "5/19/2023"
  chapters:
    - index.qmd
    - install.qmd
    - intro.qmd
    - counts-import.qmd
    - counts-analysis.qmd
    - sums-import.qmd
    - sums-analysis.qmd
    - plots.qmd
    - tidy-data.qmd
    - bind-join.qmd
    - answers.qmd
    - group-dates.qmd
    - functions.qmd
    - troubleshooting.qmd
    - explore.qmd
    - charts-tips.qmd
    

format:
  html:
    theme: cosmo

editor: visual

