project:
  type: book
  output-dir: docs
  resources:
    - v*/
book:
  title: "Reporting with Data in R"
  author: "Christian McDonald & Jo Lukito"
  date: "07/05/2023"
  chapters:
    - index.qmd
    - install.qmd
    - intro.qmd
    - part: "Counting"
      chapters: 
      - billboard-cleaning.qmd
      - billboard-analysis.qmd
    - part: "Summing"
      chapters:
      - leso-cleaning.qmd
      - leso-analysis.qmd
    - part: "Visualization"
      chapters:
      - plots.qmd
      - plots-more.qmd
      - tidy-data.qmd
    - part: "Bind & Join"    
      chapters:
      - denied-cleaning.qmd
      - denied-analysis.qmd
  appendices:
    - functions.qmd
    - posit-cloud.qmd
    - group-dates.qmd
    - count.qmd
    - case-when.qmd
    - troubleshooting.qmd
    - explore.qmd
    - charts-tips.qmd

format:
  html:
    theme: cosmo
    df-print: paged
    code-overflow: wrap

editor: source
