<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Reporting with Data in R - 9&nbsp; Bind and join</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./answers.html" rel="next">
<link href="./tidy-data.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./bind-join.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bind and join</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Reporting with Data in R</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">About this book</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./install.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Install Party</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction to R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./counts-import.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Summarize: count - import</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./counts-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Summarize: count - analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sums-import.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Summarize: math - import</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sums-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summarize: math - analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Data Viz - Intro to ggplot</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tidy-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Tidy data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bind-join.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bind and join</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./answers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Plotting for answers</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./group-dates.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Grouping by dates</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">R Functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./troubleshooting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Troubleshooting</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explore.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Exploring a new dataset</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./charts-tips.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Chart production tips</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#goals-of-the-chapter" id="toc-goals-of-the-chapter" class="nav-link active" data-scroll-target="#goals-of-the-chapter"><span class="header-section-number">9.1</span> Goals of the chapter</a></li>
  <li><a href="#the-story-an-update-to-denied" id="toc-the-story-an-update-to-denied" class="nav-link" data-scroll-target="#the-story-an-update-to-denied"><span class="header-section-number">9.2</span> The story: An update to Denied</a></li>
  <li><a href="#about-the-data" id="toc-about-the-data" class="nav-link" data-scroll-target="#about-the-data"><span class="header-section-number">9.3</span> About the data</a>
  <ul class="collapse">
  <li><a href="#set-up-your-project" id="toc-set-up-your-project" class="nav-link" data-scroll-target="#set-up-your-project"><span class="header-section-number">9.3.1</span> Set up your project</a></li>
  <li><a href="#open-read-and-run" id="toc-open-read-and-run" class="nav-link" data-scroll-target="#open-read-and-run"><span class="header-section-number">9.3.2</span> Open, read and run</a></li>
  </ul></li>
  <li><a href="#merging-data-together" id="toc-merging-data-together" class="nav-link" data-scroll-target="#merging-data-together"><span class="header-section-number">9.4</span> Merging data together</a></li>
  <li><a href="#about-joins" id="toc-about-joins" class="nav-link" data-scroll-target="#about-joins"><span class="header-section-number">9.5</span> About joins</a>
  <ul class="collapse">
  <li><a href="#joining-our-reference-table" id="toc-joining-our-reference-table" class="nav-link" data-scroll-target="#joining-our-reference-table"><span class="header-section-number">9.5.1</span> Joining our reference table</a></li>
  </ul></li>
  <li><a href="#some-cleanup-filter-and-select" id="toc-some-cleanup-filter-and-select" class="nav-link" data-scroll-target="#some-cleanup-filter-and-select"><span class="header-section-number">9.6</span> Some cleanup: filter and select</a></li>
  <li><a href="#create-an-audit-benchmark-column" id="toc-create-an-audit-benchmark-column" class="nav-link" data-scroll-target="#create-an-audit-benchmark-column"><span class="header-section-number">9.7</span> Create an audit benchmark column</a></li>
  <li><a href="#export-the-data" id="toc-export-the-data" class="nav-link" data-scroll-target="#export-the-data"><span class="header-section-number">9.8</span> Export the data</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="bind-join" class="quarto-section-identifier"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bind and join</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>So far all of our lessons have come from a single data source, but that’s not always the case in the real world. With this lesson we’ll learn how to “bind” and “join” data, which are different ways to bring multiple data frames together into a single object.</p>
<p>This is the first of a two-chapter project. It is by Prof.&nbsp;McDonald, using a Mac.</p>
<section id="goals-of-the-chapter" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="goals-of-the-chapter"><span class="header-section-number">9.1</span> Goals of the chapter</h2>
<ul>
<li>Merge multiple data files with <code>bind_rows()</code></li>
<li>Join data frames with <code>inner_join()</code></li>
<li>Use <code>str_remove()</code> to clean data</li>
<li>Introduce <code>if_else()</code> for categorization</li>
</ul>
<p>We’ll use the results of this chapter in our next one.</p>
</section>
<section id="the-story-an-update-to-denied" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="the-story-an-update-to-denied"><span class="header-section-number">9.2</span> The story: An update to Denied</h2>
<p>In 2016, the Houston Chronicle published a multi-part series called <a href="https://www.houstonchronicle.com/denied/1/">Denied</a> that outlined how a Texas Education Agency policy started in 2004 could force an audit of schools that have more than 8.5% of their students in special education programs. The story was a Pulitzer Prize finalist. Here’s an excerpt:</p>
<blockquote class="blockquote">
<p>Over a decade ago, the officials arbitrarily decided what percentage of students should get special education services — 8.5% — and since then they have forced school districts to comply by strictly auditing those serving too many kids.</p>
</blockquote>
<blockquote class="blockquote">
<p>Their efforts, which started in 2004 but have never been publicly announced or explained, have saved the Texas Education Agency billions of dollars but denied vital supports to children with autism, attention deficit hyperactivity disorder, dyslexia, epilepsy, mental illnesses, speech impediments, traumatic brain injuries, even blindness and deafness, a Houston Chronicle investigation has found.</p>
</blockquote>
<blockquote class="blockquote">
<p>More than a dozen teachers and administrators from across the state told the Chronicle they have delayed or denied special education to disabled students in order to stay below the 8.5 percent benchmark. They revealed a variety of methods, from putting kids into a cheaper alternative program known as “Section 504” to persuading parents to pull their children out of public school altogether.</p>
</blockquote>
<p>Following the Chronicle’s reporting (along with other news orgs), the Texas Legislature in 2017 <a href="https://www.chron.com/news/houston-texas/houston/article/Legislature-unanimously-approves-bill-designed-to-11134046.php">unanimously banned</a> using a target or benchmark on how many students a district or charter school enrolls in special education.</p>
<p>We want to look into the result of this reporting based on three things:</p>
<ul>
<li>Has the percentage of special education students in Texas changed since the benchmarking policy was dropped?</li>
<li>How many districts were above that arbitrary 8.5% benchmark before and after the changes?</li>
<li>How have local districts changed?</li>
</ul>
<p>To prepare for this:</p>
<ol type="1">
<li>Read <a href="https://www.houstonchronicle.com/denied/1/">Part 1</a> of the original Denied series.</li>
<li>Read <a href="https://www.houstonchronicle.com/denied/about/">About this series</a></li>
<li>Read <a href="https://www.chron.com/news/houston-texas/houston/article/Legislature-unanimously-approves-bill-designed-to-11134046.php">this followup</a> about the legislative changes.</li>
</ol>
</section>
<section id="about-the-data" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="about-the-data"><span class="header-section-number">9.3</span> About the data</h2>
<p>Each year, the Texas Education Agency publishes the percentage of students in special education as part of their <a href="https://tea.texas.gov/texas-schools/accountability/academic-accountability/performance-reporting/texas-academic-performance-reports">Texas Academic Performance Reports</a>. We can download a file that has the percentages for each district in the state.</p>
<p>There are some challenges, though:</p>
<ul>
<li>We have to download each year individually. There are nine years of data.</li>
<li>The are no district names in the files, only a district ID. We can get a reference file, though.</li>
<li>There are some differences in formatting for some files.</li>
</ul>
<p>I will save you the hassle of going through the TAPR database to find and download the individual files, and I will also supply code to clean the files to make them consistent. I’ll try not to get lost in the weeds along the way.</p>
<section id="set-up-your-project" class="level3" data-number="9.3.1">
<h3 data-number="9.3.1" class="anchored" data-anchor-id="set-up-your-project"><span class="header-section-number">9.3.1</span> Set up your project</h3>
<section id="if-you-are-a-posit.cloud-user" class="level4" data-number="9.3.1.1">
<h4 data-number="9.3.1.1" class="anchored" data-anchor-id="if-you-are-a-posit.cloud-user"><span class="header-section-number">9.3.1.1</span> If you are a posit.cloud user</h4>
<ol type="1">
<li>From your posit.cloud account, go to <a href="https://posit.cloud/content/3753507">this shared project</a></li>
<li>Click <strong>Save a permanent copy</strong> so you have your own version.</li>
<li>Rename the project <code>yourname-sped</code> <strong>but use your name</strong>.</li>
<li>You can skip to the <strong>Open, read and run</strong> section below.</li>
</ol>
</section>
<section id="if-you-are-using-rstudio-desktop" class="level4" data-number="9.3.1.2">
<h4 data-number="9.3.1.2" class="anchored" data-anchor-id="if-you-are-using-rstudio-desktop"><span class="header-section-number">9.3.1.2</span> If you are using RStudio Desktop</h4>
<ol type="1">
<li>Go to <a href="https://github.com/utdata/rwdir/blob/main/resources/rwdir-sped-template.zip">this page</a>. Yes, it looks like you can’t see anything, but …</li>
<li>Look for the <strong>Download</strong> button and download the zip file.</li>
<li>Find that on your computer and uncompress it.</li>
<li>Rename the folder to <code>yourname-sped</code> <strong>but use your name</strong>.</li>
<li>Move the folder to your <code>rwd</code> folder or wherever you’ve been saving your class projects.</li>
<li>In RStudio, choose File &gt; New Project. <strong>Choose EXISTING Directory</strong> at the next step and then find the folder you just moved. Use that to create your project.</li>
</ol>
</section>
</section>
<section id="open-read-and-run" class="level3" data-number="9.3.2">
<h3 data-number="9.3.2" class="anchored" data-anchor-id="open-read-and-run"><span class="header-section-number">9.3.2</span> Open, read and run</h3>
<p>Once you have your project set up …</p>
<ol type="1">
<li>Open up the <code>01-import</code> notebook.</li>
<li>Read every line</li>
<li>Run each chunk as you do.</li>
</ol>
<p>Go ahead. I’ll wait.</p>
<div style="width:100%;height:0;padding-bottom:56%;position:relative;">
<iframe src="https://giphy.com/embed/ExSXXwQmCSMWKor0qb" width="100%" height="100%" style="position:absolute" frameborder="0" class="giphy-embed" allowfullscreen="">
</iframe>
</div>
<p>
<a href="https://giphy.com/gifs/snl-saturday-night-live-season-47-ExSXXwQmCSMWKor0qb">via GIPHY</a>
</p>
<p>There is a lot to take in there about where the data came from and how we dealt with it. Here is where you end up:</p>
<!-- UPDATE THE DATA FILES VALUE WHEN NEW YEAR IS ADDED -->
<ul>
<li><strong>You have 10 data files for each year and one reference file imported.</strong></li>
</ul>
</section>
</section>
<section id="merging-data-together" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="merging-data-together"><span class="header-section-number">9.4</span> Merging data together</h2>
<p>OK, so we have all these different yearly files. Wouldn’t it be a lot easier if these were ONE thing? Indeed, we can <strong>merge</strong> these files together by stacking them on top of each other. Let’s review the concept using Starburst data:</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/9WA8YxMjpnI" title="Merge" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
<p>Here’s another representation of the concept. You have two data sets and you stack them on top of each other where the column names match. (Note here that identical rows in both data sets remain).</p>
<p><img src="images/bind_rows.png" class="img-fluid"></p>
<p>Since all of our data files have the same column names, we can easily merge them with function <strong><code>bind_rows()</code></strong>.</p>
<p>Let’s demonstrate through building it.</p>
<ol type="1">
<li>Start a new section on your R Markdown document and note you are merging data</li>
<li>Add a chunk with just the <code>dstud13</code> data and run it.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>dstud13</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,228 × 5
   district year  dpetallc dpetspec dpetspep
   &lt;chr&gt;    &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
 1 001902   2013       595       73     12.3
 2 001903   2013      1236      113      9.1
 3 001904   2013       751       81     10.8
 4 001906   2013       406       45     11.1
 5 001907   2013      3288      252      7.7
 6 001908   2013      1619      151      9.3
 7 001909   2013       439       48     10.9
 8 002901   2013      3617      250      6.9
 9 003801   2013       635       45      7.1
10 003902   2013      2726      196      7.2
# ℹ 1,218 more rows</code></pre>
</div>
</div>
<p>The result shows there are <strong>1228</strong> rows and <strong>5</strong> variables in the data, which should match what shows for <code>dstud13</code> in your Environment tab.</p>
<ol type="1">
<li>Now <strong>edit</strong> that chunk to use <code>bind_rows()</code> with <code>dstud14</code> and run it.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>dstud13 <span class="sc">|&gt;</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(dstud14)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,455 × 5
   district year  dpetallc dpetspec dpetspep
   &lt;chr&gt;    &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
 1 001902   2013       595       73     12.3
 2 001903   2013      1236      113      9.1
 3 001904   2013       751       81     10.8
 4 001906   2013       406       45     11.1
 5 001907   2013      3288      252      7.7
 6 001908   2013      1619      151      9.3
 7 001909   2013       439       48     10.9
 8 002901   2013      3617      250      6.9
 9 003801   2013       635       45      7.1
10 003902   2013      2726      196      7.2
# ℹ 2,445 more rows</code></pre>
</div>
</div>
<p>This shows we now have <strong>2455</strong> rows and <strong>5</strong> variables. This is good … we’ve addded the rows of <code>dstud14</code> but we don’t have any new columns because the column names were identical.</p>
<p>Now <strong>edit the chunk</strong> to do all these things:</p>
<ol type="1">
<li>Within the <code>bind_rows()</code> function, also add the <code>dstud15</code> dataframe so you can see you are adding more on.</li>
<li>Save the result of the merge into a new data frame called <code>sped_merged</code>.</li>
<li>At the bottom of the chunk print out the <code>sped_merged</code> tibble and pipe it into <code>count(year)</code> so you can make sure you continue to add rows correctly.</li>
</ol>
<p>It should look like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>sped_merged <span class="ot">&lt;-</span> dstud13 <span class="sc">|&gt;</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_rows</span>(</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    dstud14,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    dstud15</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># we use this to ensure we bind correctly when we add new years</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>sped_merged <span class="sc">|&gt;</span> <span class="fu">count</span>(year)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  year      n
  &lt;chr&gt; &lt;int&gt;
1 2013   1228
2 2014   1227
3 2015   1219</code></pre>
</div>
</div>
<p>(In the screencast video you might also see each new datatable added in their own <code>bind_rows()</code> function instead of all in one. Either works.)</p>
<p>We are NOT saving the <code>count()</code> result into a new object; We are just printing it to our screen to make sure we get all the years.</p>
<p>Now that we know this is working, you’ll finish this out on your own.</p>
<ol type="1">
<li><strong>Edit your chunk</strong> to add <code>bind_rows()</code> for the rest of the files <code>dstud16</code> through <code>dstud22</code>. You just keep tacking them on like we did with <code>dstud15</code>.</li>
<li>After you are done, make sure you look at the <code>sped_merged</code> listing in your environment to make sure you end up with a count for each year of data.</li>
</ol>
<p>OK, we have all our data in one file, but we still don’t know the district names. It’s time to <strong>Join</strong> our data with our reference file.</p>
</section>
<section id="about-joins" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="about-joins"><span class="header-section-number">9.5</span> About joins</h2>
<p>OK, before we go further we need to talk about joining data. It’s one of those <a href="https://vimeo.com/showcase/7320305">Basic Data Journalism Functions</a> …</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/T6PPd-ukFyk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
</iframe>
<p>What joins do is match rows from two data sets that have a column of common values, like an ID or county name. (The <code>district</code> ID column in our case). Columns from the second data set will be added based on where the ID’s match.</p>
<p>There are several types of <a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">joins</a>. We describe these as left vs right based on which table we reference first (which is the left one). How much data you end up with depends on the “direction” of the join.</p>
<ul>
<li>An <strong>inner_join</strong> puts together columns from both tables where there are matching rows. If there are records in either table where the IDs don’t match, they are dropped.</li>
<li>A <strong>left_join</strong> will keep ALL the rows of your first table, then bring over columns from the second table where the IDs match. If there isn’t a match in the second table, then new values will be blank in the new columns.</li>
<li>A <strong>right_join</strong> is the opposite of that: You keep ALL the rows of the second table, but bring over only matching rows from the first.</li>
<li>A <strong>full_join</strong> keeps all rows and columns from both tables, joining rows when they match.</li>
</ul>
<p>Here are two common ways to think of this visually.</p>
<p>In the image below, The orange represents the data that remains after the join.</p>
<p><img src="images/joins-description.png" class="img-fluid"></p>
<p>This next visual shows this as tables where only two rows “match” so you can see how non-matches are handled (the lighter color represents blank values). The functions listed there are the tidyverse versions of each join type.</p>
<p><img src="images/join_types.png" class="img-fluid"></p>
<section id="joining-our-reference-table" class="level3" data-number="9.5.1">
<h3 data-number="9.5.1" class="anchored" data-anchor-id="joining-our-reference-table"><span class="header-section-number">9.5.1</span> Joining our reference table</h3>
<p>In our case we start with the <code>dref</code> data and then use an <strong>inner_join</strong> to add all the yearly data values. We’re doing it in this order so the <code>dref</code> values are listed first in our resulting table.</p>
<ol type="1">
<li>Start a new Markdown section and note we are joining the reference data</li>
<li>Add the chunk below and run it</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>sped_joined <span class="ot">&lt;-</span> dref <span class="sc">|&gt;</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">inner_join</span>(sped_merged, <span class="at">by =</span> <span class="st">"district"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>sped_joined <span class="sc">|&gt;</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  district distname  cntyname dflalted dflchart year  dpetallc dpetspec dpetspep
  &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;    &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
1 001902   CAYUGA I… ANDERSON N        N        2013       595       73     12.3
2 001902   CAYUGA I… ANDERSON N        N        2014       553       76     13.7
3 001902   CAYUGA I… ANDERSON N        N        2015       577       76     13.2
4 001902   CAYUGA I… ANDERSON N        N        2016       568       78     13.7
5 001902   CAYUGA I… ANDERSON N        N        2017       576       82     14.2
6 001902   CAYUGA I… ANDERSON N        N        2018       575       83     14.4</code></pre>
</div>
</div>
<p>You might also <code>glimpse()</code> it so you can see all the columns have been added.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>sped_joined <span class="sc">|&gt;</span> <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 11,882
Columns: 9
$ district &lt;chr&gt; "001902", "001902", "001902", "001902", "001902", "001902", "…
$ distname &lt;chr&gt; "CAYUGA ISD", "CAYUGA ISD", "CAYUGA ISD", "CAYUGA ISD", "CAYU…
$ cntyname &lt;chr&gt; "ANDERSON", "ANDERSON", "ANDERSON", "ANDERSON", "ANDERSON", "…
$ dflalted &lt;chr&gt; "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "…
$ dflchart &lt;chr&gt; "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "N", "…
$ year     &lt;chr&gt; "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020…
$ dpetallc &lt;dbl&gt; 595, 553, 577, 568, 576, 575, 564, 557, 535, 574, 1236, 1207,…
$ dpetspec &lt;dbl&gt; 73, 76, 76, 78, 82, 83, 84, 82, 78, 84, 113, 107, 126, 144, 1…
$ dpetspep &lt;dbl&gt; 12.3, 13.7, 13.2, 13.7, 14.2, 14.4, 14.9, 14.7, 14.6, 14.6, 9…</code></pre>
</div>
</div>
<p>Let’s explain what is going on here:</p>
<ul>
<li>We are creating a new bucket <code>sped_joined</code> to save our data.</li>
<li>We start with <code>dref</code> so those fields will be listed first in our result.</li>
<li>We then pipe into <code>inner_join()</code> to <code>sped_merged</code>, which will attach our <code>dref</code> data to our merged data when the ID matches in the <code>district</code> variable.</li>
<li>The <code>by = "district"</code> argument ensures that we are matching based on the <code>district</code> column in both data sets.</li>
</ul>
<p>We could’ve left out the <code>by =</code> argument and R would match columns of the same name, but it is best practice to specify your joining columns so it is clear what is happening. You wouldn’t want to be surprised by other columns of the same name that you didn’t want to join on. If you wanted to specify join columns of different names it would look like this: <code>df1 |&gt; inner_join(df2, by = c("df1_id" = "df2_id"))</code></p>
<p>There are now <strong>11882</strong> rows in our joined data, fewer than what was in the original merged file because some districts (mostly charters) have closed and were not in our reference file. We are comparing only districts that have been open during this time period. For that matter, we don’t want charter or alternative education districts at all, so we’ll drop those next.</p>
</section>
</section>
<section id="some-cleanup-filter-and-select" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="some-cleanup-filter-and-select"><span class="header-section-number">9.6</span> Some cleanup: filter and select</h2>
<p>Filtering and selecting data is something we’ve done time and again, so you should be able to do this on your own.</p>
<p>You will next remove the charter and alternative education districts. This is a judgement call on our part to focus on just traditional public schools. We can always come back later and change if needed.</p>
<p>You’ll also remove and rename columns to make the more descriptive.</p>
<ol type="1">
<li>Start a new markdown section and note you are cleaning up your data.</li>
<li>Create an R chunk and start with the <code>sped_joined</code> and then do all these things …</li>
<li>Use <code>filter()</code> to keep rows where:
<ul>
<li>the <code>dflalted</code> field is “N”</li>
<li>AND the <code>dflchart</code> field is “N”</li>
</ul></li>
<li>Use <code>select()</code> to:
<ul>
<li>remove (or not include) the <code>dflalted</code> and <code>dflchart</code> columns. (You can only do this AFTER you filter with them!)</li>
</ul></li>
<li>Use <code>select()</code> or <code>rename()</code> to rename the following columns:
<ul>
<li>change <code>dpetallc</code> to <code>all_count</code></li>
<li>change <code>dpetspec</code> to <code>sped_count</code></li>
<li>change <code>dpetspep</code> to <code>sped_percent</code></li>
</ul></li>
<li>Make sure all your changes are saved into a new data frame called <code>sped_cleaned</code>.</li>
</ol>
<p>I really, really suggest you don’t try to write that all at once. Build it one line at a time so you can see the result as you build your code.</p>
<details>
<summary>
I’m being too nice here
</summary>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>sped_cleaned <span class="ot">&lt;-</span> sped_joined <span class="sc">|&gt;</span> </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(dflalted <span class="sc">==</span> <span class="st">"N"</span> <span class="sc">&amp;</span> dflchart <span class="sc">==</span> <span class="st">"N"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    district,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    distname,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    cntyname,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    year,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">all_count =</span> dpetallc,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">sped_count =</span> dpetspec,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">sped_percent =</span> dpetspep</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</details>
<p><br></p>
<p>You should end up with <strong>10204</strong> rows and <strong>7</strong> variables.</p>
</section>
<section id="create-an-audit-benchmark-column" class="level2" data-number="9.7">
<h2 data-number="9.7" class="anchored" data-anchor-id="create-an-audit-benchmark-column"><span class="header-section-number">9.7</span> Create an audit benchmark column</h2>
<p>Part of this story is to note when a district is above the “8.5%” benchmark that the TEA was using for their audit calculations. It would be useful to have a column that noted if a district was above or below that threshold so we could plot districts based on that flag. We’ll create this new column and introduce the logic of <a href="https://dplyr.tidyverse.org/reference/if_else.html"><code>if_else()</code></a>.</p>
<p>OK, our data looks like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>sped_cleaned <span class="sc">|&gt;</span> <span class="fu">head</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  district distname   cntyname year  all_count sped_count sped_percent
  &lt;chr&gt;    &lt;chr&gt;      &lt;chr&gt;    &lt;chr&gt;     &lt;dbl&gt;      &lt;dbl&gt;        &lt;dbl&gt;
1 001902   CAYUGA ISD ANDERSON 2013        595         73         12.3
2 001902   CAYUGA ISD ANDERSON 2014        553         76         13.7
3 001902   CAYUGA ISD ANDERSON 2015        577         76         13.2
4 001902   CAYUGA ISD ANDERSON 2016        568         78         13.7
5 001902   CAYUGA ISD ANDERSON 2017        576         82         14.2
6 001902   CAYUGA ISD ANDERSON 2018        575         83         14.4</code></pre>
</div>
</div>
<p>We want to add a column called <code>audit_flag</code> that says <strong>ABOVE</strong> if the <code>sped_percent</code> is above “8.5”, and says <strong>BELOW</strong> if it isn’t. This is a simple true/false condition that is perfect for the <code>if_else()</code> function.</p>
<ol type="1">
<li>Add a new Markdown section and note that you are adding an audit flag column</li>
<li>Create an r chunk that and run it and I’ll explain after.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>sped_flag <span class="ot">&lt;-</span> sped_cleaned <span class="sc">|&gt;</span> </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">audit_flag =</span> <span class="fu">if_else</span>(sped_percent <span class="sc">&gt;</span> <span class="fl">8.5</span>, <span class="st">"ABOVE"</span>, <span class="st">"BELOW"</span>))</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># this pulls 30 random rows so I can check results</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>sped_flag <span class="sc">|&gt;</span> <span class="fu">sample_n</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 8
   district distname cntyname year  all_count sped_count sped_percent audit_flag
   &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;    &lt;chr&gt;     &lt;dbl&gt;      &lt;dbl&gt;        &lt;dbl&gt; &lt;chr&gt;     
 1 109913   BLUM ISD HILL     2022        344         50         14.5 ABOVE     
 2 153904   TAHOKA … LYNN     2022        597         83         13.9 ABOVE     
 3 073901   CHILTON… FALLS    2014        509         59         11.6 ABOVE     
 4 015915   NORTHSI… BEXAR    2016     104437      11538         11   ABOVE     
 5 129910   SCURRY-… KAUFMAN  2019       1052        110         10.5 ABOVE     
 6 062901   CUERO I… DEWITT   2022       1920        319         16.6 ABOVE     
 7 076904   ROTAN I… FISHER   2017        246         19          7.7 BELOW     
 8 216901   STERLIN… STERLING 2016        329         33         10   ABOVE     
 9 018905   WALNUT … BOSQUE   2014        174         19         10.9 ABOVE     
10 043901   ALLEN I… COLLIN   2021      21564       2759         12.8 ABOVE     </code></pre>
</div>
</div>
<p>Let’s walk through the code above:</p>
<ul>
<li>We’re making a new data frame called <code>sped_flag</code> and then starting with <code>sped_cleaned</code>.</li>
<li>We use <code>mutate()</code> to create a new column and we name it <code>audit_flag</code>.</li>
<li>We set the value of <code>audit_flag</code> to be the result of this <code>if_else()</code> function. That function takes three arguments: A condition test (<code>sped_percent &gt; 8.5</code> in our case), what is the result if the condition is true (“ABOVE” in our case), and what is the result if the condition is NOT true (“BELOW”) in our case.</li>
<li>Lastly we print out the new data <code>sped_cleaned</code> and pipe it into <code>sample_n()</code> which gives us a number of random rows from the data. I do this because the top of the data was all TRUE so I couldn’t see if the mutate worked properly or not. (Always check your calculations!!)</li>
</ul>
</section>
<section id="export-the-data" class="level2" data-number="9.8">
<h2 data-number="9.8" class="anchored" data-anchor-id="export-the-data"><span class="header-section-number">9.8</span> Export the data</h2>
<p>This is something you’ve done a number of times as well, so I leave you to you:</p>
<ol type="1">
<li>Make a new section and note you are exporting the data</li>
<li>Export your <code>sped_flag</code> data using <code>write_rds()</code> and save it in your <code>data-processed</code> folder.</li>
</ol>
<p>In the next chapter we’ll build an analysis notebook to find our answers!</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./tidy-data.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Tidy data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./answers.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Plotting for answers</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>