<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 12 Joining census data | Reporting with Data in R</title>
  <meta name="description" content="Chapter 12 Joining census data | Reporting with Data in R is a series of lessons and instructions used in courses in the School of Journalism and Media, Moody College of Communication at the University of Texas at Austin. The course is taught by Christian McDonald and Jo Lukito." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 12 Joining census data | Reporting with Data in R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Chapter 12 Joining census data | Reporting with Data in R is a series of lessons and instructions used in courses in the School of Journalism and Media, Moody College of Communication at the University of Texas at Austin. The course is taught by Christian McDonald and Jo Lukito." />
  <meta name="github-repo" content="utdata/rwdir" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 12 Joining census data | Reporting with Data in R" />
  
  <meta name="twitter:description" content="Chapter 12 Joining census data | Reporting with Data in R is a series of lessons and instructions used in courses in the School of Journalism and Media, Moody College of Communication at the University of Texas at Austin. The course is taught by Christian McDonald and Jo Lukito." />
  

<meta name="author" content="Christian McDonald and Jo Lukito" />


<meta name="date" content="2022-03-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="census-intro.html"/>
<link rel="next" href="mastery.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<style type="text/css">
  p.caption {
    color: #777;
    margin-top: 10px;
  }
  p code, pre, pre code, li code {
    background-color: #DCDCDC !important;
  }
  detail {
    margin-bottom: 30px;
  }
</style>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Reporting with Data in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About this book</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#a-word-from-prof.-mcdonald"><i class="fa fa-check"></i>A word from Prof. McDonald</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#tips-on-the-book-style"><i class="fa fa-check"></i>Tips on the book style</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#things-to-do"><i class="fa fa-check"></i>Things to do</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#notes-some-important"><i class="fa fa-check"></i>Notes, some important</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#copy-code-blocks"><i class="fa fa-check"></i>Copy code blocks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#about-the-authors"><i class="fa fa-check"></i>About the authors</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#christian-mcdonald"><i class="fa fa-check"></i>Christian McDonald</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#jo-lukito"><i class="fa fa-check"></i>Jo Lukito</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i>License</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#other-resources"><i class="fa fa-check"></i>Other resources</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="install.html"><a href="install.html"><i class="fa fa-check"></i><b>1</b> Install Party</a>
<ul>
<li class="chapter" data-level="1.1" data-path="install.html"><a href="install.html#mac-vs-pc"><i class="fa fa-check"></i><b>1.1</b> Mac vs PC</a></li>
<li class="chapter" data-level="1.2" data-path="install.html"><a href="install.html#installing-r"><i class="fa fa-check"></i><b>1.2</b> Installing R</a></li>
<li class="chapter" data-level="1.3" data-path="install.html"><a href="install.html#installing-rstudio"><i class="fa fa-check"></i><b>1.3</b> Installing RStudio</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="install.html"><a href="install.html#getting-git-errors-on-macs"><i class="fa fa-check"></i><b>1.3.1</b> Getting “Git” errors on Macs</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="install.html"><a href="install.html#class-project-folder"><i class="fa fa-check"></i><b>1.4</b> Class project folder</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#rstudio-tour"><i class="fa fa-check"></i><b>2.1</b> RStudio tour</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#updating-preferences"><i class="fa fa-check"></i><b>2.2</b> Updating preferences</a></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#starting-a-new-project"><i class="fa fa-check"></i><b>2.3</b> Starting a new Project</a></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#using-r-notebooks"><i class="fa fa-check"></i><b>2.4</b> Using R Notebooks</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="intro.html"><a href="intro.html#create-your-first-notebook"><i class="fa fa-check"></i><b>2.4.1</b> Create your first notebook</a></li>
<li class="chapter" data-level="2.4.2" data-path="intro.html"><a href="intro.html#save-the-.rmd-file"><i class="fa fa-check"></i><b>2.4.2</b> Save the .Rmd file</a></li>
<li class="chapter" data-level="2.4.3" data-path="intro.html"><a href="intro.html#run-the-notebook"><i class="fa fa-check"></i><b>2.4.3</b> Run the notebook</a></li>
<li class="chapter" data-level="2.4.4" data-path="intro.html"><a href="intro.html#a-note-about-rmarkdown"><i class="fa fa-check"></i><b>2.4.4</b> A note about RMarkdown</a></li>
<li class="chapter" data-level="2.4.5" data-path="intro.html"><a href="intro.html#adding-new-code-chunks"><i class="fa fa-check"></i><b>2.4.5</b> Adding new code chunks</a></li>
<li class="chapter" data-level="2.4.6" data-path="intro.html"><a href="intro.html#practice-adding-code-chunks"><i class="fa fa-check"></i><b>2.4.6</b> Practice adding code chunks</a></li>
<li class="chapter" data-level="2.4.7" data-path="intro.html"><a href="intro.html#preview-the-report"><i class="fa fa-check"></i><b>2.4.7</b> Preview the report</a></li>
<li class="chapter" data-level="2.4.8" data-path="intro.html"><a href="intro.html#the-toolbar"><i class="fa fa-check"></i><b>2.4.8</b> The toolbar</a></li>
<li class="chapter" data-level="2.4.9" data-path="intro.html"><a href="intro.html#knit-the-final-workbook"><i class="fa fa-check"></i><b>2.4.9</b> Knit the final workbook</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="intro.html"><a href="intro.html#turning-in-our-projects"><i class="fa fa-check"></i><b>2.5</b> Turning in our projects</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="counts-import.html"><a href="counts-import.html"><i class="fa fa-check"></i><b>3</b> Summarize with count - import</a>
<ul>
<li class="chapter" data-level="3.1" data-path="counts-import.html"><a href="counts-import.html#learning-goals-of-this-lesson"><i class="fa fa-check"></i><b>3.1</b> Learning goals of this lesson</a></li>
<li class="chapter" data-level="3.2" data-path="counts-import.html"><a href="counts-import.html#basic-steps-of-this-lesson"><i class="fa fa-check"></i><b>3.2</b> Basic steps of this lesson</a></li>
<li class="chapter" data-level="3.3" data-path="counts-import.html"><a href="counts-import.html#create-a-new-project"><i class="fa fa-check"></i><b>3.3</b> Create a new project</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="counts-import.html"><a href="counts-import.html#describe-the-goals-of-the-notebook"><i class="fa fa-check"></i><b>3.3.1</b> Describe the goals of the notebook</a></li>
<li class="chapter" data-level="3.3.2" data-path="counts-import.html"><a href="counts-import.html#the-r-package-environment"><i class="fa fa-check"></i><b>3.3.2</b> The R Package environment</a></li>
<li class="chapter" data-level="3.3.3" data-path="counts-import.html"><a href="counts-import.html#installing-and-using-packages"><i class="fa fa-check"></i><b>3.3.3</b> Installing and using packages</a></li>
<li class="chapter" data-level="3.3.4" data-path="counts-import.html"><a href="counts-import.html#load-the-libraries"><i class="fa fa-check"></i><b>3.3.4</b> Load the libraries</a></li>
<li class="chapter" data-level="3.3.5" data-path="counts-import.html"><a href="counts-import.html#create-a-directory-for-your-data"><i class="fa fa-check"></i><b>3.3.5</b> Create a directory for your data</a></li>
<li class="chapter" data-level="3.3.6" data-path="counts-import.html"><a href="counts-import.html#about-data-sources"><i class="fa fa-check"></i><b>3.3.6</b> About data sources</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="counts-import.html"><a href="counts-import.html#the-billboard-hot-100"><i class="fa fa-check"></i><b>3.4</b> The Billboard Hot 100</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="counts-import.html"><a href="counts-import.html#data-dictionary"><i class="fa fa-check"></i><b>3.4.1</b> Data dictionary</a></li>
<li class="chapter" data-level="3.4.2" data-path="counts-import.html"><a href="counts-import.html#lets-download-our-data"><i class="fa fa-check"></i><b>3.4.2</b> Let’s download our data</a></li>
<li class="chapter" data-level="3.4.3" data-path="counts-import.html"><a href="counts-import.html#consider-commenting-the-download"><i class="fa fa-check"></i><b>3.4.3</b> Consider commenting the download</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="counts-import.html"><a href="counts-import.html#import-the-data"><i class="fa fa-check"></i><b>3.5</b> Import the data</a></li>
<li class="chapter" data-level="3.6" data-path="counts-import.html"><a href="counts-import.html#assign-our-import-to-an-r-object"><i class="fa fa-check"></i><b>3.6</b> Assign our import to an R object</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="counts-import.html"><a href="counts-import.html#print-a-peek-to-your-r-notebook"><i class="fa fa-check"></i><b>3.6.1</b> Print a peek to your R Notebook</a></li>
<li class="chapter" data-level="3.6.2" data-path="counts-import.html"><a href="counts-import.html#glimpse-the-data"><i class="fa fa-check"></i><b>3.6.2</b> Glimpse the data</a></li>
<li class="chapter" data-level="3.6.3" data-path="counts-import.html"><a href="counts-import.html#about-the-pipe"><i class="fa fa-check"></i><b>3.6.3</b> About the pipe %&gt;%</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="counts-import.html"><a href="counts-import.html#cleaning-data"><i class="fa fa-check"></i><b>3.7</b> Cleaning data</a></li>
<li class="chapter" data-level="3.8" data-path="counts-import.html"><a href="counts-import.html#cleaning-column-names"><i class="fa fa-check"></i><b>3.8</b> Cleaning column names</a></li>
<li class="chapter" data-level="3.9" data-path="counts-import.html"><a href="counts-import.html#fixing-the-date"><i class="fa fa-check"></i><b>3.9</b> Fixing the date</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="counts-import.html"><a href="counts-import.html#working-with-mutate"><i class="fa fa-check"></i><b>3.9.1</b> Working with mutate()</a></li>
<li class="chapter" data-level="3.9.2" data-path="counts-import.html"><a href="counts-import.html#check-the-result"><i class="fa fa-check"></i><b>3.9.2</b> Check the result!</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="counts-import.html"><a href="counts-import.html#arrange-the-data"><i class="fa fa-check"></i><b>3.10</b> Arrange the data</a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="counts-import.html"><a href="counts-import.html#getting-summary-stats"><i class="fa fa-check"></i><b>3.10.1</b> Getting summary stats</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="counts-import.html"><a href="counts-import.html#selecting-columns"><i class="fa fa-check"></i><b>3.11</b> Selecting columns</a></li>
<li class="chapter" data-level="3.12" data-path="counts-import.html"><a href="counts-import.html#exporting-data"><i class="fa fa-check"></i><b>3.12</b> Exporting data</a>
<ul>
<li class="chapter" data-level="3.12.1" data-path="counts-import.html"><a href="counts-import.html#single-notebook-philosophy"><i class="fa fa-check"></i><b>3.12.1</b> Single-notebook philosophy</a></li>
<li class="chapter" data-level="3.12.2" data-path="counts-import.html"><a href="counts-import.html#exporting-as-rds"><i class="fa fa-check"></i><b>3.12.2</b> Exporting as rds</a></li>
</ul></li>
<li class="chapter" data-level="3.13" data-path="counts-import.html"><a href="counts-import.html#naming-chunks"><i class="fa fa-check"></i><b>3.13</b> Naming chunks</a></li>
<li class="chapter" data-level="3.14" data-path="counts-import.html"><a href="counts-import.html#knit-your-page"><i class="fa fa-check"></i><b>3.14</b> Knit your page</a></li>
<li class="chapter" data-level="3.15" data-path="counts-import.html"><a href="counts-import.html#review-of-what-weve-learned-so-far"><i class="fa fa-check"></i><b>3.15</b> Review of what we’ve learned so far</a></li>
<li class="chapter" data-level="3.16" data-path="counts-import.html"><a href="counts-import.html#whats-next"><i class="fa fa-check"></i><b>3.16</b> What’s next</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="count-analysis.html"><a href="count-analysis.html"><i class="fa fa-check"></i><b>4</b> Summarize with count - analysis</a>
<ul>
<li class="chapter" data-level="4.1" data-path="count-analysis.html"><a href="count-analysis.html#goals-of-this-lesson"><i class="fa fa-check"></i><b>4.1</b> Goals of this lesson</a></li>
<li class="chapter" data-level="4.2" data-path="count-analysis.html"><a href="count-analysis.html#the-questions-well-answer"><i class="fa fa-check"></i><b>4.2</b> The questions we’ll answer</a></li>
<li class="chapter" data-level="4.3" data-path="count-analysis.html"><a href="count-analysis.html#setting-up-an-analysis-notebook"><i class="fa fa-check"></i><b>4.3</b> Setting up an analysis notebook</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="count-analysis.html"><a href="count-analysis.html#import-the-data-on-your-own"><i class="fa fa-check"></i><b>4.3.1</b> Import the data on your own</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="count-analysis.html"><a href="count-analysis.html#introducing-dplyr"><i class="fa fa-check"></i><b>4.4</b> Introducing dplyr</a></li>
<li class="chapter" data-level="4.5" data-path="count-analysis.html"><a href="count-analysis.html#most-appearances"><i class="fa fa-check"></i><b>4.5</b> Most appearances</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="count-analysis.html"><a href="count-analysis.html#group-aggregate"><i class="fa fa-check"></i><b>4.5.1</b> Group &amp; Aggregate</a></li>
<li class="chapter" data-level="4.5.2" data-path="count-analysis.html"><a href="count-analysis.html#summarize"><i class="fa fa-check"></i><b>4.5.2</b> Summarize</a></li>
<li class="chapter" data-level="4.5.3" data-path="count-analysis.html"><a href="count-analysis.html#group-by"><i class="fa fa-check"></i><b>4.5.3</b> Group by</a></li>
<li class="chapter" data-level="4.5.4" data-path="count-analysis.html"><a href="count-analysis.html#arrange-the-results"><i class="fa fa-check"></i><b>4.5.4</b> Arrange the results</a></li>
<li class="chapter" data-level="4.5.5" data-path="count-analysis.html"><a href="count-analysis.html#get-the-top-of-the-list"><i class="fa fa-check"></i><b>4.5.5</b> Get the top of the list</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="count-analysis.html"><a href="count-analysis.html#songperformer-with-most-appearances"><i class="fa fa-check"></i><b>4.6</b> Song/performer with most appearances</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="count-analysis.html"><a href="count-analysis.html#introducing-filter"><i class="fa fa-check"></i><b>4.6.1</b> Introducing filter()</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="count-analysis.html"><a href="count-analysis.html#songperformer-with-most-weeks-at-no.-1"><i class="fa fa-check"></i><b>4.7</b> Song/Performer with most weeks at No. 1</a></li>
<li class="chapter" data-level="4.8" data-path="count-analysis.html"><a href="count-analysis.html#performer-with-most-songs-to-reach-no.-1"><i class="fa fa-check"></i><b>4.8</b> Performer with most songs to reach No. 1</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="count-analysis.html"><a href="count-analysis.html#using-distinct"><i class="fa fa-check"></i><b>4.8.1</b> Using distinct()</a></li>
<li class="chapter" data-level="4.8.2" data-path="count-analysis.html"><a href="count-analysis.html#summarize-the-performers"><i class="fa fa-check"></i><b>4.8.2</b> Summarize the performers</a></li>
<li class="chapter" data-level="4.8.3" data-path="count-analysis.html"><a href="count-analysis.html#filter-for-a-good-cutoff"><i class="fa fa-check"></i><b>4.8.3</b> Filter for a good cutoff</a></li>
</ul></li>
<li class="chapter" data-level="4.9" data-path="count-analysis.html"><a href="count-analysis.html#no.-1-hits-in-last-five-years"><i class="fa fa-check"></i><b>4.9</b> No. 1 hits in last five years</a></li>
<li class="chapter" data-level="4.10" data-path="count-analysis.html"><a href="count-analysis.html#top-10-hits-overall-on-your-own"><i class="fa fa-check"></i><b>4.10</b> Top 10 hits overall (on your own)</a></li>
<li class="chapter" data-level="4.11" data-path="count-analysis.html"><a href="count-analysis.html#a-shortcut-count"><i class="fa fa-check"></i><b>4.11</b> A shortcut: count()</a></li>
<li class="chapter" data-level="4.12" data-path="count-analysis.html"><a href="count-analysis.html#complex-filters"><i class="fa fa-check"></i><b>4.12</b> Complex filters</a>
<ul>
<li class="chapter" data-level="4.12.1" data-path="count-analysis.html"><a href="count-analysis.html#multiple-truths"><i class="fa fa-check"></i><b>4.12.1</b> Multiple truths</a></li>
<li class="chapter" data-level="4.12.2" data-path="count-analysis.html"><a href="count-analysis.html#either-is-true"><i class="fa fa-check"></i><b>4.12.2</b> Either is true</a></li>
<li class="chapter" data-level="4.12.3" data-path="count-analysis.html"><a href="count-analysis.html#mixing-criteria"><i class="fa fa-check"></i><b>4.12.3</b> Mixing criteria</a></li>
<li class="chapter" data-level="4.12.4" data-path="count-analysis.html"><a href="count-analysis.html#search-within-a-string"><i class="fa fa-check"></i><b>4.12.4</b> Search within a string</a></li>
</ul></li>
<li class="chapter" data-level="4.13" data-path="count-analysis.html"><a href="count-analysis.html#on-your-own"><i class="fa fa-check"></i><b>4.13</b> On your own</a></li>
<li class="chapter" data-level="4.14" data-path="count-analysis.html"><a href="count-analysis.html#review-of-what-weve-learned"><i class="fa fa-check"></i><b>4.14</b> Review of what we’ve learned</a></li>
<li class="chapter" data-level="4.15" data-path="count-analysis.html"><a href="count-analysis.html#turn-in-your-project"><i class="fa fa-check"></i><b>4.15</b> Turn in your project</a></li>
<li class="chapter" data-level="4.16" data-path="count-analysis.html"><a href="count-analysis.html#soundtrack-for-this-assignment"><i class="fa fa-check"></i><b>4.16</b> Soundtrack for this assignment</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="sums-import.html"><a href="sums-import.html"><i class="fa fa-check"></i><b>5</b> Summarize with math - import</a>
<ul>
<li class="chapter" data-level="5.1" data-path="sums-import.html"><a href="sums-import.html#about-the-story-military-surplus-transfers"><i class="fa fa-check"></i><b>5.1</b> About the story: Military surplus transfers</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="sums-import.html"><a href="sums-import.html#the-leso-program"><i class="fa fa-check"></i><b>5.1.1</b> The LESO program</a></li>
<li class="chapter" data-level="5.1.2" data-path="sums-import.html"><a href="sums-import.html#about-the-data"><i class="fa fa-check"></i><b>5.1.2</b> About the data</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="sums-import.html"><a href="sums-import.html#the-questions-we-will-answer"><i class="fa fa-check"></i><b>5.2</b> The questions we will answer</a></li>
<li class="chapter" data-level="5.3" data-path="sums-import.html"><a href="sums-import.html#create-your-project"><i class="fa fa-check"></i><b>5.3</b> Create your project</a></li>
<li class="chapter" data-level="5.4" data-path="sums-import.html"><a href="sums-import.html#importcleaning-notebook"><i class="fa fa-check"></i><b>5.4</b> Import/cleaning notebook</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="sums-import.html"><a href="sums-import.html#add-the-goals-of-the-notebook"><i class="fa fa-check"></i><b>5.4.1</b> Add the goals of the notebook</a></li>
<li class="chapter" data-level="5.4.2" data-path="sums-import.html"><a href="sums-import.html#add-a-setup-section"><i class="fa fa-check"></i><b>5.4.2</b> Add a setup section</a></li>
<li class="chapter" data-level="5.4.3" data-path="sums-import.html"><a href="sums-import.html#download-the-data"><i class="fa fa-check"></i><b>5.4.3</b> Download the data</a></li>
<li class="chapter" data-level="5.4.4" data-path="sums-import.html"><a href="sums-import.html#import-the-data-1"><i class="fa fa-check"></i><b>5.4.4</b> Import the data</a></li>
<li class="chapter" data-level="5.4.5" data-path="sums-import.html"><a href="sums-import.html#glimpse-the-data-1"><i class="fa fa-check"></i><b>5.4.5</b> Glimpse the data</a></li>
<li class="chapter" data-level="5.4.6" data-path="sums-import.html"><a href="sums-import.html#remove-unnecessary-columns"><i class="fa fa-check"></i><b>5.4.6</b> Remove unnecessary columns</a></li>
<li class="chapter" data-level="5.4.7" data-path="sums-import.html"><a href="sums-import.html#create-a-total_value-column"><i class="fa fa-check"></i><b>5.4.7</b> Create a total_value column</a></li>
<li class="chapter" data-level="5.4.8" data-path="sums-import.html"><a href="sums-import.html#filtering-our-data"><i class="fa fa-check"></i><b>5.4.8</b> Filtering our data</a></li>
<li class="chapter" data-level="5.4.9" data-path="sums-import.html"><a href="sums-import.html#export-cleaned-data"><i class="fa fa-check"></i><b>5.4.9</b> Export cleaned data</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="sums-import.html"><a href="sums-import.html#things-we-learned-in-this-lesson"><i class="fa fa-check"></i><b>5.5</b> Things we learned in this lesson</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sums-analyze.html"><a href="sums-analyze.html"><i class="fa fa-check"></i><b>6</b> Summarize with math - analysis</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sums-analyze.html"><a href="sums-analyze.html#learning-goals-of-this-lesson-1"><i class="fa fa-check"></i><b>6.1</b> Learning goals of this lesson</a></li>
<li class="chapter" data-level="6.2" data-path="sums-analyze.html"><a href="sums-analyze.html#questions-to-answer"><i class="fa fa-check"></i><b>6.2</b> Questions to answer</a></li>
<li class="chapter" data-level="6.3" data-path="sums-analyze.html"><a href="sums-analyze.html#set-up-the-analysis-notebook"><i class="fa fa-check"></i><b>6.3</b> Set up the analysis notebook</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="sums-analyze.html"><a href="sums-analyze.html#load-the-data-into-a-tibble"><i class="fa fa-check"></i><b>6.3.1</b> Load the data into a tibble</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="sums-analyze.html"><a href="sums-analyze.html#how-to-tackle-summaries"><i class="fa fa-check"></i><b>6.4</b> How to tackle summaries</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="sums-analyze.html"><a href="sums-analyze.html#summaries-with-math"><i class="fa fa-check"></i><b>6.4.1</b> Summaries with math</a></li>
<li class="chapter" data-level="6.4.2" data-path="sums-analyze.html"><a href="sums-analyze.html#add-the-total_value"><i class="fa fa-check"></i><b>6.4.2</b> Add the total_value</a></li>
<li class="chapter" data-level="6.4.3" data-path="sums-analyze.html"><a href="sums-analyze.html#arrange-the-results-1"><i class="fa fa-check"></i><b>6.4.3</b> Arrange the results</a></li>
<li class="chapter" data-level="6.4.4" data-path="sums-analyze.html"><a href="sums-analyze.html#consider-the-results"><i class="fa fa-check"></i><b>6.4.4</b> Consider the results</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="sums-analyze.html"><a href="sums-analyze.html#looking-a-local-agencies"><i class="fa fa-check"></i><b>6.5</b> Looking a local agencies</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="sums-analyze.html"><a href="sums-analyze.html#filtering-within-a-vector"><i class="fa fa-check"></i><b>6.5.1</b> Filtering within a vector</a></li>
<li class="chapter" data-level="6.5.2" data-path="sums-analyze.html"><a href="sums-analyze.html#use-the-vector-to-build-this-filter"><i class="fa fa-check"></i><b>6.5.2</b> Use the vector to build this filter</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="sums-analyze.html"><a href="sums-analyze.html#item-quantities-totals-for-local-agencies"><i class="fa fa-check"></i><b>6.6</b> Item quantities, totals for local agencies</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="sums-analyze.html"><a href="sums-analyze.html#build-the-lists-for-other-agencies"><i class="fa fa-check"></i><b>6.6.1</b> Build the lists for other agencies</a></li>
<li class="chapter" data-level="6.6.2" data-path="sums-analyze.html"><a href="sums-analyze.html#google-some-interesting-items"><i class="fa fa-check"></i><b>6.6.2</b> Google some interesting items</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="sums-analyze.html"><a href="sums-analyze.html#write-a-data-drop"><i class="fa fa-check"></i><b>6.7</b> Write a data drop</a></li>
<li class="chapter" data-level="6.8" data-path="sums-analyze.html"><a href="sums-analyze.html#what-we-learned-in-this-chapter"><i class="fa fa-check"></i><b>6.8</b> What we learned in this chapter</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ggplot-intro.html"><a href="ggplot-intro.html"><i class="fa fa-check"></i><b>7</b> Data Viz - Intro to ggplot</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ggplot-intro.html"><a href="ggplot-intro.html#goals-for-this-section"><i class="fa fa-check"></i><b>7.1</b> Goals for this section</a></li>
<li class="chapter" data-level="7.2" data-path="ggplot-intro.html"><a href="ggplot-intro.html#introduction-to-ggplot"><i class="fa fa-check"></i><b>7.2</b> Introduction to ggplot</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="ggplot-intro.html"><a href="ggplot-intro.html#what-i-likedislike-about-ggplot"><i class="fa fa-check"></i><b>7.2.1</b> What I like/dislike about ggplot</a></li>
<li class="chapter" data-level="7.2.2" data-path="ggplot-intro.html"><a href="ggplot-intro.html#the-grammar-of-graphics"><i class="fa fa-check"></i><b>7.2.2</b> The Grammar of Graphics</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="ggplot-intro.html"><a href="ggplot-intro.html#start-a-new-project"><i class="fa fa-check"></i><b>7.3</b> Start a new project</a></li>
<li class="chapter" data-level="7.4" data-path="ggplot-intro.html"><a href="ggplot-intro.html#the-layers-of-ggplot"><i class="fa fa-check"></i><b>7.4</b> The layers of ggplot</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="ggplot-intro.html"><a href="ggplot-intro.html#build-the-base-layer"><i class="fa fa-check"></i><b>7.4.1</b> Build the base layer</a></li>
<li class="chapter" data-level="7.4.2" data-path="ggplot-intro.html"><a href="ggplot-intro.html#layers-can-we-add-to-our-plots"><i class="fa fa-check"></i><b>7.4.2</b> Layers can we add to our plots</a></li>
<li class="chapter" data-level="7.4.3" data-path="ggplot-intro.html"><a href="ggplot-intro.html#add-geom_point"><i class="fa fa-check"></i><b>7.4.3</b> Add geom_point</a></li>
<li class="chapter" data-level="7.4.4" data-path="ggplot-intro.html"><a href="ggplot-intro.html#adding-other-mappings"><i class="fa fa-check"></i><b>7.4.4</b> Adding other mappings</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="ggplot-intro.html"><a href="ggplot-intro.html#lets-build-a-bar-chart"><i class="fa fa-check"></i><b>7.5</b> Let’s build a bar chart</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="ggplot-intro.html"><a href="ggplot-intro.html#prepare-the-data"><i class="fa fa-check"></i><b>7.5.1</b> Prepare the data</a></li>
<li class="chapter" data-level="7.5.2" data-path="ggplot-intro.html"><a href="ggplot-intro.html#build-our-plot-with-geom_col"><i class="fa fa-check"></i><b>7.5.2</b> Build our plot with geom_col</a></li>
<li class="chapter" data-level="7.5.3" data-path="ggplot-intro.html"><a href="ggplot-intro.html#add-the-geom_col-layer"><i class="fa fa-check"></i><b>7.5.3</b> Add the geom_col layer</a></li>
<li class="chapter" data-level="7.5.4" data-path="ggplot-intro.html"><a href="ggplot-intro.html#flip-the-axes"><i class="fa fa-check"></i><b>7.5.4</b> Flip the axes</a></li>
<li class="chapter" data-level="7.5.5" data-path="ggplot-intro.html"><a href="ggplot-intro.html#reorder-the-bars"><i class="fa fa-check"></i><b>7.5.5</b> Reorder the bars</a></li>
<li class="chapter" data-level="7.5.6" data-path="ggplot-intro.html"><a href="ggplot-intro.html#adding-a-geom_text-layer"><i class="fa fa-check"></i><b>7.5.6</b> Adding a geom_text layer</a></li>
<li class="chapter" data-level="7.5.7" data-path="ggplot-intro.html"><a href="ggplot-intro.html#add-some-titles-and-more-labels"><i class="fa fa-check"></i><b>7.5.7</b> Add some titles and more labels</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="ggplot-intro.html"><a href="ggplot-intro.html#on-your-own-ice-cream"><i class="fa fa-check"></i><b>7.6</b> On your own: Ice cream!</a></li>
<li class="chapter" data-level="7.7" data-path="ggplot-intro.html"><a href="ggplot-intro.html#what-weve-learned"><i class="fa fa-check"></i><b>7.7</b> What we’ve learned</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ggplot-more.html"><a href="ggplot-more.html"><i class="fa fa-check"></i><b>8</b> Deeper into ggplot</a>
<ul>
<li class="chapter" data-level="8.1" data-path="ggplot-more.html"><a href="ggplot-more.html#references"><i class="fa fa-check"></i><b>8.1</b> References</a></li>
<li class="chapter" data-level="8.2" data-path="ggplot-more.html"><a href="ggplot-more.html#learning-goals-for-this-chapter"><i class="fa fa-check"></i><b>8.2</b> Learning goals for this chapter</a></li>
<li class="chapter" data-level="8.3" data-path="ggplot-more.html"><a href="ggplot-more.html#set-up-your-notebook"><i class="fa fa-check"></i><b>8.3</b> Set up your notebook</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="ggplot-more.html"><a href="ggplot-more.html#lets-get-the-data"><i class="fa fa-check"></i><b>8.3.1</b> Let’s get the data</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="ggplot-more.html"><a href="ggplot-more.html#wrangle-the-data"><i class="fa fa-check"></i><b>8.4</b> Wrangle the data</a></li>
<li class="chapter" data-level="8.5" data-path="ggplot-more.html"><a href="ggplot-more.html#make-a-line-chart-of-the-texas-data"><i class="fa fa-check"></i><b>8.5</b> Make a line chart of the Texas data</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="ggplot-more.html"><a href="ggplot-more.html#plot-the-chart"><i class="fa fa-check"></i><b>8.5.1</b> Plot the chart</a></li>
<li class="chapter" data-level="8.5.2" data-path="ggplot-more.html"><a href="ggplot-more.html#cleaning-up"><i class="fa fa-check"></i><b>8.5.2</b> Cleaning Up</a></li>
<li class="chapter" data-level="8.5.3" data-path="ggplot-more.html"><a href="ggplot-more.html#saving-plots-as-an-object"><i class="fa fa-check"></i><b>8.5.3</b> Saving plots as an object</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="ggplot-more.html"><a href="ggplot-more.html#themes"><i class="fa fa-check"></i><b>8.6</b> Themes</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="ggplot-more.html"><a href="ggplot-more.html#more-with-ggthemes"><i class="fa fa-check"></i><b>8.6.1</b> More with ggthemes</a></li>
<li class="chapter" data-level="8.6.2" data-path="ggplot-more.html"><a href="ggplot-more.html#there-is-more-to-themes"><i class="fa fa-check"></i><b>8.6.2</b> There is more to themes</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="ggplot-more.html"><a href="ggplot-more.html#adding-more-information"><i class="fa fa-check"></i><b>8.7</b> Adding more information</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="ggplot-more.html"><a href="ggplot-more.html#prepare-the-data-1"><i class="fa fa-check"></i><b>8.7.1</b> Prepare the data</a></li>
<li class="chapter" data-level="8.7.2" data-path="ggplot-more.html"><a href="ggplot-more.html#plot-multiple-line-chart"><i class="fa fa-check"></i><b>8.7.2</b> Plot multiple line chart</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="ggplot-more.html"><a href="ggplot-more.html#on-your-own-line-chart"><i class="fa fa-check"></i><b>8.8</b> On your own: Line chart</a></li>
<li class="chapter" data-level="8.9" data-path="ggplot-more.html"><a href="ggplot-more.html#tour-of-some-other-adjustments"><i class="fa fa-check"></i><b>8.9</b> Tour of some other adjustments</a>
<ul>
<li class="chapter" data-level="8.9.1" data-path="ggplot-more.html"><a href="ggplot-more.html#line-width"><i class="fa fa-check"></i><b>8.9.1</b> Line width</a></li>
<li class="chapter" data-level="8.9.2" data-path="ggplot-more.html"><a href="ggplot-more.html#line-type"><i class="fa fa-check"></i><b>8.9.2</b> Line type</a></li>
<li class="chapter" data-level="8.9.3" data-path="ggplot-more.html"><a href="ggplot-more.html#adjust-axis"><i class="fa fa-check"></i><b>8.9.3</b> Adjust axis</a></li>
</ul></li>
<li class="chapter" data-level="8.10" data-path="ggplot-more.html"><a href="ggplot-more.html#facets"><i class="fa fa-check"></i><b>8.10</b> Facets</a>
<ul>
<li class="chapter" data-level="8.10.1" data-path="ggplot-more.html"><a href="ggplot-more.html#facet-wrap"><i class="fa fa-check"></i><b>8.10.1</b> Facet wrap</a></li>
<li class="chapter" data-level="8.10.2" data-path="ggplot-more.html"><a href="ggplot-more.html#facet-grids"><i class="fa fa-check"></i><b>8.10.2</b> Facet grids</a></li>
</ul></li>
<li class="chapter" data-level="8.11" data-path="ggplot-more.html"><a href="ggplot-more.html#on-your-own-facet-wrap"><i class="fa fa-check"></i><b>8.11</b> On your own: Facet wrap</a></li>
<li class="chapter" data-level="8.12" data-path="ggplot-more.html"><a href="ggplot-more.html#saving-plots"><i class="fa fa-check"></i><b>8.12</b> Saving plots</a></li>
<li class="chapter" data-level="8.13" data-path="ggplot-more.html"><a href="ggplot-more.html#interactive-plots"><i class="fa fa-check"></i><b>8.13</b> Interactive plots</a></li>
<li class="chapter" data-level="8.14" data-path="ggplot-more.html"><a href="ggplot-more.html#what-we-learned"><i class="fa fa-check"></i><b>8.14</b> What we learned</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="tidy-data.html"><a href="tidy-data.html"><i class="fa fa-check"></i><b>9</b> Tidy data</a>
<ul>
<li class="chapter" data-level="9.1" data-path="tidy-data.html"><a href="tidy-data.html#goals-for-this-section-1"><i class="fa fa-check"></i><b>9.1</b> Goals for this section</a></li>
<li class="chapter" data-level="9.2" data-path="tidy-data.html"><a href="tidy-data.html#the-questions-well-answer-1"><i class="fa fa-check"></i><b>9.2</b> The questions we’ll answer</a></li>
<li class="chapter" data-level="9.3" data-path="tidy-data.html"><a href="tidy-data.html#what-is-tidy-data"><i class="fa fa-check"></i><b>9.3</b> What is tidy data</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="tidy-data.html"><a href="tidy-data.html#wide-vs-long-data"><i class="fa fa-check"></i><b>9.3.1</b> Wide vs long data</a></li>
<li class="chapter" data-level="9.3.2" data-path="tidy-data.html"><a href="tidy-data.html#why-we-might-want-different-shaped-data"><i class="fa fa-check"></i><b>9.3.2</b> Why we might want different shaped data</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="tidy-data.html"><a href="tidy-data.html#prepare-our-candy-project"><i class="fa fa-check"></i><b>9.4</b> Prepare our candy project</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="tidy-data.html"><a href="tidy-data.html#get-the-data"><i class="fa fa-check"></i><b>9.4.1</b> Get the data</a></li>
<li class="chapter" data-level="9.4.2" data-path="tidy-data.html"><a href="tidy-data.html#drop-unneeded-columns"><i class="fa fa-check"></i><b>9.4.2</b> Drop unneeded columns</a></li>
<li class="chapter" data-level="9.4.3" data-path="tidy-data.html"><a href="tidy-data.html#peek-at-the-wide-table"><i class="fa fa-check"></i><b>9.4.3</b> Peek at the wide table</a></li>
<li class="chapter" data-level="9.4.4" data-path="tidy-data.html"><a href="tidy-data.html#where-are-we-going-with-this-data"><i class="fa fa-check"></i><b>9.4.4</b> Where are we going with this data</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="tidy-data.html"><a href="tidy-data.html#the-tidyr-verbs"><i class="fa fa-check"></i><b>9.5</b> The tidyr verbs</a></li>
<li class="chapter" data-level="9.6" data-path="tidy-data.html"><a href="tidy-data.html#pivot-longer"><i class="fa fa-check"></i><b>9.6</b> Pivot longer</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="tidy-data.html"><a href="tidy-data.html#pivot-our-candy-data-longer"><i class="fa fa-check"></i><b>9.6.1</b> Pivot our candy data longer</a></li>
<li class="chapter" data-level="9.6.2" data-path="tidy-data.html"><a href="tidy-data.html#get-average-candies-per-color"><i class="fa fa-check"></i><b>9.6.2</b> Get average candies per color</a></li>
<li class="chapter" data-level="9.6.3" data-path="tidy-data.html"><a href="tidy-data.html#round-the-averages"><i class="fa fa-check"></i><b>9.6.3</b> Round the averages</a></li>
<li class="chapter" data-level="9.6.4" data-path="tidy-data.html"><a href="tidy-data.html#on-your-own-plot-the-averages"><i class="fa fa-check"></i><b>9.6.4</b> On your own: Plot the averages</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="tidy-data.html"><a href="tidy-data.html#introducing-datawrapper"><i class="fa fa-check"></i><b>9.7</b> Introducing Datawrapper</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="tidy-data.html"><a href="tidy-data.html#review-how-to-make-a-bar-chart"><i class="fa fa-check"></i><b>9.7.1</b> Review how to make a bar chart</a></li>
<li class="chapter" data-level="9.7.2" data-path="tidy-data.html"><a href="tidy-data.html#start-a-chart"><i class="fa fa-check"></i><b>9.7.2</b> Start a chart</a></li>
<li class="chapter" data-level="9.7.3" data-path="tidy-data.html"><a href="tidy-data.html#get-your-candies-data"><i class="fa fa-check"></i><b>9.7.3</b> Get your candies data</a></li>
<li class="chapter" data-level="9.7.4" data-path="tidy-data.html"><a href="tidy-data.html#build-the-datawrapper-graphic"><i class="fa fa-check"></i><b>9.7.4</b> Build the datawrapper graphic</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="tidy-data.html"><a href="tidy-data.html#pivot-wider"><i class="fa fa-check"></i><b>9.8</b> Pivot wider</a>
<ul>
<li class="chapter" data-level="9.8.1" data-path="tidy-data.html"><a href="tidy-data.html#pivot-wider-on-your-own"><i class="fa fa-check"></i><b>9.8.1</b> Pivot wider on your own</a></li>
</ul></li>
<li class="chapter" data-level="9.9" data-path="tidy-data.html"><a href="tidy-data.html#bonus-questions"><i class="fa fa-check"></i><b>9.9</b> Bonus questions</a>
<ul>
<li class="chapter" data-level="9.9.1" data-path="tidy-data.html"><a href="tidy-data.html#mostleast-candies"><i class="fa fa-check"></i><b>9.9.1</b> Most/least candies</a></li>
<li class="chapter" data-level="9.9.2" data-path="tidy-data.html"><a href="tidy-data.html#average-total-candies-in-a-bag"><i class="fa fa-check"></i><b>9.9.2</b> Average total candies in a bag</a></li>
</ul></li>
<li class="chapter" data-level="9.10" data-path="tidy-data.html"><a href="tidy-data.html#turn-in-your-work"><i class="fa fa-check"></i><b>9.10</b> Turn in your work</a></li>
<li class="chapter" data-level="9.11" data-path="tidy-data.html"><a href="tidy-data.html#what-we-learned-1"><i class="fa fa-check"></i><b>9.11</b> What we learned</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="plot-aac.html"><a href="plot-aac.html"><i class="fa fa-check"></i><b>10</b> Plotting for answers</a>
<ul>
<li class="chapter" data-level="10.1" data-path="plot-aac.html"><a href="plot-aac.html#goals-of-this-lesson-1"><i class="fa fa-check"></i><b>10.1</b> Goals of this lesson</a></li>
<li class="chapter" data-level="10.2" data-path="plot-aac.html"><a href="plot-aac.html#questions-we-will-answer"><i class="fa fa-check"></i><b>10.2</b> Questions we will answer</a></li>
<li class="chapter" data-level="10.3" data-path="plot-aac.html"><a href="plot-aac.html#create-your-project-1"><i class="fa fa-check"></i><b>10.3</b> Create your project</a></li>
<li class="chapter" data-level="10.4" data-path="plot-aac.html"><a href="plot-aac.html#download-the-data-1"><i class="fa fa-check"></i><b>10.4</b> Download the data</a></li>
<li class="chapter" data-level="10.5" data-path="plot-aac.html"><a href="plot-aac.html#import-your-data"><i class="fa fa-check"></i><b>10.5</b> Import your data</a></li>
<li class="chapter" data-level="10.6" data-path="plot-aac.html"><a href="plot-aac.html#fix-the-dates"><i class="fa fa-check"></i><b>10.6</b> Fix the dates</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="plot-aac.html"><a href="plot-aac.html#edit-to-convert-to-a-real-date"><i class="fa fa-check"></i><b>10.6.1</b> Edit to convert to a real date</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="plot-aac.html"><a href="plot-aac.html#parse-the-date-into-helpful-variables"><i class="fa fa-check"></i><b>10.7</b> Parse the date into helpful variables</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="plot-aac.html"><a href="plot-aac.html#extract-the-year"><i class="fa fa-check"></i><b>10.7.1</b> Extract the year</a></li>
<li class="chapter" data-level="10.7.2" data-path="plot-aac.html"><a href="plot-aac.html#extract-the-month-name"><i class="fa fa-check"></i><b>10.7.2</b> Extract the month name</a></li>
<li class="chapter" data-level="10.7.3" data-path="plot-aac.html"><a href="plot-aac.html#extract-yyyy-mm-format"><i class="fa fa-check"></i><b>10.7.3</b> Extract YYYY-MM format</a></li>
<li class="chapter" data-level="10.7.4" data-path="plot-aac.html"><a href="plot-aac.html#reorder-and-drop-columns"><i class="fa fa-check"></i><b>10.7.4</b> Reorder and drop columns</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="plot-aac.html"><a href="plot-aac.html#on-your-own-filter-dates"><i class="fa fa-check"></i><b>10.8</b> On your own: Filter dates</a></li>
<li class="chapter" data-level="10.9" data-path="plot-aac.html"><a href="plot-aac.html#on-your-own-export-your-data"><i class="fa fa-check"></i><b>10.9</b> On your own: Export your data</a></li>
<li class="chapter" data-level="10.10" data-path="plot-aac.html"><a href="plot-aac.html#set-up-your-analysis-notebook"><i class="fa fa-check"></i><b>10.10</b> Set up your analysis notebook</a></li>
<li class="chapter" data-level="10.11" data-path="plot-aac.html"><a href="plot-aac.html#on-your-own-import-your-cleaned-data"><i class="fa fa-check"></i><b>10.11</b> On your own: Import your cleaned data</a></li>
<li class="chapter" data-level="10.12" data-path="plot-aac.html"><a href="plot-aac.html#question-1-intakes-by-year"><i class="fa fa-check"></i><b>10.12</b> Question 1: Intakes by year</a>
<ul>
<li class="chapter" data-level="10.12.1" data-path="plot-aac.html"><a href="plot-aac.html#on-your-own-column-chart-of-intakes-by-year"><i class="fa fa-check"></i><b>10.12.1</b> On your own: Column chart of intakes by year</a></li>
<li class="chapter" data-level="10.12.2" data-path="plot-aac.html"><a href="plot-aac.html#getting-commas-on-numbers"><i class="fa fa-check"></i><b>10.12.2</b> Getting commas on numbers</a></li>
</ul></li>
<li class="chapter" data-level="10.13" data-path="plot-aac.html"><a href="plot-aac.html#question-2-intakes-by-month"><i class="fa fa-check"></i><b>10.13</b> Question 2: Intakes by month</a>
<ul>
<li class="chapter" data-level="10.13.1" data-path="plot-aac.html"><a href="plot-aac.html#intakes-by-month-as-a-line"><i class="fa fa-check"></i><b>10.13.1</b> Intakes by month as a line</a></li>
<li class="chapter" data-level="10.13.2" data-path="plot-aac.html"><a href="plot-aac.html#make-the-chart-wider"><i class="fa fa-check"></i><b>10.13.2</b> Make the chart wider</a></li>
<li class="chapter" data-level="10.13.3" data-path="plot-aac.html"><a href="plot-aac.html#so-what-of-this"><i class="fa fa-check"></i><b>10.13.3</b> So, what of this</a></li>
</ul></li>
<li class="chapter" data-level="10.14" data-path="plot-aac.html"><a href="plot-aac.html#question-3-intakes-by-month-split-by-year"><i class="fa fa-check"></i><b>10.14</b> Question 3: Intakes by month, split by year</a>
<ul>
<li class="chapter" data-level="10.14.1" data-path="plot-aac.html"><a href="plot-aac.html#prepare-the-data-with-mo-and-yr"><i class="fa fa-check"></i><b>10.14.1</b> Prepare the data with mo and yr</a></li>
<li class="chapter" data-level="10.14.2" data-path="plot-aac.html"><a href="plot-aac.html#plot-by-month-split-by-year"><i class="fa fa-check"></i><b>10.14.2</b> Plot by month, split by year</a></li>
<li class="chapter" data-level="10.14.3" data-path="plot-aac.html"><a href="plot-aac.html#adjust-the-yr-value-to-a-character"><i class="fa fa-check"></i><b>10.14.3</b> Adjust the yr value to a character</a></li>
<li class="chapter" data-level="10.14.4" data-path="plot-aac.html"><a href="plot-aac.html#clean-up-your-intakes-by-month-split-by-year-chart"><i class="fa fa-check"></i><b>10.14.4</b> Clean up your intakes by month, split by year chart</a></li>
</ul></li>
<li class="chapter" data-level="10.15" data-path="plot-aac.html"><a href="plot-aac.html#question-4-animal-types-by-month"><i class="fa fa-check"></i><b>10.15</b> Question 4: Animal types by month</a>
<ul>
<li class="chapter" data-level="10.15.1" data-path="plot-aac.html"><a href="plot-aac.html#recode-animal-types"><i class="fa fa-check"></i><b>10.15.1</b> Recode animal types</a></li>
<li class="chapter" data-level="10.15.2" data-path="plot-aac.html"><a href="plot-aac.html#on-your-own-count-animal-types-by-month"><i class="fa fa-check"></i><b>10.15.2</b> On your own: Count animal types by month</a></li>
<li class="chapter" data-level="10.15.3" data-path="plot-aac.html"><a href="plot-aac.html#on-your-own-plot-animal-types-by-month"><i class="fa fa-check"></i><b>10.15.3</b> On your own: Plot animal types by month</a></li>
</ul></li>
<li class="chapter" data-level="10.16" data-path="plot-aac.html"><a href="plot-aac.html#what-we-learned-2"><i class="fa fa-check"></i><b>10.16</b> What we learned</a></li>
<li class="chapter" data-level="10.17" data-path="plot-aac.html"><a href="plot-aac.html#turn-in-your-work-1"><i class="fa fa-check"></i><b>10.17</b> Turn in your work</a></li>
<li class="chapter" data-level="10.18" data-path="plot-aac.html"><a href="plot-aac.html#whats-next-1"><i class="fa fa-check"></i><b>10.18</b> What’s next</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="census-intro.html"><a href="census-intro.html"><i class="fa fa-check"></i><b>11</b> Census introduction</a>
<ul>
<li class="chapter" data-level="11.1" data-path="census-intro.html"><a href="census-intro.html#goals-of-this-chapter"><i class="fa fa-check"></i><b>11.1</b> Goals of this chapter</a></li>
<li class="chapter" data-level="11.2" data-path="census-intro.html"><a href="census-intro.html#start-a-tidycensus-project"><i class="fa fa-check"></i><b>11.2</b> Start a tidycensus project</a></li>
<li class="chapter" data-level="11.3" data-path="census-intro.html"><a href="census-intro.html#census-data-portal-and-api"><i class="fa fa-check"></i><b>11.3</b> Census data portal and API</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="census-intro.html"><a href="census-intro.html#request-a-key"><i class="fa fa-check"></i><b>11.3.1</b> Request a key</a></li>
<li class="chapter" data-level="11.3.2" data-path="census-intro.html"><a href="census-intro.html#install-a-key"><i class="fa fa-check"></i><b>11.3.2</b> Install a key</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="census-intro.html"><a href="census-intro.html#about-the-tidycensus-package"><i class="fa fa-check"></i><b>11.4</b> About the tidycensus package</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="census-intro.html"><a href="census-intro.html#finding-the-data-you-want"><i class="fa fa-check"></i><b>11.4.1</b> Finding the data you want</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="census-intro.html"><a href="census-intro.html#broadband-access-by-county-in-texas"><i class="fa fa-check"></i><b>11.5</b> Broadband access by county in Texas</a></li>
<li class="chapter" data-level="11.6" data-path="census-intro.html"><a href="census-intro.html#using-the-tidycensus-load_variable-function"><i class="fa fa-check"></i><b>11.6</b> Using the tidycensus load_variable() function</a></li>
<li class="chapter" data-level="11.7" data-path="census-intro.html"><a href="census-intro.html#use-tidycensus-to-fetch-our-data"><i class="fa fa-check"></i><b>11.7</b> Use tidycensus to fetch our data</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="census-intro.html"><a href="census-intro.html#get-broadband-rates-by-county-in-texas"><i class="fa fa-check"></i><b>11.7.1</b> Get broadband rates by county in Texas</a></li>
<li class="chapter" data-level="11.7.2" data-path="census-intro.html"><a href="census-intro.html#on-your-own-arrange-to-get-lowesthighest-values"><i class="fa fa-check"></i><b>11.7.2</b> On your own: Arrange to get lowest/highest values</a></li>
<li class="chapter" data-level="11.7.3" data-path="census-intro.html"><a href="census-intro.html#what-you-have-here"><i class="fa fa-check"></i><b>11.7.3</b> What you have here</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="census-intro.html"><a href="census-intro.html#map-broadband-access-by-counties-in-texas"><i class="fa fa-check"></i><b>11.8</b> Map broadband access by counties in Texas</a>
<ul>
<li class="chapter" data-level="11.8.1" data-path="census-intro.html"><a href="census-intro.html#plot-the-broadband-map"><i class="fa fa-check"></i><b>11.8.1</b> Plot the broadband map</a></li>
<li class="chapter" data-level="11.8.2" data-path="census-intro.html"><a href="census-intro.html#you-did-it"><i class="fa fa-check"></i><b>11.8.2</b> You did it!</a></li>
</ul></li>
<li class="chapter" data-level="11.9" data-path="census-intro.html"><a href="census-intro.html#keep-this-project"><i class="fa fa-check"></i><b>11.9</b> Keep this project</a></li>
<li class="chapter" data-level="11.10" data-path="census-intro.html"><a href="census-intro.html#what-weve-learned-1"><i class="fa fa-check"></i><b>11.10</b> What we’ve learned</a></li>
<li class="chapter" data-level="11.11" data-path="census-intro.html"><a href="census-intro.html#other-useful-census-related-packages"><i class="fa fa-check"></i><b>11.11</b> Other useful census-related packages</a>
<ul>
<li class="chapter" data-level="11.11.1" data-path="census-intro.html"><a href="census-intro.html#the-censusapi-package"><i class="fa fa-check"></i><b>11.11.1</b> The censusapi package</a></li>
</ul></li>
<li class="chapter" data-level="11.12" data-path="census-intro.html"><a href="census-intro.html#interactive-maps-with-leaflet"><i class="fa fa-check"></i><b>11.12</b> Interactive maps with leaflet</a></li>
<li class="chapter" data-level="11.13" data-path="census-intro.html"><a href="census-intro.html#more-resources-and-examples"><i class="fa fa-check"></i><b>11.13</b> More resources and examples</a></li>
<li class="chapter" data-level="11.14" data-path="census-intro.html"><a href="census-intro.html#using-the-data-portal-to-download-data"><i class="fa fa-check"></i><b>11.14</b> Using the data portal to download data</a>
<ul>
<li class="chapter" data-level="11.14.1" data-path="census-intro.html"><a href="census-intro.html#importing-downloaded-data"><i class="fa fa-check"></i><b>11.14.1</b> Importing downloaded data</a></li>
<li class="chapter" data-level="11.14.2" data-path="census-intro.html"><a href="census-intro.html#fields-made-to-join-with-other-data"><i class="fa fa-check"></i><b>11.14.2</b> Fields made to join with other data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="census-more.html"><a href="census-more.html"><i class="fa fa-check"></i><b>12</b> Joining census data</a>
<ul>
<li class="chapter" data-level="12.1" data-path="census-more.html"><a href="census-more.html#goals-of-the-chapter"><i class="fa fa-check"></i><b>12.1</b> Goals of the chapter</a></li>
<li class="chapter" data-level="12.2" data-path="census-more.html"><a href="census-more.html#questions-well-answer"><i class="fa fa-check"></i><b>12.2</b> Questions we’ll answer</a></li>
<li class="chapter" data-level="12.3" data-path="census-more.html"><a href="census-more.html#set-up-your-notebook-1"><i class="fa fa-check"></i><b>12.3</b> Set up your notebook</a></li>
<li class="chapter" data-level="12.4" data-path="census-more.html"><a href="census-more.html#new-york-times-covid-data"><i class="fa fa-check"></i><b>12.4</b> New York Times COVID data</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="census-more.html"><a href="census-more.html#on-your-own-import-the-nyt-data"><i class="fa fa-check"></i><b>12.4.1</b> On your own: Import the NYT data</a></li>
<li class="chapter" data-level="12.4.2" data-path="census-more.html"><a href="census-more.html#slice-the-most-recent-data"><i class="fa fa-check"></i><b>12.4.2</b> Slice the most recent data</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="census-more.html"><a href="census-more.html#get-county-populations-using-tidycensus"><i class="fa fa-check"></i><b>12.5</b> Get county populations using tidycensus</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="census-more.html"><a href="census-more.html#find-the-data-on-data.census.gov"><i class="fa fa-check"></i><b>12.5.1</b> Find the data on data.census.gov</a></li>
<li class="chapter" data-level="12.5.2" data-path="census-more.html"><a href="census-more.html#find-the-variable-name"><i class="fa fa-check"></i><b>12.5.2</b> Find the variable name</a></li>
<li class="chapter" data-level="12.5.3" data-path="census-more.html"><a href="census-more.html#fetch-the-population-data"><i class="fa fa-check"></i><b>12.5.3</b> Fetch the population data</a></li>
<li class="chapter" data-level="12.5.4" data-path="census-more.html"><a href="census-more.html#get-data-for-texas-counties"><i class="fa fa-check"></i><b>12.5.4</b> Get data for Texas counties</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="census-more.html"><a href="census-more.html#about-joins"><i class="fa fa-check"></i><b>12.6</b> About joins</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="census-more.html"><a href="census-more.html#join-our-data-together"><i class="fa fa-check"></i><b>12.6.1</b> Join our data together</a></li>
<li class="chapter" data-level="12.6.2" data-path="census-more.html"><a href="census-more.html#clean-up-column-names-etc."><i class="fa fa-check"></i><b>12.6.2</b> Clean up column names, etc.</a></li>
</ul></li>
<li class="chapter" data-level="12.7" data-path="census-more.html"><a href="census-more.html#create-our-rate-columns"><i class="fa fa-check"></i><b>12.7</b> Create our rate columns</a>
<ul>
<li class="chapter" data-level="12.7.1" data-path="census-more.html"><a href="census-more.html#on-your-own-get-a-deaths-rate-per-1000"><i class="fa fa-check"></i><b>12.7.1</b> On your own: Get a deaths rate per 1,000</a></li>
<li class="chapter" data-level="12.7.2" data-path="census-more.html"><a href="census-more.html#on-your-own-find-counties-with-highest-rates"><i class="fa fa-check"></i><b>12.7.2</b> On your own: Find counties with highest rates</a></li>
</ul></li>
<li class="chapter" data-level="12.8" data-path="census-more.html"><a href="census-more.html#mapping-the-rates-for-texas-counties"><i class="fa fa-check"></i><b>12.8</b> Mapping the rates for Texas counties</a></li>
<li class="chapter" data-level="12.9" data-path="census-more.html"><a href="census-more.html#on-your-own-map-the-deaths-per-1000"><i class="fa fa-check"></i><b>12.9</b> On your own: Map the deaths per 1,000</a></li>
<li class="chapter" data-level="12.10" data-path="census-more.html"><a href="census-more.html#what-weve-learned-2"><i class="fa fa-check"></i><b>12.10</b> What we’ve learned</a></li>
<li class="chapter" data-level="12.11" data-path="census-more.html"><a href="census-more.html#turn-in-your-work-2"><i class="fa fa-check"></i><b>12.11</b> Turn in your work</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="mastery.html"><a href="mastery.html"><i class="fa fa-check"></i><b>13</b> Mastery - Mixed Beverages</a>
<ul>
<li class="chapter" data-level="13.1" data-path="mastery.html"><a href="mastery.html#the-assignment-outline"><i class="fa fa-check"></i><b>13.1</b> The assignment outline</a></li>
<li class="chapter" data-level="13.2" data-path="mastery.html"><a href="mastery.html#about-the-interviews"><i class="fa fa-check"></i><b>13.2</b> About the interviews</a></li>
<li class="chapter" data-level="13.3" data-path="mastery.html"><a href="mastery.html#about-the-data-1"><i class="fa fa-check"></i><b>13.3</b> About the data</a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="mastery.html"><a href="mastery.html#important-things-to-know"><i class="fa fa-check"></i><b>13.3.1</b> Important things to know</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="mastery.html"><a href="mastery.html#story-ideas"><i class="fa fa-check"></i><b>13.4</b> Story ideas</a></li>
<li class="chapter" data-level="13.5" data-path="mastery.html"><a href="mastery.html#downloading-and-cleaning-the-data"><i class="fa fa-check"></i><b>13.5</b> Downloading and cleaning the data</a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="mastery.html"><a href="mastery.html#set-up-the-download-url"><i class="fa fa-check"></i><b>13.5.1</b> Set up the download url</a></li>
<li class="chapter" data-level="13.5.2" data-path="mastery.html"><a href="mastery.html#download-the-data-2"><i class="fa fa-check"></i><b>13.5.2</b> Download the data</a></li>
<li class="chapter" data-level="13.5.3" data-path="mastery.html"><a href="mastery.html#fix-some-values"><i class="fa fa-check"></i><b>13.5.3</b> Fix some values</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="mastery.html"><a href="mastery.html#export-your-data"><i class="fa fa-check"></i><b>13.6</b> Export your data</a></li>
<li class="chapter" data-level="13.7" data-path="mastery.html"><a href="mastery.html#how-to-tackle-the-analysis"><i class="fa fa-check"></i><b>13.7</b> How to tackle the analysis</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="how-to-interview-a-new-dataset.html"><a href="how-to-interview-a-new-dataset.html"><i class="fa fa-check"></i><b>14</b> How to interview a new dataset</a>
<ul>
<li class="chapter" data-level="14.1" data-path="how-to-interview-a-new-dataset.html"><a href="how-to-interview-a-new-dataset.html#start-by-listing-questions"><i class="fa fa-check"></i><b>14.1</b> Start by listing questions</a></li>
<li class="chapter" data-level="14.2" data-path="how-to-interview-a-new-dataset.html"><a href="how-to-interview-a-new-dataset.html#understand-your-data"><i class="fa fa-check"></i><b>14.2</b> Understand your data</a></li>
<li class="chapter" data-level="14.3" data-path="how-to-interview-a-new-dataset.html"><a href="how-to-interview-a-new-dataset.html#pay-attention-to-the-shape-of-your-data"><i class="fa fa-check"></i><b>14.3</b> Pay attention to the shape of your data</a></li>
<li class="chapter" data-level="14.4" data-path="how-to-interview-a-new-dataset.html"><a href="how-to-interview-a-new-dataset.html#counting-and-aggregation"><i class="fa fa-check"></i><b>14.4</b> Counting and aggregation</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="how-to-interview-a-new-dataset.html"><a href="how-to-interview-a-new-dataset.html#counting-rows-based-on-a-column"><i class="fa fa-check"></i><b>14.4.1</b> Counting rows based on a column</a></li>
<li class="chapter" data-level="14.4.2" data-path="how-to-interview-a-new-dataset.html"><a href="how-to-interview-a-new-dataset.html#sum-mean-and-other-aggregations"><i class="fa fa-check"></i><b>14.4.2</b> Sum, mean and other aggregations</a></li>
<li class="chapter" data-level="14.4.3" data-path="how-to-interview-a-new-dataset.html"><a href="how-to-interview-a-new-dataset.html#creating-columns-to-show-difference"><i class="fa fa-check"></i><b>14.4.3</b> Creating columns to show difference</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="how-to-interview-a-new-dataset.html"><a href="how-to-interview-a-new-dataset.html#cleaning-up-categorical-data"><i class="fa fa-check"></i><b>14.5</b> Cleaning up categorical data</a></li>
<li class="chapter" data-level="14.6" data-path="how-to-interview-a-new-dataset.html"><a href="how-to-interview-a-new-dataset.html#time-as-a-variable"><i class="fa fa-check"></i><b>14.6</b> Time as a variable</a></li>
<li class="chapter" data-level="14.7" data-path="how-to-interview-a-new-dataset.html"><a href="how-to-interview-a-new-dataset.html#explore-the-distributions-in-your-data"><i class="fa fa-check"></i><b>14.7</b> Explore the distributions in your data</a>
<ul>
<li class="chapter" data-level="14.7.1" data-path="how-to-interview-a-new-dataset.html"><a href="how-to-interview-a-new-dataset.html#more-on-histograms"><i class="fa fa-check"></i><b>14.7.1</b> More on histograms</a></li>
</ul></li>
<li class="chapter" data-level="14.8" data-path="how-to-interview-a-new-dataset.html"><a href="how-to-interview-a-new-dataset.html#same-ideas-using-spreadsheets"><i class="fa fa-check"></i><b>14.8</b> Same ideas using spreadsheets</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="verbs.html"><a href="verbs.html"><i class="fa fa-check"></i><b>15</b> Verbs</a>
<ul>
<li class="chapter" data-level="15.1" data-path="verbs.html"><a href="verbs.html#importexport"><i class="fa fa-check"></i><b>15.1</b> Import/Export</a></li>
<li class="chapter" data-level="15.2" data-path="verbs.html"><a href="verbs.html#data-manipulation"><i class="fa fa-check"></i><b>15.2</b> Data manipulation</a></li>
<li class="chapter" data-level="15.3" data-path="verbs.html"><a href="verbs.html#aggregation"><i class="fa fa-check"></i><b>15.3</b> Aggregation</a></li>
<li class="chapter" data-level="15.4" data-path="verbs.html"><a href="verbs.html#math"><i class="fa fa-check"></i><b>15.4</b> Math</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Reporting with Data in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="census-more" class="section level1" number="12">
<h1><span class="header-section-number">Chapter 12</span> Joining census data</h1>
<p>In the last chapter we introduced U.S. Census Bureau’s data.census.gov and used it to guide us in using their API with the tidycensus package. We used tidycensus to pull data and we mapped it.</p>
<p>In this chapter we’ll use tidycensus again, but we’ll use it to pull data that compliments other data (COVID cases), joining two data sets together to get a per-population rate.</p>
<div id="goals-of-the-chapter" class="section level2" number="12.1">
<h2><span class="header-section-number">12.1</span> Goals of the chapter</h2>
<ul>
<li>Introduce the New York Times’ collection of COVID-related data.</li>
<li>Along the way we’ll learn how to use <code>slice()</code> to get a subset of data.</li>
<li>Use tidycensus to pull 2020 Decennial Census population data.</li>
<li>Introduce the concept of “joining” data on a common key variable.</li>
<li>Create COVID cases and death rates using the combination of these two data sets.</li>
<li>Map the results.</li>
</ul>
</div>
<div id="questions-well-answer" class="section level2" number="12.2">
<h2><span class="header-section-number">12.2</span> Questions we’ll answer</h2>
<ul>
<li>Which counties in Texas have the highest/lowest cases-per-population rates for COVID.</li>
<li>Which counties have the highest/lowest deaths-per-population rates for COVID.</li>
</ul>
</div>
<div id="set-up-your-notebook-1" class="section level2" number="12.3">
<h2><span class="header-section-number">12.3</span> Set up your notebook</h2>
<p>We’re going to use the same project from the last chapter, <code>yourname-census</code>, but start a new notebook.</p>
<ol style="list-style-type: decimal">
<li>Open your census project</li>
<li>Start a new R Notebook and name it <code>covid-rates.Rmd</code>.</li>
<li>Create a setup chunk with the following libraries</li>
</ol>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="census-more.html#cb264-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb264-2"><a href="census-more.html#cb264-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidycensus)</span>
<span id="cb264-3"><a href="census-more.html#cb264-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb264-4"><a href="census-more.html#cb264-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code></pre></div>
</div>
<div id="new-york-times-covid-data" class="section level2" number="12.4">
<h2><span class="header-section-number">12.4</span> New York Times COVID data</h2>
<p>The New York Times has been collecting COVID-19 case data since the beginning of the pandemic, and they have been <a href="https://github.com/nytimes/covid-19-data">publishing it on Github</a> for others to use. One of files they publish is cumulative case and death counts by county throughout the United States.</p>
<p>We will use this file, along with 2020 U.S. Census Bureau population data, to create cases-per-population and deaths-per-population rates for each county in Texas. Because counties have varying populations, we need a rate like this to compare them on an equal basis.</p>
<div id="on-your-own-import-the-nyt-data" class="section level3" number="12.4.1">
<h3><span class="header-section-number">12.4.1</span> On your own: Import the NYT data</h3>
<p>We won’t bother to save the covid data to your hard drive … we’ll just import directly from the URL.</p>
<ol style="list-style-type: decimal">
<li>Create a new section and note you are download the NYT covid data</li>
<li>Start an R chunk and use <code>read_csv</code> to import the data from this url: <code>https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv</code> and save it into an R object called <code>covid</code>. (This is similar to how you imported the Skittles data.)</li>
<li>Print your new <code>covid</code> tibble to the screen. You can pipe it into <code>head()</code> to show just the top of it so we can see what it is.</li>
</ol>
<p>There is more than 1.8 million rows of this data, so it might take a couple of seconds.</p>
<p>Let’s tour the data real quick:</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="census-more.html#cb265-1" aria-hidden="true" tabindex="-1"></a>covid <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 x 6
##   date       county    state      fips  cases deaths
##   &lt;date&gt;     &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1 2020-01-21 Snohomish Washington 53061     1      0
## 2 2020-01-22 Snohomish Washington 53061     1      0
## 3 2020-01-23 Snohomish Washington 53061     1      0
## 4 2020-01-24 Cook      Illinois   17031     1      0
## 5 2020-01-24 Snohomish Washington 53061     1      0
## 6 2020-01-25 Orange    California 06059     1      0</code></pre>
<p>This is the same data that powers the NYT’s <a href="https://www.nytimes.com/interactive/2021/us/covid-cases.html">Coronavirus tracker</a>. They have a team of reporters that update the data every day.</p>
<p>There is a new row of data for each county, each day. The data includes the date of the update along with the county, state, a FIPS code (a special geographic designation) as well as the total cases and deaths from COVID up to that date.</p>
<p>Since the data is cumulative, we only want the most recent date for each county.</p>
</div>
<div id="slice-the-most-recent-data" class="section level3" number="12.4.2">
<h3><span class="header-section-number">12.4.2</span> Slice the most recent data</h3>
<p>Most of the concept in the next chunk you know already, but <a href="https://dplyr.tidyverse.org/reference/slice.html"><code>slice()</code></a> is new so I’ll do this all and then explain it.</p>
<ol style="list-style-type: decimal">
<li>Create a new section that notes you are getting the most recent Texas data by county.</li>
<li>Add the code chunk below (one line at a time!) and run it.</li>
</ol>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="census-more.html#cb267-1" aria-hidden="true" tabindex="-1"></a>tx_covid <span class="ot">&lt;-</span> covid <span class="sc">%&gt;%</span> </span>
<span id="cb267-2"><a href="census-more.html#cb267-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(state <span class="sc">==</span> <span class="st">&quot;Texas&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb267-3"><a href="census-more.html#cb267-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(county) <span class="sc">%&gt;%</span> </span>
<span id="cb267-4"><a href="census-more.html#cb267-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(date) <span class="sc">%&gt;%</span> <span class="co"># our new function that gets the latest date</span></span>
<span id="cb267-5"><a href="census-more.html#cb267-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(county <span class="sc">!=</span> <span class="st">&quot;Unknown&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb267-6"><a href="census-more.html#cb267-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>state)</span>
<span id="cb267-7"><a href="census-more.html#cb267-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb267-8"><a href="census-more.html#cb267-8" aria-hidden="true" tabindex="-1"></a>tx_covid</span></code></pre></div>
<pre><code>## # A tibble: 255 x 5
## # Groups:   county [255]
##    date       county    fips  cases deaths
##    &lt;date&gt;     &lt;chr&gt;     &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt;
##  1 2022-03-08 Anderson  48001  9503    230
##  2 2022-03-08 Andrews   48003  3789     71
##  3 2022-03-08 Angelina  48005 15245    474
##  4 2022-03-08 Aransas   48007  4055     79
##  5 2022-03-08 Archer    48009  2096     28
##  6 2022-03-08 Armstrong 48011   503      9
##  7 2022-03-08 Atascosa  48013 13315    229
##  8 2022-03-08 Austin    48015  5592     71
##  9 2022-03-08 Bailey    48017  1382     38
## 10 2022-03-08 Bandera   48019  3541     74
## # ... with 245 more rows</code></pre>
<blockquote>
<p>IMPORTANT NOTE: The <strong>date</strong> values in your data should be more recent than what is shown here since you are downloading at a later date.</p>
</blockquote>
<p>Let’s break this down</p>
<ul>
<li>The first line creates a new R object <code>tx_covid</code> and fills it with the expression that follows, which is built from our raw <code>covid</code> data/</li>
<li>The next line filters for Texas. Typical stuff for us.</li>
<li>The next challenge is to find the most recent date for each county in Texas. There will be a row for each date for each county, and we want only the most recent date for each county. So, we do this by using <code>group_by(county)</code>so the next action will happen within the records for each county.</li>
<li><code>slice_max()</code> is our new function, which is related to the tidyverse <a href="https://dplyr.tidyverse.org/reference/slice.html"><code>slice()</code></a> function, which lets you “subset” rows of data based on its position in your data. The documentation includes this: “<code>slice_min()</code> and <code>slice_max()</code> select rows with highest or lowest values of a variable.” That is what we do here … we use <code>slice_max()</code> to get the “highest” or latest <code>date</code> in our data. Since this follows <code>group_by(county)</code>, it finds the most recent date for <em>each</em> county.</li>
<li>If you are running these one line at a time like I suggested, you’ll notice there are 255 returns when there are <em>only</em> 254 counties in Texas. That is because there is a county value of <strong>Unknown</strong>, which we filter out using a standard filter.</li>
<li>Lastly, we use <code>select()</code> to remove the <code>state</code> column since we don’t need it anymore.</li>
</ul>
<p>So now you have the latest COVID-19 case and death counts for each county in Texas.</p>
</div>
</div>
<div id="get-county-populations-using-tidycensus" class="section level2" number="12.5">
<h2><span class="header-section-number">12.5</span> Get county populations using tidycensus</h2>
<p>We can’t compare the counts of each county against each other because they have differing numbers of people. Let’s put it like this using Oct. 15, 2021 numbers: Harris County – the state’s largest county – has had 569,187 cases out of 4.7 million people. Loving County – the smallest county – has only 8 cases, but that is out of a total of 64 people in the county. Which is worse? And yes, only 64 people lived in Loving County when the 2020 census was taken on April 1, 2020.</p>
<p>So, let’s use tidycensus to get the populations. Since the 2020 Decennial “Redistricting file” was released this year, we have really fresh and accurate population numbers.</p>
<div id="find-the-data-on-data.census.gov" class="section level3" number="12.5.1">
<h3><span class="header-section-number">12.5.1</span> Find the data on data.census.gov</h3>
<p>As I said in the last chapter, the hardest part of using Census data is finding what you want. There is so much data it is hard to find or even know what you need.</p>
<p>From experience I know that in the first Decennial Redistricting data release, there is a <strong>RACE</strong> table that has a total population for each census geography. <strong>This is the most accurate count we have of people in the U.S., but we only get it every 10 years.</strong> You are just lucky to live at this time where this data is super fresh (relatively).</p>
<p>If you search for “Total Population” on <a href="http://data.census.gov" class="uri">http://data.census.gov</a> you should get the <strong>P1</strong> table called <strong>RACE</strong> as the first return, but if not you can <a href="https://data.census.gov/cedsci/table?tid=DECENNIALPL2020.P1">click here</a> to get directly to it.</p>
<div class="figure">
<img src="images/p1-table.png" alt="" />
<p class="caption">P1 table</p>
</div>
</div>
<div id="find-the-variable-name" class="section level3" number="12.5.2">
<h3><span class="header-section-number">12.5.2</span> Find the variable name</h3>
<p>OK, now for the fun part. We can again use <code>load_variables()</code>, but the program we search for is <strong><code>pl</code></strong>.</p>
<blockquote>
<p>UNIMPORTANT ASIDE: That is an L in “pl,” as in the PL 94-171, the law that requires the Census Bureau to produce this file. It’s kinda confusing since we are also working with the P1 (one) table.</p>
</blockquote>
<ol style="list-style-type: decimal">
<li>Start a new section and note you are getting the decennial population variable.</li>
<li>Run the code below and then open the table by double-clicking table icon for that object in your Environment pane.</li>
</ol>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="census-more.html#cb269-1" aria-hidden="true" tabindex="-1"></a>pl_variables <span class="ot">&lt;-</span> <span class="fu">load_variables</span>(<span class="dv">2020</span>, <span class="st">&quot;pl&quot;</span>, <span class="at">cache =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>This is how you can open the table:</p>
<div class="figure">
<img src="images/p1-open-table.png" alt="" />
<p class="caption">Open table</p>
</div>
<p>When we open that as a table view from your environment, we get lucky that we can see the value we are looking for: <code>P1_001N</code>.</p>
<div class="figure">
<img src="images/p1-variable.png" alt="" />
<p class="caption">P1 value</p>
</div>
<ol style="list-style-type: decimal">
<li>Note the name of the variable in your markdown so you have it handy.</li>
</ol>
</div>
<div id="fetch-the-population-data" class="section level3" number="12.5.3">
<h3><span class="header-section-number">12.5.3</span> Fetch the population data</h3>
<p>Getting data form the decennial census is similar to the ACS, just with a differently-named function: <code>get_decennial()</code>. You need at least the <strong>year</strong>, the <strong>variables</strong> and the <strong>geography</strong> for your return.</p>
<p>Since it is Alabama that we see on the <a href="https://data.census.gov/cedsci/table?tid=DECENNIALPL2020.P1">data.census.gov</a> portal, we’ll start by pulling state values to make sure our numbers match.</p>
<ol style="list-style-type: decimal">
<li>Start a subsection or otherwise note you are fetching a test of the variable. If you haven’t already, you should include a link back to your table on data.census.gov.</li>
<li>Insert the code block below and run it. Might as well copy/paste all of it because you need all three arguments for it to work.</li>
</ol>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="census-more.html#cb270-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_decennial</span>(</span>
<span id="cb270-2"><a href="census-more.html#cb270-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="dv">2020</span>,</span>
<span id="cb270-3"><a href="census-more.html#cb270-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="st">&quot;P1_001N&quot;</span>,</span>
<span id="cb270-4"><a href="census-more.html#cb270-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">geography =</span> <span class="st">&quot;state&quot;</span></span>
<span id="cb270-5"><a href="census-more.html#cb270-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Getting data from the 2020 decennial Census</code></pre>
<pre><code>## Using the PL 94-171 Redistricting Data summary file</code></pre>
<pre><code>## Note: 2020 decennial Census data use differential privacy, a technique that
## introduces errors into data to preserve respondent confidentiality.
## i Small counts should be interpreted with caution.
## i See https://www.census.gov/library/fact-sheets/2021/protecting-the-confidentiality-of-the-2020-census-redistricting-data.html for additional guidance.
## This message is displayed once per session.</code></pre>
<pre><code>## # A tibble: 52 x 4
##    GEOID NAME                 variable    value
##    &lt;chr&gt; &lt;chr&gt;                &lt;chr&gt;       &lt;dbl&gt;
##  1 01    Alabama              P1_001N   5024279
##  2 02    Alaska               P1_001N    733391
##  3 04    Arizona              P1_001N   7151502
##  4 05    Arkansas             P1_001N   3011524
##  5 06    California           P1_001N  39538223
##  6 08    Colorado             P1_001N   5773714
##  7 09    Connecticut          P1_001N   3605944
##  8 10    Delaware             P1_001N    989948
##  9 11    District of Columbia P1_001N    689545
## 10 16    Idaho                P1_001N   1839106
## # ... with 42 more rows</code></pre>
<p>Our return shows a value of 5024279 for Alabama, which matches the data portal, so we have the correct variable. Let’s keep this here just for reference.</p>
</div>
<div id="get-data-for-texas-counties" class="section level3" number="12.5.4">
<h3><span class="header-section-number">12.5.4</span> Get data for Texas counties</h3>
<ol style="list-style-type: decimal">
<li>Start a new section and note you are getting the Texas county populations.</li>
<li>Build your data using the <code>get_decennial()</code> as noted below. Note you need the first three arguments before it wil work at all.</li>
</ol>
<blockquote>
<p>I’ve suppressed the output here because it doesn’t show well in the book.</p>
</blockquote>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="census-more.html#cb275-1" aria-hidden="true" tabindex="-1"></a>tx_pop <span class="ot">&lt;-</span> <span class="fu">get_decennial</span>(</span>
<span id="cb275-2"><a href="census-more.html#cb275-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">year =</span> <span class="dv">2020</span>,</span>
<span id="cb275-3"><a href="census-more.html#cb275-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">variables =</span> <span class="st">&quot;P1_001N&quot;</span>,</span>
<span id="cb275-4"><a href="census-more.html#cb275-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">geography =</span> <span class="st">&quot;county&quot;</span>,</span>
<span id="cb275-5"><a href="census-more.html#cb275-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">state =</span> <span class="st">&quot;TX&quot;</span>,</span>
<span id="cb275-6"><a href="census-more.html#cb275-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">geometry =</span> <span class="cn">TRUE</span></span>
<span id="cb275-7"><a href="census-more.html#cb275-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb275-8"><a href="census-more.html#cb275-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb275-9"><a href="census-more.html#cb275-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(name)</span>
<span id="cb275-10"><a href="census-more.html#cb275-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb275-11"><a href="census-more.html#cb275-11" aria-hidden="true" tabindex="-1"></a>tx_pop</span></code></pre></div>
<p>A couple of things to note here:</p>
<ul>
<li>We set the <strong>geography</strong> argument to “county” to get county results across the U.S.</li>
<li>We use <strong>state</strong> argument set to “TX” to get just Texas counties.</li>
<li>We use the <code>geometry = TRUE</code> argument to get our shapes for mapping.</li>
<li>We pipe the result of all that into <code>clean_names()</code> because some of the column names are UPPERCASE. We don’t <em>have</em> to do this, I’m just anal retentive.</li>
</ul>
</div>
</div>
<div id="about-joins" class="section level2" number="12.6">
<h2><span class="header-section-number">12.6</span> About joins</h2>
<p>OK, before we go further we need to talk about joining data. It’s one of those <a href="">Basic Data Journalism Functions</a> …</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/T6PPd-ukFyk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
<p>There are several types of <a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">joins</a>. We describe these as left vs right based on which table we reference first (which is the left one).</p>
<p>What joins do is match rows from multiple data sets that have the same “key value” and then append the data along those rows. Our two data sets have the same value in both, they just happend to be named different things.</p>
<p>Look at these two glimpses and note the <strong>fips</strong> and <strong>geoid</strong> fields between them.</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="census-more.html#cb276-1" aria-hidden="true" tabindex="-1"></a>tx_covid <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 255
## Columns: 5
## Groups: county [255]
## $ date   &lt;date&gt; 2022-03-08, 2022-03-08, 2022-03-08, 2022-03-08, 2022-03-08, 20~
## $ county &lt;chr&gt; &quot;Anderson&quot;, &quot;Andrews&quot;, &quot;Angelina&quot;, &quot;Aransas&quot;, &quot;Archer&quot;, &quot;Armstr~
## $ fips   &lt;chr&gt; &quot;48001&quot;, &quot;48003&quot;, &quot;48005&quot;, &quot;48007&quot;, &quot;48009&quot;, &quot;48011&quot;, &quot;48013&quot;, ~
## $ cases  &lt;dbl&gt; 9503, 3789, 15245, 4055, 2096, 503, 13315, 5592, 1382, 3541, 21~
## $ deaths &lt;dbl&gt; 230, 71, 474, 79, 28, 9, 229, 71, 38, 74, 227, 32, 150, 869, 59~</code></pre>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb278-1"><a href="census-more.html#cb278-1" aria-hidden="true" tabindex="-1"></a>tx_pop <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 254
## Columns: 5
## $ geoid    &lt;chr&gt; &quot;48001&quot;, &quot;48003&quot;, &quot;48005&quot;, &quot;48007&quot;, &quot;48009&quot;, &quot;48011&quot;, &quot;48013&quot;~
## $ name     &lt;chr&gt; &quot;Anderson County, Texas&quot;, &quot;Andrews County, Texas&quot;, &quot;Angelina ~
## $ variable &lt;chr&gt; &quot;P1_001N&quot;, &quot;P1_001N&quot;, &quot;P1_001N&quot;, &quot;P1_001N&quot;, &quot;P1_001N&quot;, &quot;P1_00~
## $ value    &lt;dbl&gt; 57922, 18610, 86395, 23830, 8560, 1848, 48981, 30167, 6904, 2~
## $ geometry &lt;MULTIPOLYGON [°]&gt; MULTIPOLYGON (((-96.0648 31..., MULTIPOLYGON (((~</code></pre>
<p>The <code>fips</code> and <code>geoid</code> columns are the same value under different names. This is the FIPS code for counties used in all kinds of government data. It’s actually a combination of the <strong>state</strong> FIPS (48 for Texas) and the <strong>county</strong> designation (the last three numbers). This creates a unique combination for every county in the U.S.</p>
<p>Knowing we have these two similar values, we can <strong>Join</strong> the rows that have the same value in both. Basically we will add the <strong><em>columns</em></strong> of one data set to the other based on that value.</p>
<p>In our case, we have the same 254 rows in each data set, but if we didn’t we would need to decide what to do with data that DIDN’T match.</p>
<p>In the figure below, we can see which matching records are retained based on the type of join we use.</p>
<div class="figure">
<img src="images/joins-description.png" alt="" />
<p class="caption">Types of joins</p>
</div>
<p>The join syntax works like this, with the * as the direction of the join:</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="census-more.html#cb280-1" aria-hidden="true" tabindex="-1"></a>new_dataframe <span class="ot">&lt;-</span> <span class="er">*</span><span class="fu">_join</span>(first_df, second_df, <span class="at">by =</span> field_name_to_join_on)</span></code></pre></div>
<p>If the fields you are joining on are not named the same thing (as in our case), then you can define the relationships: <code>by = c("a" = "b")</code>.</p>
<p>For our purposes here we want to use an <code>inner_join()</code>. We have to <strong>start with our population data first</strong> for the mapping to work later. (This threw me for a loop when wrote this, so learn from my experience.) We’ll then add our our covid data.</p>
<div id="join-our-data-together" class="section level3" number="12.6.1">
<h3><span class="header-section-number">12.6.1</span> Join our data together</h3>
<ol style="list-style-type: decimal">
<li>Start a new section and note we are joining our data.</li>
<li>Add the code below, run and review the results and the explanation below.</li>
</ol>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="census-more.html#cb281-1" aria-hidden="true" tabindex="-1"></a>tx_joined <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(</span>
<span id="cb281-2"><a href="census-more.html#cb281-2" aria-hidden="true" tabindex="-1"></a>  tx_pop, <span class="co"># first table</span></span>
<span id="cb281-3"><a href="census-more.html#cb281-3" aria-hidden="true" tabindex="-1"></a>  tx_covid, <span class="co"># second table with columns we&#39;ll add</span></span>
<span id="cb281-4"><a href="census-more.html#cb281-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;geoid&quot;</span> <span class="ot">=</span> <span class="st">&quot;fips&quot;</span>) <span class="co"># note the joining columns</span></span>
<span id="cb281-5"><a href="census-more.html#cb281-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb281-6"><a href="census-more.html#cb281-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb281-7"><a href="census-more.html#cb281-7" aria-hidden="true" tabindex="-1"></a>tx_joined</span></code></pre></div>
<pre><code>## Simple feature collection with 254 features and 8 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -106.6456 ymin: 25.83738 xmax: -93.50829 ymax: 36.5007
## Geodetic CRS:  NAD83
## # A tibble: 254 x 9
##    geoid name   variable value                  geometry date       county cases
##    &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;    &lt;dbl&gt;        &lt;MULTIPOLYGON [°]&gt; &lt;date&gt;     &lt;chr&gt;  &lt;dbl&gt;
##  1 48001 Ander~ P1_001N  57922 (((-96.0648 31.98066, -9~ 2022-03-08 Ander~  9503
##  2 48003 Andre~ P1_001N  18610 (((-103.0647 32.52219, -~ 2022-03-08 Andre~  3789
##  3 48005 Angel~ P1_001N  86395 (((-95.00488 31.42396, -~ 2022-03-08 Angel~ 15245
##  4 48007 Arans~ P1_001N  23830 (((-96.8229 28.16743, -9~ 2022-03-08 Arans~  4055
##  5 48009 Arche~ P1_001N   8560 (((-98.95383 33.48959, -~ 2022-03-08 Archer  2096
##  6 48011 Armst~ P1_001N   1848 (((-101.6294 34.75006, -~ 2022-03-08 Armst~   503
##  7 48013 Atasc~ P1_001N  48981 (((-98.80488 29.10702, -~ 2022-03-08 Atasc~ 13315
##  8 48015 Austi~ P1_001N  30167 (((-96.62085 30.0452, -9~ 2022-03-08 Austin  5592
##  9 48017 Baile~ P1_001N   6904 (((-103.0469 33.8503, -1~ 2022-03-08 Bailey  1382
## 10 48019 Bande~ P1_001N  20851 (((-99.60332 29.74026, -~ 2022-03-08 Bande~  3541
## # ... with 244 more rows, and 1 more variable: deaths &lt;dbl&gt;</code></pre>
<p>So, to break this down:</p>
<ul>
<li>Our new combined dataframe will be called <code>tx_joined</code>, which is filled from the result of …</li>
<li>We start the <code>inner_join()</code> and then name our two tables.</li>
<li>Since our “key” columns don’t have the same name, we have to specify how to join them. We need to name these columns in the same order as we name the tables, hence <code>by = c("fips" = "geoid")</code></li>
</ul>
<p>Page through the result so you can see the new columns.</p>
<p>Here is glimpse of the new table:</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="census-more.html#cb283-1" aria-hidden="true" tabindex="-1"></a>tx_joined <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 254
## Columns: 9
## $ geoid    &lt;chr&gt; &quot;48001&quot;, &quot;48003&quot;, &quot;48005&quot;, &quot;48007&quot;, &quot;48009&quot;, &quot;48011&quot;, &quot;48013&quot;~
## $ name     &lt;chr&gt; &quot;Anderson County, Texas&quot;, &quot;Andrews County, Texas&quot;, &quot;Angelina ~
## $ variable &lt;chr&gt; &quot;P1_001N&quot;, &quot;P1_001N&quot;, &quot;P1_001N&quot;, &quot;P1_001N&quot;, &quot;P1_001N&quot;, &quot;P1_00~
## $ value    &lt;dbl&gt; 57922, 18610, 86395, 23830, 8560, 1848, 48981, 30167, 6904, 2~
## $ geometry &lt;MULTIPOLYGON [°]&gt; MULTIPOLYGON (((-96.0648 31..., MULTIPOLYGON (((~
## $ date     &lt;date&gt; 2022-03-08, 2022-03-08, 2022-03-08, 2022-03-08, 2022-03-08, ~
## $ county   &lt;chr&gt; &quot;Anderson&quot;, &quot;Andrews&quot;, &quot;Angelina&quot;, &quot;Aransas&quot;, &quot;Archer&quot;, &quot;Arms~
## $ cases    &lt;dbl&gt; 9503, 3789, 15245, 4055, 2096, 503, 13315, 5592, 1382, 3541, ~
## $ deaths   &lt;dbl&gt; 230, 71, 474, 79, 28, 9, 229, 71, 38, 74, 227, 32, 150, 869, ~</code></pre>
<p>Now that we have our <code>cases</code>, <code>deaths</code> and <code>value</code> (or population) columns in the same table so we can do some math to create case and death rates.</p>
</div>
<div id="clean-up-column-names-etc." class="section level3" number="12.6.2">
<h3><span class="header-section-number">12.6.2</span> Clean up column names, etc.</h3>
<p>Let’s rename our <code>value</code> column to a more descriptive <code>total_pop</code> and remove some other unneeded columns.</p>
<p>I don’t think we’ve renamed columns using <code>rename()</code> yet so we’ll do this together. Rename works similar to <code>mutate()</code> in that you name the new column first and then set it equal to the old one. We’re also using <code>select()</code> which we’ve done before.</p>
<ol style="list-style-type: decimal">
<li>Create a new section noting you are renaming columns and other cleanup.</li>
<li>Add this chunk and run it.</li>
</ol>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="census-more.html#cb285-1" aria-hidden="true" tabindex="-1"></a>tx_renamed <span class="ot">&lt;-</span> tx_joined <span class="sc">%&gt;%</span> </span>
<span id="cb285-2"><a href="census-more.html#cb285-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb285-3"><a href="census-more.html#cb285-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_pop =</span> value</span>
<span id="cb285-4"><a href="census-more.html#cb285-4" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb285-5"><a href="census-more.html#cb285-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>name, <span class="sc">-</span>variable)</span>
<span id="cb285-6"><a href="census-more.html#cb285-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb285-7"><a href="census-more.html#cb285-7" aria-hidden="true" tabindex="-1"></a>tx_renamed <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 254
## Columns: 7
## $ geoid     &lt;chr&gt; &quot;48001&quot;, &quot;48003&quot;, &quot;48005&quot;, &quot;48007&quot;, &quot;48009&quot;, &quot;48011&quot;, &quot;48013~
## $ total_pop &lt;dbl&gt; 57922, 18610, 86395, 23830, 8560, 1848, 48981, 30167, 6904, ~
## $ geometry  &lt;MULTIPOLYGON [°]&gt; MULTIPOLYGON (((-96.0648 31..., MULTIPOLYGON ((~
## $ date      &lt;date&gt; 2022-03-08, 2022-03-08, 2022-03-08, 2022-03-08, 2022-03-08,~
## $ county    &lt;chr&gt; &quot;Anderson&quot;, &quot;Andrews&quot;, &quot;Angelina&quot;, &quot;Aransas&quot;, &quot;Archer&quot;, &quot;Arm~
## $ cases     &lt;dbl&gt; 9503, 3789, 15245, 4055, 2096, 503, 13315, 5592, 1382, 3541,~
## $ deaths    &lt;dbl&gt; 230, 71, 474, 79, 28, 9, 229, 71, 38, 74, 227, 32, 150, 869,~</code></pre>
</div>
</div>
<div id="create-our-rate-columns" class="section level2" number="12.7">
<h2><span class="header-section-number">12.7</span> Create our rate columns</h2>
<p>Our whole goal here was to find the number of cases per population per county and we are finally at a place where we can. We do this using <code>mutate()</code> and we’ve done stuff like this in the past with the Military Surplus assignment.</p>
<p>We’re actually going to find “cases per 1,000 people” because otherwise the numbers would be too small to comprehend. For a good explanation of why we need this, read <a href="https://www.robertniles.com/stats/percap.shtml">Robert Niles’ take on per capita rates</a>. It is also covered on Page 16 of Numbers in the Newsroom by Sarah Cohen.</p>
<p>To get a per-1,000 rate, the math works like this: <strong>(cases / (total_pop / 1000))</strong>.</p>
<ol style="list-style-type: decimal">
<li>Start a new section noting you are creating your rates</li>
<li>Add the chunk and run it.</li>
</ol>
<blockquote>
<p>I’m suppressing the output here because the book doesn’t show it well.</p>
</blockquote>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="census-more.html#cb287-1" aria-hidden="true" tabindex="-1"></a>tx_rates <span class="ot">&lt;-</span> tx_renamed <span class="sc">%&gt;%</span> </span>
<span id="cb287-2"><a href="census-more.html#cb287-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb287-3"><a href="census-more.html#cb287-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">cases_per_pop =</span> (cases <span class="sc">/</span> (total_pop <span class="sc">/</span> <span class="dv">1000</span>)) <span class="sc">%&gt;%</span> <span class="fu">round</span>()</span>
<span id="cb287-4"><a href="census-more.html#cb287-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb287-5"><a href="census-more.html#cb287-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb287-6"><a href="census-more.html#cb287-6" aria-hidden="true" tabindex="-1"></a>tx_rates</span></code></pre></div>
<p>You should be able to comprehend the <code>mutate()</code> function by now.</p>
<ol style="list-style-type: decimal">
<li>Go to the last column in the tibble that returns and make sure you have a new column named `cases_perpop_ and that everything worked as you expected.</li>
</ol>
<div id="on-your-own-get-a-deaths-rate-per-1000" class="section level3" number="12.7.1">
<h3><span class="header-section-number">12.7.1</span> On your own: Get a deaths rate per 1,000</h3>
<ol style="list-style-type: decimal">
<li>Edit your rates chunk to add an additional rule to calculate deaths per 1,000 people. It’s pretty much the same but using <code>deaths</code>.</li>
</ol>
</div>
<div id="on-your-own-find-counties-with-highest-rates" class="section level3" number="12.7.2">
<h3><span class="header-section-number">12.7.2</span> On your own: Find counties with highest rates</h3>
<p>On your own, I want you to create <strong>two</strong> lists: One of the Top 10 counties with the highest cases-per-1,000 and another of the Top 10 counties with the highest deaths-per-1,000 cases. Don’t overthink this … it is a simple arrange, select and head combination. You <strong>do not</strong> need to save these into new object … just print to the screen.</p>
<p>Use <code>select()</code> to show just the county, total_pop, cases/deaths and the appropriate rate for each view. <strong>Note that the <code>geometry</code> column will <em>always</em> show</strong>. You can’t remove it … that’s just how it works.</p>
</div>
</div>
<div id="mapping-the-rates-for-texas-counties" class="section level2" number="12.8">
<h2><span class="header-section-number">12.8</span> Mapping the rates for Texas counties</h2>
<p>We’ll build a Texas map of the rates much like we did with the broadband rates in the last chapter. In fact it is pretty much the same code with updated variables and text.</p>
<ol style="list-style-type: decimal">
<li>Create a new section that you will map cases per 1,000</li>
<li>Add the chunk below and run it.</li>
<li>Update the labs to add a title, etc.</li>
</ol>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb288-1"><a href="census-more.html#cb288-1" aria-hidden="true" tabindex="-1"></a>tx_rates <span class="sc">%&gt;%</span> </span>
<span id="cb288-2"><a href="census-more.html#cb288-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb288-3"><a href="census-more.html#cb288-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill =</span> cases_per_pop), <span class="at">color =</span> <span class="st">&quot;white&quot;</span>, <span class="at">size =</span> .<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb288-4"><a href="census-more.html#cb288-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb288-5"><a href="census-more.html#cb288-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb288-6"><a href="census-more.html#cb288-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;COVID cases per 1,000 in Texas counties&quot;</span>,</span>
<span id="cb288-7"><a href="census-more.html#cb288-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">caption =</span> <span class="st">&quot;Source: New York Times COVID, Census Bureau/2020 Decennial&quot;</span></span>
<span id="cb288-8"><a href="census-more.html#cb288-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb288-9"><a href="census-more.html#cb288-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_distiller</span>(</span>
<span id="cb288-10"><a href="census-more.html#cb288-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">palette =</span> <span class="st">&quot;Greens&quot;</span>,</span>
<span id="cb288-11"><a href="census-more.html#cb288-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">direction =</span> <span class="dv">1</span>,</span>
<span id="cb288-12"><a href="census-more.html#cb288-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">name =</span> <span class="st">&quot;Cases per 1000&quot;</span></span>
<span id="cb288-13"><a href="census-more.html#cb288-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb288-14"><a href="census-more.html#cb288-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.margin =</span> <span class="fu">unit</span>(<span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">0</span>,<span class="dv">10</span>,<span class="dv">0</span>), <span class="st">&quot;pt&quot;</span>))</span></code></pre></div>
<p><img src="12-census-more_files/figure-html/map-rates-1.png" width="672" /></p>
</div>
<div id="on-your-own-map-the-deaths-per-1000" class="section level2" number="12.9">
<h2><span class="header-section-number">12.9</span> On your own: Map the deaths per 1,000</h2>
<p>On your own, create a map like above but:</p>
<ol style="list-style-type: decimal">
<li>Use your deaths per 1,000 data.</li>
<li>Change the color</li>
<li>Update the titles, etc to be correct.</li>
</ol>
</div>
<div id="what-weve-learned-2" class="section level2" number="12.10">
<h2><span class="header-section-number">12.10</span> What we’ve learned</h2>
<ul>
<li>We learned that the New York Times is awesome that they have collected COVID data and then shared it with the world.</li>
<li>We used <code>group_by()</code> and <a href="https://dplyr.tidyverse.org/reference/slice.html"><code>slice_max()</code></a> to get the most recent data for each county.</li>
<li>We used tidycensus to get population data and geometry data for mapping.</li>
<li>You made more maps.</li>
</ul>
</div>
<div id="turn-in-your-work-2" class="section level2" number="12.11">
<h2><span class="header-section-number">12.11</span> Turn in your work</h2>
<p>(There may be an extra-credit assignment that you can try if I can work it up in time. You should know by class time.)</p>
<ol style="list-style-type: decimal">
<li>Make sure your Markdown is in good shape, chunks named, etc.</li>
<li>Make sure everything runs and knits all the way through.</li>
<li>Zip your project and turn it into Canvas.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="census-intro.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="mastery.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/12-census-more.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
