<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 15 Transform | Reporting with Data in R</title>
  <meta name="description" content="Chapter 15 Transform | Reporting with Data in R is a series of lessons and instructions used in courses in the School of Journalism and Media, Moody College of Communication at the University of Texas at Austin. It is taught by Christian McDonald, assistant professor of practice." />
  <meta name="generator" content="bookdown 0.23 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 15 Transform | Reporting with Data in R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Chapter 15 Transform | Reporting with Data in R is a series of lessons and instructions used in courses in the School of Journalism and Media, Moody College of Communication at the University of Texas at Austin. It is taught by Christian McDonald, assistant professor of practice." />
  <meta name="github-repo" content="utdata/rwdir" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 15 Transform | Reporting with Data in R" />
  
  <meta name="twitter:description" content="Chapter 15 Transform | Reporting with Data in R is a series of lessons and instructions used in courses in the School of Journalism and Media, Moody College of Communication at the University of Texas at Austin. It is taught by Christian McDonald, assistant professor of practice." />
  

<meta name="author" content="Christian McDonald" />


<meta name="date" content="2021-08-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="sped-import.html"/>
<link rel="next" href="sped-summarize.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<style type="text/css">
  p.caption {
    color: #777;
    margin-top: 10px;
  }
  p code, pre, pre code, li code {
    background-color: #DCDCDC !important;
  }
</style>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Reporting with Data in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About this book</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#about-my-philosphy"><i class="fa fa-check"></i>About my philosphy</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#tips-on-my-writing-style"><i class="fa fa-check"></i>Tips on my writing style</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#things-to-do"><i class="fa fa-check"></i>Things to do</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#notes-some-important"><i class="fa fa-check"></i>Notes, some important</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#copy-code-blocks"><i class="fa fa-check"></i>Copy code blocks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#about-the-author"><i class="fa fa-check"></i>About the author</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i>License</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#other-resources"><i class="fa fa-check"></i>Other resources</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="install.html"><a href="install.html"><i class="fa fa-check"></i><b>1</b> Install Party</a>
<ul>
<li class="chapter" data-level="1.1" data-path="install.html"><a href="install.html#mac-vs-pc"><i class="fa fa-check"></i><b>1.1</b> Mac vs PC</a></li>
<li class="chapter" data-level="1.2" data-path="install.html"><a href="install.html#installing-r"><i class="fa fa-check"></i><b>1.2</b> Installing R</a></li>
<li class="chapter" data-level="1.3" data-path="install.html"><a href="install.html#installing-rstudio"><i class="fa fa-check"></i><b>1.3</b> Installing RStudio</a></li>
<li class="chapter" data-level="1.4" data-path="install.html"><a href="install.html#class-project-folder"><i class="fa fa-check"></i><b>1.4</b> Class project folder</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#rstudio-tour"><i class="fa fa-check"></i><b>2.1</b> RStudio tour</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#updating-preferences"><i class="fa fa-check"></i><b>2.2</b> Updating preferences</a></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#starting-a-new-project"><i class="fa fa-check"></i><b>2.3</b> Starting a new Project</a></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#using-r-notebooks"><i class="fa fa-check"></i><b>2.4</b> Using R Notebooks</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="intro.html"><a href="intro.html#create-your-first-notebook"><i class="fa fa-check"></i><b>2.4.1</b> Create your first notebook</a></li>
<li class="chapter" data-level="2.4.2" data-path="intro.html"><a href="intro.html#save-the-.rmd-file"><i class="fa fa-check"></i><b>2.4.2</b> Save the .Rmd file</a></li>
<li class="chapter" data-level="2.4.3" data-path="intro.html"><a href="intro.html#run-the-notebook"><i class="fa fa-check"></i><b>2.4.3</b> Run the notebook</a></li>
<li class="chapter" data-level="2.4.4" data-path="intro.html"><a href="intro.html#a-note-about-rmarkdown"><i class="fa fa-check"></i><b>2.4.4</b> A note about RMarkdown</a></li>
<li class="chapter" data-level="2.4.5" data-path="intro.html"><a href="intro.html#adding-new-code-chunks"><i class="fa fa-check"></i><b>2.4.5</b> Adding new code chunks</a></li>
<li class="chapter" data-level="2.4.6" data-path="intro.html"><a href="intro.html#practice-adding-code-chunks"><i class="fa fa-check"></i><b>2.4.6</b> Practice adding code chunks</a></li>
<li class="chapter" data-level="2.4.7" data-path="intro.html"><a href="intro.html#preview-the-report"><i class="fa fa-check"></i><b>2.4.7</b> Preview the report</a></li>
<li class="chapter" data-level="2.4.8" data-path="intro.html"><a href="intro.html#the-toolbar"><i class="fa fa-check"></i><b>2.4.8</b> The toolbar</a></li>
<li class="chapter" data-level="2.4.9" data-path="intro.html"><a href="intro.html#knit-the-final-workbook"><i class="fa fa-check"></i><b>2.4.9</b> Knit the final workbook</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="intro.html"><a href="intro.html#turning-in-our-projects"><i class="fa fa-check"></i><b>2.5</b> Turning in our projects</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="import.html"><a href="import.html"><i class="fa fa-check"></i><b>3</b> Import</a>
<ul>
<li class="chapter" data-level="3.1" data-path="import.html"><a href="import.html#learning-goals-of-this-lesson"><i class="fa fa-check"></i><b>3.1</b> Learning goals of this lesson</a></li>
<li class="chapter" data-level="3.2" data-path="import.html"><a href="import.html#basic-steps-of-this-lesson"><i class="fa fa-check"></i><b>3.2</b> Basic steps of this lesson</a></li>
<li class="chapter" data-level="3.3" data-path="import.html"><a href="import.html#create-a-new-project"><i class="fa fa-check"></i><b>3.3</b> Create a new project</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="import.html"><a href="import.html#describe-the-goals-of-the-notebook"><i class="fa fa-check"></i><b>3.3.1</b> Describe the goals of the notebook</a></li>
<li class="chapter" data-level="3.3.2" data-path="import.html"><a href="import.html#the-r-package-environment"><i class="fa fa-check"></i><b>3.3.2</b> The R Package environment</a></li>
<li class="chapter" data-level="3.3.3" data-path="import.html"><a href="import.html#installing-and-using-packages"><i class="fa fa-check"></i><b>3.3.3</b> Installing and using packages</a></li>
<li class="chapter" data-level="3.3.4" data-path="import.html"><a href="import.html#load-the-libraries"><i class="fa fa-check"></i><b>3.3.4</b> Load the libraries</a></li>
<li class="chapter" data-level="3.3.5" data-path="import.html"><a href="import.html#create-a-directory-for-your-data"><i class="fa fa-check"></i><b>3.3.5</b> Create a directory for your data</a></li>
<li class="chapter" data-level="3.3.6" data-path="import.html"><a href="import.html#lets-get-our-data"><i class="fa fa-check"></i><b>3.3.6</b> Let’s get our data</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="import.html"><a href="import.html#about-data-sources"><i class="fa fa-check"></i><b>3.4</b> About data sources</a></li>
<li class="chapter" data-level="3.5" data-path="import.html"><a href="import.html#our-project-data"><i class="fa fa-check"></i><b>3.5</b> Our project data</a></li>
<li class="chapter" data-level="3.6" data-path="import.html"><a href="import.html#data-dictionary"><i class="fa fa-check"></i><b>3.6</b> Data dictionary</a></li>
<li class="chapter" data-level="3.7" data-path="import.html"><a href="import.html#import-the-data"><i class="fa fa-check"></i><b>3.7</b> Import the data</a></li>
<li class="chapter" data-level="3.8" data-path="import.html"><a href="import.html#assign-our-import-to-a-tibble"><i class="fa fa-check"></i><b>3.8</b> Assign our import to a tibble</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="import.html"><a href="import.html#print-a-peek-to-the-screen"><i class="fa fa-check"></i><b>3.8.1</b> Print a peek to the screen</a></li>
<li class="chapter" data-level="3.8.2" data-path="import.html"><a href="import.html#glimpse-the-data"><i class="fa fa-check"></i><b>3.8.2</b> Glimpse the data</a></li>
<li class="chapter" data-level="3.8.3" data-path="import.html"><a href="import.html#about-the-pipe"><i class="fa fa-check"></i><b>3.8.3</b> About the pipe %&gt;%</a></li>
<li class="chapter" data-level="3.8.4" data-path="import.html"><a href="import.html#what-is-clean-data"><i class="fa fa-check"></i><b>3.8.4</b> What is clean data</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="import.html"><a href="import.html#cleaning-column-names"><i class="fa fa-check"></i><b>3.9</b> Cleaning column names</a></li>
<li class="chapter" data-level="3.10" data-path="import.html"><a href="import.html#fixing-the-date"><i class="fa fa-check"></i><b>3.10</b> Fixing the date</a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="import.html"><a href="import.html#working-with-mutate"><i class="fa fa-check"></i><b>3.10.1</b> Working with mutate()</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="import.html"><a href="import.html#arrange-the-data"><i class="fa fa-check"></i><b>3.11</b> Arrange the data</a></li>
<li class="chapter" data-level="3.12" data-path="import.html"><a href="import.html#selecting-columns"><i class="fa fa-check"></i><b>3.12</b> Selecting columns</a></li>
<li class="chapter" data-level="3.13" data-path="import.html"><a href="import.html#exporting-data"><i class="fa fa-check"></i><b>3.13</b> Exporting data</a>
<ul>
<li class="chapter" data-level="3.13.1" data-path="import.html"><a href="import.html#single-notebook-philosophy"><i class="fa fa-check"></i><b>3.13.1</b> Single-notebook philosophy</a></li>
<li class="chapter" data-level="3.13.2" data-path="import.html"><a href="import.html#exporting-as-rds"><i class="fa fa-check"></i><b>3.13.2</b> Exporting as rds</a></li>
</ul></li>
<li class="chapter" data-level="3.14" data-path="import.html"><a href="import.html#naming-chunks"><i class="fa fa-check"></i><b>3.14</b> Naming chunks</a></li>
<li class="chapter" data-level="3.15" data-path="import.html"><a href="import.html#knit-your-page"><i class="fa fa-check"></i><b>3.15</b> Knit your page</a></li>
<li class="chapter" data-level="3.16" data-path="import.html"><a href="import.html#review-of-what-weve-learned-so-far"><i class="fa fa-check"></i><b>3.16</b> Review of what we’ve learned so far</a></li>
<li class="chapter" data-level="3.17" data-path="import.html"><a href="import.html#turn-in-your-work"><i class="fa fa-check"></i><b>3.17</b> Turn in your work</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="wrangle.html"><a href="wrangle.html"><i class="fa fa-check"></i><b>4</b> Wrangle</a>
<ul>
<li class="chapter" data-level="4.1" data-path="wrangle.html"><a href="wrangle.html#goals-of-this-lesson"><i class="fa fa-check"></i><b>4.1</b> Goals of this lesson</a></li>
<li class="chapter" data-level="4.2" data-path="wrangle.html"><a href="wrangle.html#about-the-story"><i class="fa fa-check"></i><b>4.2</b> About the story</a></li>
<li class="chapter" data-level="4.3" data-path="wrangle.html"><a href="wrangle.html#setting-up-an-analysis-notebook"><i class="fa fa-check"></i><b>4.3</b> Setting up an analysis notebook</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="wrangle.html"><a href="wrangle.html#import-the-data-on-your-own"><i class="fa fa-check"></i><b>4.3.1</b> Import the data on your own</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="wrangle.html"><a href="wrangle.html#introducing-dplyr"><i class="fa fa-check"></i><b>4.4</b> Introducing dplyr</a></li>
<li class="chapter" data-level="4.5" data-path="wrangle.html"><a href="wrangle.html#most-appearances"><i class="fa fa-check"></i><b>4.5</b> Most appearances</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="wrangle.html"><a href="wrangle.html#group-aggregate"><i class="fa fa-check"></i><b>4.5.1</b> Group &amp; Aggregate</a></li>
<li class="chapter" data-level="4.5.2" data-path="wrangle.html"><a href="wrangle.html#summarize"><i class="fa fa-check"></i><b>4.5.2</b> Summarize</a></li>
<li class="chapter" data-level="4.5.3" data-path="wrangle.html"><a href="wrangle.html#group-by"><i class="fa fa-check"></i><b>4.5.3</b> Group by</a></li>
<li class="chapter" data-level="4.5.4" data-path="wrangle.html"><a href="wrangle.html#arrange-the-results"><i class="fa fa-check"></i><b>4.5.4</b> Arrange the results</a></li>
<li class="chapter" data-level="4.5.5" data-path="wrangle.html"><a href="wrangle.html#get-the-top-of-the-list"><i class="fa fa-check"></i><b>4.5.5</b> Get the top of the list</a></li>
<li class="chapter" data-level="4.5.6" data-path="wrangle.html"><a href="wrangle.html#a-shortcut-count"><i class="fa fa-check"></i><b>4.5.6</b> A shortcut: count()</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="wrangle.html"><a href="wrangle.html#most-songs-to-reach-no.-1"><i class="fa fa-check"></i><b>4.6</b> Most songs to reach No. 1</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="wrangle.html"><a href="wrangle.html#filter"><i class="fa fa-check"></i><b>4.6.1</b> Filter</a></li>
<li class="chapter" data-level="4.6.2" data-path="wrangle.html"><a href="wrangle.html#comparisons-logical-tests"><i class="fa fa-check"></i><b>4.6.2</b> Comparisons: Logical tests</a></li>
<li class="chapter" data-level="4.6.3" data-path="wrangle.html"><a href="wrangle.html#filter-for-week_position"><i class="fa fa-check"></i><b>4.6.3</b> Filter for week_position</a></li>
<li class="chapter" data-level="4.6.4" data-path="wrangle.html"><a href="wrangle.html#complex-filters"><i class="fa fa-check"></i><b>4.6.4</b> Complex filters</a></li>
<li class="chapter" data-level="4.6.5" data-path="wrangle.html"><a href="wrangle.html#using-distinct"><i class="fa fa-check"></i><b>4.6.5</b> Using distinct()</a></li>
<li class="chapter" data-level="4.6.6" data-path="wrangle.html"><a href="wrangle.html#summarize-the-performers"><i class="fa fa-check"></i><b>4.6.6</b> Summarize the performers</a></li>
<li class="chapter" data-level="4.6.7" data-path="wrangle.html"><a href="wrangle.html#filter-after-summary"><i class="fa fa-check"></i><b>4.6.7</b> Filter after summary</a></li>
<li class="chapter" data-level="4.6.8" data-path="wrangle.html"><a href="wrangle.html#try-count-on-your-own"><i class="fa fa-check"></i><b>4.6.8</b> Try count on your own</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="wrangle.html"><a href="wrangle.html#no.-1-hits-in-last-five-years"><i class="fa fa-check"></i><b>4.7</b> No. 1 hits in last five years</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="wrangle.html"><a href="wrangle.html#group-on-your-own"><i class="fa fa-check"></i><b>4.7.1</b> Group on your own</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="wrangle.html"><a href="wrangle.html#top-10-hits-overall"><i class="fa fa-check"></i><b>4.8</b> Top 10 hits overall</a></li>
<li class="chapter" data-level="4.9" data-path="wrangle.html"><a href="wrangle.html#most-appearances-at-any-position"><i class="fa fa-check"></i><b>4.9</b> Most appearances at any position</a></li>
<li class="chapter" data-level="4.10" data-path="wrangle.html"><a href="wrangle.html#most-weeks-at-no.-1"><i class="fa fa-check"></i><b>4.10</b> Most weeks at No. 1</a></li>
<li class="chapter" data-level="4.11" data-path="wrangle.html"><a href="wrangle.html#review-of-what-weve-learned"><i class="fa fa-check"></i><b>4.11</b> Review of what we’ve learned</a></li>
<li class="chapter" data-level="4.12" data-path="wrangle.html"><a href="wrangle.html#turn-in-your-project"><i class="fa fa-check"></i><b>4.12</b> Turn in your project</a></li>
<li class="chapter" data-level="4.13" data-path="wrangle.html"><a href="wrangle.html#soundtrack-for-this-assignment"><i class="fa fa-check"></i><b>4.13</b> Soundtrack for this assignment</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="wrangle-mastery.html"><a href="wrangle-mastery.html"><i class="fa fa-check"></i><b>5</b> Wrangle mastery</a>
<ul>
<li class="chapter" data-level="5.1" data-path="wrangle-mastery.html"><a href="wrangle-mastery.html#military-surplus-transfers"><i class="fa fa-check"></i><b>5.1</b> Military surplus transfers</a></li>
<li class="chapter" data-level="5.2" data-path="wrangle-mastery.html"><a href="wrangle-mastery.html#the-leso-program"><i class="fa fa-check"></i><b>5.2</b> The LESO program</a></li>
<li class="chapter" data-level="5.3" data-path="wrangle-mastery.html"><a href="wrangle-mastery.html#about-the-data"><i class="fa fa-check"></i><b>5.3</b> About the data</a></li>
<li class="chapter" data-level="5.4" data-path="wrangle-mastery.html"><a href="wrangle-mastery.html#some-helpful-hints"><i class="fa fa-check"></i><b>5.4</b> Some helpful hints</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="wrangle-mastery.html"><a href="wrangle-mastery.html#create-columns-using-math-from-other-columns"><i class="fa fa-check"></i><b>5.4.1</b> Create columns using math from other columns</a></li>
<li class="chapter" data-level="5.4.2" data-path="wrangle-mastery.html"><a href="wrangle-mastery.html#math-within-summarize"><i class="fa fa-check"></i><b>5.4.2</b> Math within summarize</a></li>
<li class="chapter" data-level="5.4.3" data-path="wrangle-mastery.html"><a href="wrangle-mastery.html#filter-from-a-collection"><i class="fa fa-check"></i><b>5.4.3</b> Filter from a collection</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="wrangle-mastery.html"><a href="wrangle-mastery.html#the-questions-to-answer-and-write-about"><i class="fa fa-check"></i><b>5.5</b> The questions to answer and write about</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="wrangle-mastery.html"><a href="wrangle-mastery.html#requirements-of-the-assignment"><i class="fa fa-check"></i><b>5.5.1</b> Requirements of the assignment</a></li>
<li class="chapter" data-level="5.5.2" data-path="wrangle-mastery.html"><a href="wrangle-mastery.html#specifics-for-importcleaning"><i class="fa fa-check"></i><b>5.5.2</b> Specifics for import/cleaning</a></li>
<li class="chapter" data-level="5.5.3" data-path="wrangle-mastery.html"><a href="wrangle-mastery.html#specifics-for-analysis"><i class="fa fa-check"></i><b>5.5.3</b> Specifics for analysis</a></li>
<li class="chapter" data-level="5.5.4" data-path="wrangle-mastery.html"><a href="wrangle-mastery.html#write-a-data-drop"><i class="fa fa-check"></i><b>5.5.4</b> Write a data drop</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="plots.html"><a href="plots.html"><i class="fa fa-check"></i><b>6</b> Plots</a>
<ul>
<li class="chapter" data-level="6.1" data-path="plots.html"><a href="plots.html#updates-needed"><i class="fa fa-check"></i><b>6.1</b> UPDATES NEEDED</a></li>
<li class="chapter" data-level="6.2" data-path="plots.html"><a href="plots.html#goals-for-this-section"><i class="fa fa-check"></i><b>6.2</b> Goals for this section</a></li>
<li class="chapter" data-level="6.3" data-path="plots.html"><a href="plots.html#introduction-ggplot"><i class="fa fa-check"></i><b>6.3</b> Introduction ggplot</a></li>
<li class="chapter" data-level="6.4" data-path="plots.html"><a href="plots.html#the-basic-ggplot-template"><i class="fa fa-check"></i><b>6.4</b> The basic ggplot template</a></li>
<li class="chapter" data-level="6.5" data-path="plots.html"><a href="plots.html#lets-plot"><i class="fa fa-check"></i><b>6.5</b> Let’s plot!</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="plots.html"><a href="plots.html#set-up-our-notebook"><i class="fa fa-check"></i><b>6.5.1</b> Set up our Notebook</a></li>
<li class="chapter" data-level="6.5.2" data-path="plots.html"><a href="plots.html#scatterplot"><i class="fa fa-check"></i><b>6.5.2</b> Scatterplot</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="plots.html"><a href="plots.html#plotting-our-wells-data"><i class="fa fa-check"></i><b>6.6</b> Plotting our wells data</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="plots.html"><a href="plots.html#total-wells-per-county"><i class="fa fa-check"></i><b>6.6.1</b> Total wells per county</a></li>
<li class="chapter" data-level="6.6.2" data-path="plots.html"><a href="plots.html#add-a-layer-of-text-labels"><i class="fa fa-check"></i><b>6.6.2</b> Add a layer of text labels</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="plots.html"><a href="plots.html#wells-per-county-over-time"><i class="fa fa-check"></i><b>6.7</b> Wells per county over time</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="plots.html"><a href="plots.html#work-up-the-data-frame"><i class="fa fa-check"></i><b>6.7.1</b> Work up the data frame</a></li>
<li class="chapter" data-level="6.7.2" data-path="plots.html"><a href="plots.html#draw-the-plot"><i class="fa fa-check"></i><b>6.7.2</b> Draw the plot</a></li>
<li class="chapter" data-level="6.7.3" data-path="plots.html"><a href="plots.html#your-turn-add-layers"><i class="fa fa-check"></i><b>6.7.3</b> Your turn: Add layers</a></li>
<li class="chapter" data-level="6.7.4" data-path="plots.html"><a href="plots.html#dates-as-numbers-and-the-problems-they-cause"><i class="fa fa-check"></i><b>6.7.4</b> Dates as numbers and the problems they cause</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="plots.html"><a href="plots.html#your-turn-build-a-line-chart"><i class="fa fa-check"></i><b>6.8</b> Your turn: Build a line chart</a></li>
<li class="chapter" data-level="6.9" data-path="plots.html"><a href="plots.html#review-of-ggplot"><i class="fa fa-check"></i><b>6.9</b> Review of ggplot</a></li>
<li class="chapter" data-level="6.10" data-path="plots.html"><a href="plots.html#plotly-for-more-interactive-graphics"><i class="fa fa-check"></i><b>6.10</b> Plotly for more interactive graphics</a>
<ul>
<li class="chapter" data-level="6.10.1" data-path="plots.html"><a href="plots.html#ggplotly"><i class="fa fa-check"></i><b>6.10.1</b> ggplotly</a></li>
<li class="chapter" data-level="6.10.2" data-path="plots.html"><a href="plots.html#more-with-plot_ly-function"><i class="fa fa-check"></i><b>6.10.2</b> More with <code>plot_ly()</code> function</a></li>
<li class="chapter" data-level="6.10.3" data-path="plots.html"><a href="plots.html#plotlys-freemium-model"><i class="fa fa-check"></i><b>6.10.3</b> Plotly’s freemium model</a></li>
</ul></li>
<li class="chapter" data-level="6.11" data-path="plots.html"><a href="plots.html#resources"><i class="fa fa-check"></i><b>6.11</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="census.html"><a href="census.html"><i class="fa fa-check"></i><b>7</b> Census</a>
<ul>
<li class="chapter" data-level="7.1" data-path="census.html"><a href="census.html#goals-of-this-section"><i class="fa fa-check"></i><b>7.1</b> Goals of this section</a></li>
<li class="chapter" data-level="7.2" data-path="census.html"><a href="census.html#census-bureau-programs-and-platforms"><i class="fa fa-check"></i><b>7.2</b> Census Bureau programs and platforms</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="census.html"><a href="census.html#decennial-census"><i class="fa fa-check"></i><b>7.2.1</b> Decennial Census</a></li>
<li class="chapter" data-level="7.2.2" data-path="census.html"><a href="census.html#american-community-survey"><i class="fa fa-check"></i><b>7.2.2</b> American Community Survey</a></li>
<li class="chapter" data-level="7.2.3" data-path="census.html"><a href="census.html#population-estimates-program"><i class="fa fa-check"></i><b>7.2.3</b> Population Estimates Program</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="census.html"><a href="census.html#using-the-new-data-portal"><i class="fa fa-check"></i><b>7.3</b> Using the new data portal</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="census.html"><a href="census.html#tips-about-using-downloaded-portal-data-in-r"><i class="fa fa-check"></i><b>7.3.1</b> Tips about using downloaded portal data in R</a></li>
<li class="chapter" data-level="7.3.2" data-path="census.html"><a href="census.html#importing-downloaded-data"><i class="fa fa-check"></i><b>7.3.2</b> Importing downloaded data</a></li>
<li class="chapter" data-level="7.3.3" data-path="census.html"><a href="census.html#fields-made-to-join-with-other-data"><i class="fa fa-check"></i><b>7.3.3</b> Fields made to join with other data</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="census.html"><a href="census.html#using-the-census-api-in-r"><i class="fa fa-check"></i><b>7.4</b> Using the Census API in R</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="census.html"><a href="census.html#setting-up-an-api-key"><i class="fa fa-check"></i><b>7.4.1</b> Setting up an API key</a></li>
<li class="chapter" data-level="7.4.2" data-path="census.html"><a href="census.html#the-censusapi-package"><i class="fa fa-check"></i><b>7.4.2</b> The censusapi package</a></li>
<li class="chapter" data-level="7.4.3" data-path="census.html"><a href="census.html#the-tidycensus-package"><i class="fa fa-check"></i><b>7.4.3</b> The tidycensus package</a></li>
<li class="chapter" data-level="7.4.4" data-path="census.html"><a href="census.html#adding-geometry-to-tidycensus"><i class="fa fa-check"></i><b>7.4.4</b> Adding geometry to tidycensus</a></li>
<li class="chapter" data-level="7.4.5" data-path="census.html"><a href="census.html#map-shapes-only-with-tigris"><i class="fa fa-check"></i><b>7.4.5</b> Map shapes only with tigris</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="census.html"><a href="census.html#interactive-maps-with-leaflet"><i class="fa fa-check"></i><b>7.5</b> Interactive maps with leaflet</a></li>
<li class="chapter" data-level="7.6" data-path="census.html"><a href="census.html#resources-1"><i class="fa fa-check"></i><b>7.6</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="tidy.html"><a href="tidy.html"><i class="fa fa-check"></i><b>8</b> Tidy data</a>
<ul>
<li class="chapter" data-level="8.1" data-path="tidy.html"><a href="tidy.html#updates-needed-1"><i class="fa fa-check"></i><b>8.1</b> UPDATES NEEDED</a></li>
<li class="chapter" data-level="8.2" data-path="tidy.html"><a href="tidy.html#goals-for-this-section-1"><i class="fa fa-check"></i><b>8.2</b> Goals for this section</a></li>
<li class="chapter" data-level="8.3" data-path="tidy.html"><a href="tidy.html#what-is-tidy-data"><i class="fa fa-check"></i><b>8.3</b> What is tidy data</a></li>
<li class="chapter" data-level="8.4" data-path="tidy.html"><a href="tidy.html#tidyr-package"><i class="fa fa-check"></i><b>8.4</b> Tidyr package</a></li>
<li class="chapter" data-level="8.5" data-path="tidy.html"><a href="tidy.html#the-tidyr-verbs"><i class="fa fa-check"></i><b>8.5</b> The tidyr verbs</a></li>
<li class="chapter" data-level="8.6" data-path="tidy.html"><a href="tidy.html#set-up-the-mixbev-project"><i class="fa fa-check"></i><b>8.6</b> Set up the mixbev project</a></li>
<li class="chapter" data-level="8.7" data-path="tidy.html"><a href="tidy.html#create-an-explore-notebook"><i class="fa fa-check"></i><b>8.7</b> Create an explore notebook</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="tidy.html"><a href="tidy.html#peruse-the-data"><i class="fa fa-check"></i><b>8.7.1</b> Peruse the data</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="tidy.html"><a href="tidy.html#what-might-we-learn-about-this-dataset"><i class="fa fa-check"></i><b>8.8</b> What might we learn about this dataset</a></li>
<li class="chapter" data-level="8.9" data-path="tidy.html"><a href="tidy.html#add-years-and-months-values"><i class="fa fa-check"></i><b>8.9</b> Add years and months values</a></li>
<li class="chapter" data-level="8.10" data-path="tidy.html"><a href="tidy.html#campus-bars"><i class="fa fa-check"></i><b>8.10</b> Campus bars</a>
<ul>
<li class="chapter" data-level="8.10.1" data-path="tidy.html"><a href="tidy.html#total-78705-sales-leaders-in-2018"><i class="fa fa-check"></i><b>8.10.1</b> Total 78705 sales leaders in 2018</a></li>
</ul></li>
<li class="chapter" data-level="8.11" data-path="tidy.html"><a href="tidy.html#west-campus-student-hot-spots"><i class="fa fa-check"></i><b>8.11</b> West Campus student hot spots</a></li>
<li class="chapter" data-level="8.12" data-path="tidy.html"><a href="tidy.html#campus-area-bar-sales-over-time"><i class="fa fa-check"></i><b>8.12</b> Campus-area bar sales over time</a>
<ul>
<li class="chapter" data-level="8.12.1" data-path="tidy.html"><a href="tidy.html#visualizing-your-visualization"><i class="fa fa-check"></i><b>8.12.1</b> Visualizing your visualization</a></li>
<li class="chapter" data-level="8.12.2" data-path="tidy.html"><a href="tidy.html#what-did-we-find"><i class="fa fa-check"></i><b>8.12.2</b> What did we find?</a></li>
</ul></li>
<li class="chapter" data-level="8.13" data-path="tidy.html"><a href="tidy.html#types-of-sales-within-student-bars"><i class="fa fa-check"></i><b>8.13</b> Types of sales within student bars</a></li>
<li class="chapter" data-level="8.14" data-path="tidy.html"><a href="tidy.html#how-gather-works"><i class="fa fa-check"></i><b>8.14</b> How gather() works</a></li>
<li class="chapter" data-level="8.15" data-path="tidy.html"><a href="tidy.html#applying-gather-to-beer-wine-and-liquor"><i class="fa fa-check"></i><b>8.15</b> Applying gather() to beer, wine and liquor</a>
<ul>
<li class="chapter" data-level="8.15.1" data-path="tidy.html"><a href="tidy.html#plot-sales-by-type-for-a-single-campus-area-bar"><i class="fa fa-check"></i><b>8.15.1</b> Plot sales by type for a single campus-area bar</a></li>
<li class="chapter" data-level="8.15.2" data-path="tidy.html"><a href="tidy.html#plot-sales-by-type-for-multiple-campus-area-bars"><i class="fa fa-check"></i><b>8.15.2</b> Plot sales by type for multiple campus-area bars</a></li>
<li class="chapter" data-level="8.15.3" data-path="tidy.html"><a href="tidy.html#what-did-we-learn"><i class="fa fa-check"></i><b>8.15.3</b> What did we learn?</a></li>
</ul></li>
<li class="chapter" data-level="8.16" data-path="tidy.html"><a href="tidy.html#the-spread-function"><i class="fa fa-check"></i><b>8.16</b> The spread() function</a></li>
<li class="chapter" data-level="8.17" data-path="tidy.html"><a href="tidy.html#practice-assignment-exploring-the-top-seller"><i class="fa fa-check"></i><b>8.17</b> Practice assignment: Exploring the top seller</a></li>
<li class="chapter" data-level="8.18" data-path="tidy.html"><a href="tidy.html#bonus-top-5-sellers-in-travis-county-over-three-years"><i class="fa fa-check"></i><b>8.18</b> Bonus: Top 5 sellers in Travis County over three years</a></li>
<li class="chapter" data-level="8.19" data-path="tidy.html"><a href="tidy.html#bonus-total-sales-by-county"><i class="fa fa-check"></i><b>8.19</b> Bonus: Total sales by county</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="review-plots.html"><a href="review-plots.html"><i class="fa fa-check"></i><b>9</b> Review: Plots</a>
<ul>
<li class="chapter" data-level="9.1" data-path="review-plots.html"><a href="review-plots.html#updates-needed-2"><i class="fa fa-check"></i><b>9.1</b> UPDATES NEEDED</a></li>
<li class="chapter" data-level="9.2" data-path="review-plots.html"><a href="review-plots.html#project-setup"><i class="fa fa-check"></i><b>9.2</b> Project setup</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="review-plots.html"><a href="review-plots.html#download-the-data"><i class="fa fa-check"></i><b>9.2.1</b> Download the data</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="review-plots.html"><a href="review-plots.html#the-story"><i class="fa fa-check"></i><b>9.3</b> The story</a></li>
<li class="chapter" data-level="9.4" data-path="review-plots.html"><a href="review-plots.html#explore-the-data"><i class="fa fa-check"></i><b>9.4</b> Explore the data</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="review-plots.html"><a href="review-plots.html#third-down-conversions"><i class="fa fa-check"></i><b>9.4.1</b> Third-down conversions</a></li>
<li class="chapter" data-level="9.4.2" data-path="review-plots.html"><a href="review-plots.html#scoring"><i class="fa fa-check"></i><b>9.4.2</b> Scoring</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="review-plots.html"><a href="review-plots.html#about-joins"><i class="fa fa-check"></i><b>9.5</b> About joins</a></li>
<li class="chapter" data-level="9.6" data-path="review-plots.html"><a href="review-plots.html#build-our-scatterplot"><i class="fa fa-check"></i><b>9.6</b> Build our scatterplot</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="review-plots.html"><a href="review-plots.html#add-a-fit-line"><i class="fa fa-check"></i><b>9.6.1</b> Add a fit line</a></li>
<li class="chapter" data-level="9.6.2" data-path="review-plots.html"><a href="review-plots.html#run-a-correlation-test"><i class="fa fa-check"></i><b>9.6.2</b> Run a correlation test</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="review-plots.html"><a href="review-plots.html#how-does-texas-compare"><i class="fa fa-check"></i><b>9.7</b> How does Texas compare?</a></li>
<li class="chapter" data-level="9.8" data-path="review-plots.html"><a href="review-plots.html#correlaton-test-for-texas"><i class="fa fa-check"></i><b>9.8</b> Correlaton test for Texas</a></li>
<li class="chapter" data-level="9.9" data-path="review-plots.html"><a href="review-plots.html#practice-1-compare-penn-state"><i class="fa fa-check"></i><b>9.9</b> Practice 1: Compare Penn State</a></li>
<li class="chapter" data-level="9.10" data-path="review-plots.html"><a href="review-plots.html#practice-2-penalties-vs-scoring"><i class="fa fa-check"></i><b>9.10</b> Practice 2: Penalties vs scoring</a></li>
<li class="chapter" data-level="9.11" data-path="review-plots.html"><a href="review-plots.html#using-bind_rows-to-merge-data-sets"><i class="fa fa-check"></i><b>9.11</b> Using bind_rows() to merge data sets</a>
<ul>
<li class="chapter" data-level="9.11.1" data-path="review-plots.html"><a href="review-plots.html#combine-data-with-a-group"><i class="fa fa-check"></i><b>9.11.1</b> Combine data with a group</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="reordering-factors.html"><a href="reordering-factors.html"><i class="fa fa-check"></i><b>10</b> Reordering factors</a>
<ul>
<li class="chapter" data-level="10.1" data-path="reordering-factors.html"><a href="reordering-factors.html#goals-for-this-section-2"><i class="fa fa-check"></i><b>10.1</b> Goals for this section</a></li>
<li class="chapter" data-level="10.2" data-path="reordering-factors.html"><a href="reordering-factors.html#create-our-survey-project"><i class="fa fa-check"></i><b>10.2</b> Create our survey project</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="reordering-factors.html"><a href="reordering-factors.html#setup"><i class="fa fa-check"></i><b>10.2.1</b> Setup</a></li>
<li class="chapter" data-level="10.2.2" data-path="reordering-factors.html"><a href="reordering-factors.html#libraries"><i class="fa fa-check"></i><b>10.2.2</b> Libraries</a></li>
<li class="chapter" data-level="10.2.3" data-path="reordering-factors.html"><a href="reordering-factors.html#import-the-data-1"><i class="fa fa-check"></i><b>10.2.3</b> Import the data</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="reordering-factors.html"><a href="reordering-factors.html#figuring-out-our-data-shape"><i class="fa fa-check"></i><b>10.3</b> Figuring out our data shape</a></li>
<li class="chapter" data-level="10.4" data-path="reordering-factors.html"><a href="reordering-factors.html#charting-the-popularity-of-princess"><i class="fa fa-check"></i><b>10.4</b> Charting the popularity of princess</a></li>
<li class="chapter" data-level="10.5" data-path="reordering-factors.html"><a href="reordering-factors.html#create-our-princess-plot"><i class="fa fa-check"></i><b>10.5</b> Create our princess plot</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="reordering-factors.html"><a href="reordering-factors.html#labels-and-titles"><i class="fa fa-check"></i><b>10.5.1</b> Labels and titles</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="reordering-factors.html"><a href="reordering-factors.html#factors"><i class="fa fa-check"></i><b>10.6</b> Factors</a></li>
<li class="chapter" data-level="10.7" data-path="reordering-factors.html"><a href="reordering-factors.html#reorder-princess"><i class="fa fa-check"></i><b>10.7</b> Reorder princess</a></li>
<li class="chapter" data-level="10.8" data-path="reordering-factors.html"><a href="reordering-factors.html#factors-recap"><i class="fa fa-check"></i><b>10.8</b> Factors recap</a></li>
<li class="chapter" data-level="10.9" data-path="reordering-factors.html"><a href="reordering-factors.html#practice-make-an-ice-cream-chart"><i class="fa fa-check"></i><b>10.9</b> Practice: Make an ice cream chart</a>
<ul>
<li class="chapter" data-level="10.9.1" data-path="reordering-factors.html"><a href="reordering-factors.html#turn-in-this-project"><i class="fa fa-check"></i><b>10.9.1</b> Turn in this project</a></li>
</ul></li>
<li class="chapter" data-level="10.10" data-path="reordering-factors.html"><a href="reordering-factors.html#resources-2"><i class="fa fa-check"></i><b>10.10</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="plotly.html"><a href="plotly.html"><i class="fa fa-check"></i><b>11</b> Plotly</a></li>
<li class="chapter" data-level="12" data-path="review---data-wrangling.html"><a href="review---data-wrangling.html"><i class="fa fa-check"></i><b>12</b> Review - Data wrangling</a>
<ul>
<li class="chapter" data-level="12.1" data-path="review---data-wrangling.html"><a href="review---data-wrangling.html#start-a-new-project"><i class="fa fa-check"></i><b>12.1</b> Start a new project</a></li>
<li class="chapter" data-level="12.2" data-path="review---data-wrangling.html"><a href="review---data-wrangling.html#downloading-our-data"><i class="fa fa-check"></i><b>12.2</b> Downloading our data</a></li>
<li class="chapter" data-level="12.3" data-path="review---data-wrangling.html"><a href="review---data-wrangling.html#importing-from-an-excel-spreadsheet"><i class="fa fa-check"></i><b>12.3</b> Importing from an Excel spreadsheet</a></li>
<li class="chapter" data-level="12.4" data-path="review---data-wrangling.html"><a href="review---data-wrangling.html#a-quick-look-at-our-data"><i class="fa fa-check"></i><b>12.4</b> A quick look at our data</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="cleaning.html"><a href="cleaning.html"><i class="fa fa-check"></i><b>13</b> Cleaning</a>
<ul>
<li class="chapter" data-level="13.1" data-path="cleaning.html"><a href="cleaning.html#not-finished-needs-rewrite"><i class="fa fa-check"></i><b>13.1</b> NOT FINISHED, NEEDS REWRITE</a></li>
<li class="chapter" data-level="13.2" data-path="cleaning.html"><a href="cleaning.html#goals-for-this-section-3"><i class="fa fa-check"></i><b>13.2</b> Goals for this section</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="cleaning.html"><a href="cleaning.html#resources-3"><i class="fa fa-check"></i><b>13.2.1</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="cleaning.html"><a href="cleaning.html#explain-thyself"><i class="fa fa-check"></i><b>13.3</b> Explain thyself</a></li>
<li class="chapter" data-level="13.4" data-path="cleaning.html"><a href="cleaning.html#syntax-etiquette"><i class="fa fa-check"></i><b>13.4</b> Syntax etiquette</a></li>
<li class="chapter" data-level="13.5" data-path="cleaning.html"><a href="cleaning.html#recode-the-apd_race-column"><i class="fa fa-check"></i><b>13.5</b> Recode the <code>apd_race</code> column</a></li>
<li class="chapter" data-level="13.6" data-path="cleaning.html"><a href="cleaning.html#filter-out-data-we-dont-need"><i class="fa fa-check"></i><b>13.6</b> Filter out data we don’t need</a>
<ul>
<li class="chapter" data-level="13.6.1" data-path="cleaning.html"><a href="cleaning.html#about-marijuana-charges"><i class="fa fa-check"></i><b>13.6.1</b> About marijuana charges</a></li>
<li class="chapter" data-level="13.6.2" data-path="cleaning.html"><a href="cleaning.html#filter-out-delivery-charges"><i class="fa fa-check"></i><b>13.6.2</b> Filter out delivery charges</a></li>
<li class="chapter" data-level="13.6.3" data-path="cleaning.html"><a href="cleaning.html#remove-controlled-substance"><i class="fa fa-check"></i><b>13.6.3</b> Remove controlled substance</a></li>
<li class="chapter" data-level="13.6.4" data-path="cleaning.html"><a href="cleaning.html#remove-drug-free-zones"><i class="fa fa-check"></i><b>13.6.4</b> Remove drug free zones</a></li>
<li class="chapter" data-level="13.6.5" data-path="cleaning.html"><a href="cleaning.html#remove-request-to-apprehend"><i class="fa fa-check"></i><b>13.6.5</b> Remove request to apprehend</a></li>
<li class="chapter" data-level="13.6.6" data-path="cleaning.html"><a href="cleaning.html#removing-more-unwated-records"><i class="fa fa-check"></i><b>13.6.6</b> Removing more unwated records</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="cleaning.html"><a href="cleaning.html#finding-just-b-misdemeanors"><i class="fa fa-check"></i><b>13.7</b> Finding just B misdemeanors</a></li>
<li class="chapter" data-level="13.8" data-path="cleaning.html"><a href="cleaning.html#export-your-updated-data-frame"><i class="fa fa-check"></i><b>13.8</b> Export your updated data frame</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="sped-import.html"><a href="sped-import.html"><i class="fa fa-check"></i><b>14</b> SPED Joins</a>
<ul>
<li class="chapter" data-level="14.1" data-path="sped-import.html"><a href="sped-import.html#goals-for-this-section-4"><i class="fa fa-check"></i><b>14.1</b> Goals for this section</a></li>
<li class="chapter" data-level="14.2" data-path="sped-import.html"><a href="sped-import.html#our-project-data-1"><i class="fa fa-check"></i><b>14.2</b> Our project data</a></li>
<li class="chapter" data-level="14.3" data-path="sped-import.html"><a href="sped-import.html#about-data-sources-1"><i class="fa fa-check"></i><b>14.3</b> About data sources</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="sped-import.html"><a href="sped-import.html#what-is-clean-data-1"><i class="fa fa-check"></i><b>14.3.1</b> What is clean data</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="sped-import.html"><a href="sped-import.html#create-a-new-project-1"><i class="fa fa-check"></i><b>14.4</b> Create a new project</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="sped-import.html"><a href="sped-import.html#the-r-package-environment-1"><i class="fa fa-check"></i><b>14.4.1</b> The R Package environment</a></li>
<li class="chapter" data-level="14.4.2" data-path="sped-import.html"><a href="sped-import.html#installing-and-using-packages-1"><i class="fa fa-check"></i><b>14.4.2</b> Installing and using packages</a></li>
<li class="chapter" data-level="14.4.3" data-path="sped-import.html"><a href="sped-import.html#load-the-libraries-1"><i class="fa fa-check"></i><b>14.4.3</b> Load the libraries</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="sped-import.html"><a href="sped-import.html#downloading-raw-data"><i class="fa fa-check"></i><b>14.5</b> Downloading raw data</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="sped-import.html"><a href="sped-import.html#create-a-directory-for-your-data-1"><i class="fa fa-check"></i><b>14.5.1</b> Create a directory for your data</a></li>
<li class="chapter" data-level="14.5.2" data-path="sped-import.html"><a href="sped-import.html#lets-get-some-data"><i class="fa fa-check"></i><b>14.5.2</b> Let’s get some data</a></li>
<li class="chapter" data-level="14.5.3" data-path="sped-import.html"><a href="sped-import.html#peek-at-the-data-file"><i class="fa fa-check"></i><b>14.5.3</b> Peek at the data file</a></li>
<li class="chapter" data-level="14.5.4" data-path="sped-import.html"><a href="sped-import.html#import-csv-as-data"><i class="fa fa-check"></i><b>14.5.4</b> Import csv as data</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="sped-import.html"><a href="sped-import.html#assign-our-import-to-a-data-frame"><i class="fa fa-check"></i><b>14.6</b> Assign our import to a data frame</a>
<ul>
<li class="chapter" data-level="14.6.1" data-path="sped-import.html"><a href="sped-import.html#print-a-peek-to-the-screen-1"><i class="fa fa-check"></i><b>14.6.1</b> Print a peek to the screen</a></li>
<li class="chapter" data-level="14.6.2" data-path="sped-import.html"><a href="sped-import.html#glimpse-the-data-1"><i class="fa fa-check"></i><b>14.6.2</b> Glimpse the data</a></li>
<li class="chapter" data-level="14.6.3" data-path="sped-import.html"><a href="sped-import.html#about-the-pipe-1"><i class="fa fa-check"></i><b>14.6.3</b> About the pipe %&gt;%</a></li>
<li class="chapter" data-level="14.6.4" data-path="sped-import.html"><a href="sped-import.html#creating-consistent-column-names"><i class="fa fa-check"></i><b>14.6.4</b> Creating consistent column names</a></li>
<li class="chapter" data-level="14.6.5" data-path="sped-import.html"><a href="sped-import.html#import-other-data-frames"><i class="fa fa-check"></i><b>14.6.5</b> Import other data frames</a></li>
</ul></li>
<li class="chapter" data-level="14.7" data-path="sped-import.html"><a href="sped-import.html#prepare-data-for-joining"><i class="fa fa-check"></i><b>14.7</b> Prepare data for joining</a>
<ul>
<li class="chapter" data-level="14.7.1" data-path="sped-import.html"><a href="sped-import.html#prepare-the-directory-data"><i class="fa fa-check"></i><b>14.7.1</b> Prepare the directory data</a></li>
<li class="chapter" data-level="14.7.2" data-path="sped-import.html"><a href="sped-import.html#prepare-cstud-data"><i class="fa fa-check"></i><b>14.7.2</b> Prepare CSTUD data</a></li>
</ul></li>
<li class="chapter" data-level="14.8" data-path="sped-import.html"><a href="sped-import.html#joining-the-data-together"><i class="fa fa-check"></i><b>14.8</b> Joining the data together</a></li>
<li class="chapter" data-level="14.9" data-path="sped-import.html"><a href="sped-import.html#exporting-data-1"><i class="fa fa-check"></i><b>14.9</b> Exporting data</a>
<ul>
<li class="chapter" data-level="14.9.1" data-path="sped-import.html"><a href="sped-import.html#single-notebook-philosophy-1"><i class="fa fa-check"></i><b>14.9.1</b> Single-notebook philosophy</a></li>
<li class="chapter" data-level="14.9.2" data-path="sped-import.html"><a href="sped-import.html#exporting-as-rds-1"><i class="fa fa-check"></i><b>14.9.2</b> Exporting as rds</a></li>
</ul></li>
<li class="chapter" data-level="14.10" data-path="sped-import.html"><a href="sped-import.html#review-of-what-weve-learned-so-far-1"><i class="fa fa-check"></i><b>14.10</b> Review of what we’ve learned so far</a></li>
<li class="chapter" data-level="14.11" data-path="sped-import.html"><a href="sped-import.html#resources-4"><i class="fa fa-check"></i><b>14.11</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="sped-transform.html"><a href="sped-transform.html"><i class="fa fa-check"></i><b>15</b> Transform</a>
<ul>
<li class="chapter" data-level="15.1" data-path="sped-transform.html"><a href="sped-transform.html#rewite-tasks"><i class="fa fa-check"></i><b>15.1</b> Rewite tasks</a></li>
<li class="chapter" data-level="15.2" data-path="sped-transform.html"><a href="sped-transform.html#goals-for-the-section"><i class="fa fa-check"></i><b>15.2</b> Goals for the section</a></li>
<li class="chapter" data-level="15.3" data-path="sped-transform.html"><a href="sped-transform.html#introducing-dplyr-1"><i class="fa fa-check"></i><b>15.3</b> Introducing dplyr</a></li>
<li class="chapter" data-level="15.4" data-path="sped-transform.html"><a href="sped-transform.html#start-a-new-r-notebook"><i class="fa fa-check"></i><b>15.4</b> Start a new R Notebook</a></li>
<li class="chapter" data-level="15.5" data-path="sped-transform.html"><a href="sped-transform.html#record-our-goals"><i class="fa fa-check"></i><b>15.5</b> Record our goals</a></li>
<li class="chapter" data-level="15.6" data-path="sped-transform.html"><a href="sped-transform.html#setup-1"><i class="fa fa-check"></i><b>15.6</b> Setup</a>
<ul>
<li class="chapter" data-level="15.6.1" data-path="sped-transform.html"><a href="sped-transform.html#naming-our-chunks"><i class="fa fa-check"></i><b>15.6.1</b> Naming our chunks</a></li>
</ul></li>
<li class="chapter" data-level="15.7" data-path="sped-transform.html"><a href="sped-transform.html#import-our-data"><i class="fa fa-check"></i><b>15.7</b> Import our data</a></li>
<li class="chapter" data-level="15.8" data-path="sped-transform.html"><a href="sped-transform.html#explore-instruction-type"><i class="fa fa-check"></i><b>15.8</b> Explore instruction type</a></li>
<li class="chapter" data-level="15.9" data-path="sped-transform.html"><a href="sped-transform.html#filter-1"><i class="fa fa-check"></i><b>15.9</b> Filter()</a>
<ul>
<li class="chapter" data-level="15.9.1" data-path="sped-transform.html"><a href="sped-transform.html#filter-for-regular-instructional-schools"><i class="fa fa-check"></i><b>15.9.1</b> Filter for Regular Instructional schools</a></li>
<li class="chapter" data-level="15.9.2" data-path="sped-transform.html"><a href="sped-transform.html#logical-tests"><i class="fa fa-check"></i><b>15.9.2</b> Logical tests</a></li>
<li class="chapter" data-level="15.9.3" data-path="sped-transform.html"><a href="sped-transform.html#common-mistakes-with-filter"><i class="fa fa-check"></i><b>15.9.3</b> Common mistakes with filter</a></li>
</ul></li>
<li class="chapter" data-level="15.10" data-path="sped-transform.html"><a href="sped-transform.html#combining-filters"><i class="fa fa-check"></i><b>15.10</b> Combining filters</a>
<ul>
<li class="chapter" data-level="15.10.1" data-path="sped-transform.html"><a href="sped-transform.html#common-mistakes-with-combining-filters"><i class="fa fa-check"></i><b>15.10.1</b> Common mistakes with combining filters</a></li>
</ul></li>
<li class="chapter" data-level="15.11" data-path="sped-transform.html"><a href="sped-transform.html#select"><i class="fa fa-check"></i><b>15.11</b> Select()</a></li>
<li class="chapter" data-level="15.12" data-path="sped-transform.html"><a href="sped-transform.html#how-to-describe-the-change"><i class="fa fa-check"></i><b>15.12</b> How to describe the change</a>
<ul>
<li class="chapter" data-level="15.12.1" data-path="sped-transform.html"><a href="sped-transform.html#describing-the-count-changes"><i class="fa fa-check"></i><b>15.12.1</b> Describing the count changes</a></li>
<li class="chapter" data-level="15.12.2" data-path="sped-transform.html"><a href="sped-transform.html#describing-percentage-differences"><i class="fa fa-check"></i><b>15.12.2</b> Describing percentage differences</a></li>
</ul></li>
<li class="chapter" data-level="15.13" data-path="sped-transform.html"><a href="sped-transform.html#mutate"><i class="fa fa-check"></i><b>15.13</b> Mutate()</a>
<ul>
<li class="chapter" data-level="15.13.1" data-path="sped-transform.html"><a href="sped-transform.html#simple-change-of-counts"><i class="fa fa-check"></i><b>15.13.1</b> Simple change of counts</a></li>
<li class="chapter" data-level="15.13.2" data-path="sped-transform.html"><a href="sped-transform.html#calculate-percent-change"><i class="fa fa-check"></i><b>15.13.2</b> Calculate percent change</a></li>
<li class="chapter" data-level="15.13.3" data-path="sped-transform.html"><a href="sped-transform.html#calculate-percentage-point-difference"><i class="fa fa-check"></i><b>15.13.3</b> Calculate percentage point difference</a></li>
<li class="chapter" data-level="15.13.4" data-path="sped-transform.html"><a href="sped-transform.html#calculating-our-special-education-threshold"><i class="fa fa-check"></i><b>15.13.4</b> Calculating our special education threshold</a></li>
</ul></li>
<li class="chapter" data-level="15.14" data-path="sped-transform.html"><a href="sped-transform.html#export-your-computations"><i class="fa fa-check"></i><b>15.14</b> Export your computations</a></li>
<li class="chapter" data-level="15.15" data-path="sped-transform.html"><a href="sped-transform.html#more-dplyr-in-next-lesson"><i class="fa fa-check"></i><b>15.15</b> More dplyr in next lesson</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="sped-summarize.html"><a href="sped-summarize.html"><i class="fa fa-check"></i><b>16</b> Summarize</a>
<ul>
<li class="chapter" data-level="16.1" data-path="sped-summarize.html"><a href="sped-summarize.html#new-task-new-notebook"><i class="fa fa-check"></i><b>16.1</b> New task, new notebook</a>
<ul>
<li class="chapter" data-level="16.1.1" data-path="sped-summarize.html"><a href="sped-summarize.html#create-analysis-notebook"><i class="fa fa-check"></i><b>16.1.1</b> Create analysis notebook</a></li>
<li class="chapter" data-level="16.1.2" data-path="sped-summarize.html"><a href="sped-summarize.html#import-1"><i class="fa fa-check"></i><b>16.1.2</b> Import</a></li>
<li class="chapter" data-level="16.1.3" data-path="sped-summarize.html"><a href="sped-summarize.html#filter-to-austin-isd"><i class="fa fa-check"></i><b>16.1.3</b> Filter to Austin ISD</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="sped-summarize.html"><a href="sped-summarize.html#sorting-with-arrange"><i class="fa fa-check"></i><b>16.2</b> Sorting with arrange()</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="sped-summarize.html"><a href="sped-summarize.html#about-arrange"><i class="fa fa-check"></i><b>16.2.1</b> About arrange</a></li>
<li class="chapter" data-level="16.2.2" data-path="sped-summarize.html"><a href="sped-summarize.html#most-new-special-education-students"><i class="fa fa-check"></i><b>16.2.2</b> Most new special education students</a></li>
<li class="chapter" data-level="16.2.3" data-path="sped-summarize.html"><a href="sped-summarize.html#the-head-command"><i class="fa fa-check"></i><b>16.2.3</b> The head() command</a></li>
<li class="chapter" data-level="16.2.4" data-path="sped-summarize.html"><a href="sped-summarize.html#highest-share-of-special-education-students-in-2020"><i class="fa fa-check"></i><b>16.2.4</b> Highest share of special education students in 2020</a></li>
<li class="chapter" data-level="16.2.5" data-path="sped-summarize.html"><a href="sped-summarize.html#greatest-change-in-share-of-special-education-students"><i class="fa fa-check"></i><b>16.2.5</b> Greatest change in share of special education students</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="sped-summarize.html"><a href="sped-summarize.html#aggregates-with-summarize"><i class="fa fa-check"></i><b>16.3</b> Aggregates with summarize()</a></li>
<li class="chapter" data-level="16.4" data-path="sped-summarize.html"><a href="sped-summarize.html#group_by"><i class="fa fa-check"></i><b>16.4</b> Group_by()</a>
<ul>
<li class="chapter" data-level="16.4.1" data-path="sped-summarize.html"><a href="sped-summarize.html#group-and-count"><i class="fa fa-check"></i><b>16.4.1</b> Group and count</a></li>
<li class="chapter" data-level="16.4.2" data-path="sped-summarize.html"><a href="sped-summarize.html#the-count-function-shortcut"><i class="fa fa-check"></i><b>16.4.2</b> The count() function shortcut</a></li>
<li class="chapter" data-level="16.4.3" data-path="sped-summarize.html"><a href="sped-summarize.html#comparing-thresholds-for-2015-and-2020"><i class="fa fa-check"></i><b>16.4.3</b> Comparing thresholds for 2015 and 2020</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="sped-summarize.html"><a href="sped-summarize.html#more-on-summarize"><i class="fa fa-check"></i><b>16.5</b> More on summarize</a>
<ul>
<li class="chapter" data-level="16.5.1" data-path="sped-summarize.html"><a href="sped-summarize.html#ignoring-na-values"><i class="fa fa-check"></i><b>16.5.1</b> Ignoring NA values</a></li>
</ul></li>
<li class="chapter" data-level="16.6" data-path="sped-summarize.html"><a href="sped-summarize.html#review-what-we-learned"><i class="fa fa-check"></i><b>16.6</b> Review what we learned</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html"><i class="fa fa-check"></i><b>17</b> How to tackle a new dataset</a>
<ul>
<li class="chapter" data-level="17.1" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#needs-review"><i class="fa fa-check"></i><b>17.1</b> NEEDS REVIEW</a></li>
<li class="chapter" data-level="17.2" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#start-by-listing-questions"><i class="fa fa-check"></i><b>17.2</b> Start by listing questions</a></li>
<li class="chapter" data-level="17.3" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#understand-your-data"><i class="fa fa-check"></i><b>17.3</b> Understand your data</a></li>
<li class="chapter" data-level="17.4" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#counting-and-aggregation"><i class="fa fa-check"></i><b>17.4</b> Counting and aggregation</a>
<ul>
<li class="chapter" data-level="17.4.1" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#counting-rows-based-on-a-column"><i class="fa fa-check"></i><b>17.4.1</b> Counting rows based on a column</a></li>
<li class="chapter" data-level="17.4.2" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#sum-mean-and-other-aggregations"><i class="fa fa-check"></i><b>17.4.2</b> Sum, mean and other aggregations</a></li>
<li class="chapter" data-level="17.4.3" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#creating-columns-to-show-difference"><i class="fa fa-check"></i><b>17.4.3</b> Creating columns to show difference</a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#cleaning-up-categorical-data"><i class="fa fa-check"></i><b>17.5</b> Cleaning up categorical data</a></li>
<li class="chapter" data-level="17.6" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#time-as-a-variable"><i class="fa fa-check"></i><b>17.6</b> Time as a variable</a></li>
<li class="chapter" data-level="17.7" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#explore-the-distributions-in-your-data"><i class="fa fa-check"></i><b>17.7</b> Explore the distributions in your data</a>
<ul>
<li class="chapter" data-level="17.7.1" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#more-on-histograms"><i class="fa fa-check"></i><b>17.7.1</b> More on histograms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="verbs.html"><a href="verbs.html"><i class="fa fa-check"></i><b>18</b> Verbs</a>
<ul>
<li class="chapter" data-level="18.1" data-path="verbs.html"><a href="verbs.html#needs-review-1"><i class="fa fa-check"></i><b>18.1</b> NEEDS REVIEW</a></li>
<li class="chapter" data-level="18.2" data-path="verbs.html"><a href="verbs.html#importexport"><i class="fa fa-check"></i><b>18.2</b> Import/Export</a></li>
<li class="chapter" data-level="18.3" data-path="verbs.html"><a href="verbs.html#data-manipulation"><i class="fa fa-check"></i><b>18.3</b> Data manipulation</a></li>
<li class="chapter" data-level="18.4" data-path="verbs.html"><a href="verbs.html#aggregation"><i class="fa fa-check"></i><b>18.4</b> Aggregation</a></li>
<li class="chapter" data-level="18.5" data-path="verbs.html"><a href="verbs.html#math"><i class="fa fa-check"></i><b>18.5</b> Math</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="chart-examples.html"><a href="chart-examples.html"><i class="fa fa-check"></i><b>19</b> Chart examples</a>
<ul>
<li class="chapter" data-level="19.1" data-path="chart-examples.html"><a href="chart-examples.html#needs-review-2"><i class="fa fa-check"></i><b>19.1</b> NEEDS REVIEW</a></li>
<li class="chapter" data-level="19.2" data-path="chart-examples.html"><a href="chart-examples.html#bar-charts"><i class="fa fa-check"></i><b>19.2</b> Bar charts</a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="chart-examples.html"><a href="chart-examples.html#explanaton"><i class="fa fa-check"></i><b>19.2.1</b> Explanaton</a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="chart-examples.html"><a href="chart-examples.html#column-chart"><i class="fa fa-check"></i><b>19.3</b> Column chart</a></li>
<li class="chapter" data-level="19.4" data-path="chart-examples.html"><a href="chart-examples.html#a-line-chart"><i class="fa fa-check"></i><b>19.4</b> A line chart</a>
<ul>
<li class="chapter" data-level="19.4.1" data-path="chart-examples.html"><a href="chart-examples.html#explanation"><i class="fa fa-check"></i><b>19.4.1</b> Explanation</a></li>
</ul></li>
<li class="chapter" data-level="19.5" data-path="chart-examples.html"><a href="chart-examples.html#scatterplot-1"><i class="fa fa-check"></i><b>19.5</b> Scatterplot</a>
<ul>
<li class="chapter" data-level="19.5.1" data-path="chart-examples.html"><a href="chart-examples.html#explanation-1"><i class="fa fa-check"></i><b>19.5.1</b> Explanation</a></li>
</ul></li>
<li class="chapter" data-level="19.6" data-path="chart-examples.html"><a href="chart-examples.html#histogram"><i class="fa fa-check"></i><b>19.6</b> Histogram</a></li>
<li class="chapter" data-level="19.7" data-path="chart-examples.html"><a href="chart-examples.html#titles-labels-and-other-cleanup"><i class="fa fa-check"></i><b>19.7</b> Titles, labels and other cleanup</a>
<ul>
<li class="chapter" data-level="19.7.1" data-path="chart-examples.html"><a href="chart-examples.html#title-and-axis-labels"><i class="fa fa-check"></i><b>19.7.1</b> Title and axis labels</a></li>
<li class="chapter" data-level="19.7.2" data-path="chart-examples.html"><a href="chart-examples.html#flip-the-graphic"><i class="fa fa-check"></i><b>19.7.2</b> Flip the graphic</a></li>
<li class="chapter" data-level="19.7.3" data-path="chart-examples.html"><a href="chart-examples.html#fix-exponential-numbers-on-an-axis"><i class="fa fa-check"></i><b>19.7.3</b> Fix exponential numbers on an axis</a></li>
</ul></li>
<li class="chapter" data-level="19.8" data-path="chart-examples.html"><a href="chart-examples.html#interactivity-with-plotly"><i class="fa fa-check"></i><b>19.8</b> Interactivity with plotly</a></li>
<li class="chapter" data-level="19.9" data-path="chart-examples.html"><a href="chart-examples.html#resources-5"><i class="fa fa-check"></i><b>19.9</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="publishing-your-findings.html"><a href="publishing-your-findings.html"><i class="fa fa-check"></i><b>20</b> Publishing your findings</a>
<ul>
<li class="chapter" data-level="20.1" data-path="publishing-your-findings.html"><a href="publishing-your-findings.html#needs-review-3"><i class="fa fa-check"></i><b>20.1</b> NEEDS REVIEW</a></li>
<li class="chapter" data-level="20.2" data-path="publishing-your-findings.html"><a href="publishing-your-findings.html#examples"><i class="fa fa-check"></i><b>20.2</b> Examples</a></li>
<li class="chapter" data-level="20.3" data-path="publishing-your-findings.html"><a href="publishing-your-findings.html#how-to-publish-your-projects"><i class="fa fa-check"></i><b>20.3</b> How to publish your projects</a>
<ul>
<li class="chapter" data-level="20.3.1" data-path="publishing-your-findings.html"><a href="publishing-your-findings.html#using-github-pages"><i class="fa fa-check"></i><b>20.3.1</b> Using Github Pages</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="publishing-your-findings.html"><a href="publishing-your-findings.html#making-branded-graphics"><i class="fa fa-check"></i><b>20.4</b> Making branded graphics</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Reporting with Data in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="sped-transform" class="section level1" number="15">
<h1><span class="header-section-number">Chapter 15</span> Transform</h1>
<blockquote>
<p>MID-UPDATE v1.0</p>
</blockquote>
<div id="rewite-tasks" class="section level2" number="15.1">
<h2><span class="header-section-number">15.1</span> Rewite tasks</h2>
<ul>
<li>Return to fill in story gaps</li>
<li>fix lists</li>
</ul>
<hr />
</div>
<div id="goals-for-the-section" class="section level2" number="15.2">
<h2><span class="header-section-number">15.2</span> Goals for the section</h2>
<p>In this lesson we will continue with the Special Education project you began in the last chapter. Our goals are:</p>
<ul>
<li>To build good data journalism and programming practices.</li>
<li>Use the <a href="https://dplyr.tidyverse.org/">dplyr</a> tools to select, filter, sort and create new columns of data with mutate. You might <a href="https://dplyr.tidyverse.org/articles/dplyr.html">read this article</a> to get an idea.</li>
</ul>
</div>
<div id="introducing-dplyr-1" class="section level2" number="15.3">
<h2><span class="header-section-number">15.3</span> Introducing dplyr</h2>
<p>One of the packages within the tidyverse is <a href="https://dplyr.tidyverse.org/">dplyr</a>. Dplyr allows us to transform our data frames in ways that let us explore the data and prepare it for visualizing. It’s the R equivalent of common Excel functions like sort, filter and pivoting.</p>
<blockquote>
<p>There is a cheatsheet on the <a href="https://dplyr.tidyverse.org/">dplyr</a> that you might find useful.</p>
</blockquote>
<div class="figure">
<img src="images/transform-dplyractions.png" width="500" alt="" />
<p class="caption">Common dplyr functions</p>
</div>
<p>(Some slides/images included here are used with permission from Hadley and Charlotte Wickham.)</p>
</div>
<div id="start-a-new-r-notebook" class="section level2" number="15.4">
<h2><span class="header-section-number">15.4</span> Start a new R Notebook</h2>
<p>As I explained at the end of our last lesson, it’s a good practice to separate your downloading/import code from your other notebooks. We are creating a new notebook to handle all our computations, too, in case we want to do different analysis in different notebooks going forward.</p>
<ul>
<li>Open your special-ed project if you haven’t already.</li>
<li>Make sure the <code>01-import.Rmd</code> file is closed.</li>
<li>Under the <strong>Session</strong> menu in RStudio, choose <em>Restart R</em>. This cleans our environment so we don’t have left-over objects from our previous session, though you still might see history in your Console.</li>
<li>Create a new R Notebook and set a new title of “Special education computations.”</li>
<li>Remove the boilerplate language and add a description of our goals: To explore an analyze our school ratings data. Mention that you have to run the other notebook first in case your someone else (or your future self) comes here first.</li>
<li>Save your file as <code>02-computations.Rmd</code>.</li>
</ul>
</div>
<div id="record-our-goals" class="section level2" number="15.5">
<h2><span class="header-section-number">15.5</span> Record our goals</h2>
<p>One thing I like to do at the top of a notebook is outline what is I’m trying to do.
What do we want to learn about these school ratings?</p>
<ul>
<li>Add a Markdown headline <code>## Goals</code>.</li>
<li>Create a bullet list of things you might want to find. Use a <code>*</code> or <code>-</code> to start each new line.</li>
</ul>
<pre class="text"><code>- Which campus gained the most (count difference) special education students from 2015 to 2020?
- Which campus has the highest share (percent) of special education students in 2020?
- Which campus had the greatest change in share of in special education students between 2015 and 2020.
- How many AISD schools would be above the special education &quot;audit threshold&quot; of 8.5% in 2020 if it were still in effect? How does those numbers compare to 2015?

We will filter our list to focus on &quot;Regular Instructional&quot; schools to exclude alternative, disciplinary or schools part of the justice system.</code></pre>
<p>We will filter our list to focus on “Regular Instructional” schools to exclude alternative, disciplinary or schools part of the justice system.</p>
</div>
<div id="setup-1" class="section level2" number="15.6">
<h2><span class="header-section-number">15.6</span> Setup</h2>
<p>The first code chunk in every notebook should be a listing of all the packages used. We put them at the top so users can see if they need to install the packages. For now, we need the tidyverse and janitor packages (which I include in every notebook).</p>
<ul>
<li>Create a new Markdown headline <code>## Import</code></li>
<li>Add a new code chunk (<strong>Cmd-Shift+i</strong>!)</li>
<li>Add the tidyverse and janitor libraries</li>
<li>Run the chunk</li>
</ul>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="sped-transform.html#cb241-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb241-2"><a href="sped-transform.html#cb241-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code></pre></div>
<div id="naming-our-chunks" class="section level3" number="15.6.1">
<h3><span class="header-section-number">15.6.1</span> Naming our chunks</h3>
<p>It is good practice to name your chunks of code to make it easier to navigate throughout your R notebook. Let’s do this with our setup chunk.</p>
<ul>
<li>In your setup chunk, change <code>{r}</code> to <code>{r setup}</code>:</li>
</ul>
<pre class="text"><code>{r setup}
library(tidyverse)</code></pre>
<p>(You have to imagine the three tickmarks that begin/end the code chunk above. I can’t display those in the instructions.)</p>
<p>You can’t have multi-word names. You must use a <code>-</code> or <code>_</code>, like <code>multi-word</code>.</p>
<p>By doing this, you can then use the notebook navigation to move to different parts of your RNotebook.</p>
<div class="figure">
<img src="images/transform-navigate.png" width="400" alt="" />
<p class="caption">R Notebook navigation</p>
</div>
<blockquote>
<p>The <code>{r}</code> part of a chunk can take a number of options in addition to a name, controlling what is displayed or knitted to your final report. We aren’t going to get into it now, but you might see it in other notebooks or my code.</p>
</blockquote>
</div>
</div>
<div id="import-our-data" class="section level2" number="15.7">
<h2><span class="header-section-number">15.7</span> Import our data</h2>
<ul>
<li>Add a Markdown headline and description that you are loading the data.</li>
<li>Add a code chunk and give it a name of <strong>import</strong>. Add the code below and then run the chunk:</li>
</ul>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="sped-transform.html#cb243-1" aria-hidden="true" tabindex="-1"></a>sped <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">&quot;data-processed/01_sped.rds&quot;</span>)</span>
<span id="cb243-2"><a href="sped-transform.html#cb243-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb243-3"><a href="sped-transform.html#cb243-3" aria-hidden="true" tabindex="-1"></a>sped <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 8,002
## Columns: 10
## $ school_name      &lt;chr&gt; &quot;CAYUGA H S&quot;, &quot;CAYUGA MIDDLE&quot;, &quot;CAYUGA EL&quot;, &quot;ELKHART …
## $ district_name    &lt;chr&gt; &quot;CAYUGA ISD&quot;, &quot;CAYUGA ISD&quot;, &quot;CAYUGA ISD&quot;, &quot;ELKHART IS…
## $ instruction_type &lt;chr&gt; &quot;REGULAR INSTRUCTIONAL&quot;, &quot;REGULAR INSTRUCTIONAL&quot;, &quot;RE…
## $ charter_type     &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
## $ grade_range      &lt;chr&gt; &quot;&#39;09-12&quot;, &quot;&#39;06-08&quot;, &quot;&#39;EE-05&quot;, &quot;&#39;09-12&quot;, &quot;&#39;06-08&quot;, &quot;&#39;E…
## $ campus           &lt;chr&gt; &quot;001902001&quot;, &quot;001902041&quot;, &quot;001902103&quot;, &quot;001903001&quot;, &quot;…
## $ sped_c_15        &lt;dbl&gt; 37, 16, 23, 33, 36, 29, 27, 28, 16, 34, 16, 25, 96, 4…
## $ sped_p_15        &lt;dbl&gt; 18.0, 13.3, 9.2, 9.3, 11.8, 9.6, 10.5, 12.6, 9.2, 8.4…
## $ sped_c_20        &lt;dbl&gt; 34, 17, 31, 44, 29, 48, 26, 19, 28, 44, 11, 14, 103, …
## $ sped_p_20        &lt;dbl&gt; 19.8, 13.6, 11.9, 11.6, 11.2, 14.4, 9.4, 8.3, 15.9, 1…</code></pre>
<p>What we’ve done is import the data we processed at the end of our <strong>01-import.Rmd</strong> notebook and assigned it to a data frame called <code>sped</code> and glimpsed it for reference.</p>
<p>We are now back to where we ended with the first notebook.</p>
</div>
<div id="explore-instruction-type" class="section level2" number="15.8">
<h2><span class="header-section-number">15.8</span> Explore instruction type</h2>
<p>Our first task is to filter our data to remove any schools not rated by normal standards, like disciplinary schools and the like. Before we do this, we’ll do a quick exploration of the data available in the <code>instruction_type</code> field using <code>count()</code>. This is a “summarize” concept that we’ll cover more in the next chapter, but it is super useful so we’ll touch on it here.</p>
<ul>
<li>Create a Markdown section with a headline and text that you are exploring instruction_type.</li>
<li>Add a code chunk and name it “explore-type.”</li>
<li>Add this code and run it, then I’ll explain it.</li>
</ul>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="sped-transform.html#cb245-1" aria-hidden="true" tabindex="-1"></a>sped <span class="sc">%&gt;%</span> </span>
<span id="cb245-2"><a href="sped-transform.html#cb245-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(instruction_type)</span></code></pre></div>
<pre><code>## # A tibble: 4 × 2
##   instruction_type              n
##   &lt;chr&gt;                     &lt;int&gt;
## 1 ALTERNATIVE INSTRUCTIONAL   397
## 2 DAEP INSTRUCTIONAL          121
## 3 JJAEP INSTRUCTIONAL         112
## 4 REGULAR INSTRUCTIONAL      7372</code></pre>
<p>What you’ve done here is very similar to a pivot table in Excel where you count the rows based on values.</p>
<ul>
<li>We start with the data frame</li>
<li>We pipe into the function <code>count()</code></li>
<li>We feed count the column name where we want to count the records by value.</li>
</ul>
<p>The <code>n</code> column is the number of rows. We’ll talk more about <code>count()</code> and other summary functions in the next chapter. It is super useful to peek at your data and use it to check filters and such.</p>
</div>
<div id="filter-1" class="section level2" number="15.9">
<h2><span class="header-section-number">15.9</span> Filter()</h2>
<p>We can use dplyr’s <code>filter()</code> function to capture a subset of the data, like our “REGULAR INSTRUCTIONAL” schools. It works like this:</p>
<div class="figure">
<img src="images/transform-filter.png" width="500" alt="" />
<p class="caption">dplyr filter function</p>
</div>
<blockquote>
<p>IMPORTANT: When you see a slide like the one above, please note that <code>.data</code> might be the data that you have piped <code>%&gt;%</code> into the function. In fact, it usually is.</p>
</blockquote>
<p>Let’s put this into practice.</p>
<div id="filter-for-regular-instructional-schools" class="section level3" number="15.9.1">
<h3><span class="header-section-number">15.9.1</span> Filter for Regular Instructional schools</h3>
<p>From or count we know there are four types of schools: ALTERNATIVE INSTRUCTIONAL, DAEP INSTRUCTIONAL, JJAEP INSTRUCTIONAL and REGULAR INSTRUCTIONAL. Now that we know what the “regular” schools are called, we can build a filter to find them.</p>
<ul>
<li>Add a header <code>## Filter fun</code> to your notebook.</li>
<li>Add text that you filtering for regular schools.</li>
<li>Add a chunk, insert and run the following:</li>
</ul>
<blockquote>
<p>The first box shown here is the code. The second is the result. The result is prettier in RStudio.</p>
</blockquote>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="sped-transform.html#cb247-1" aria-hidden="true" tabindex="-1"></a>sped <span class="sc">%&gt;%</span> </span>
<span id="cb247-2"><a href="sped-transform.html#cb247-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(instruction_type <span class="sc">==</span> <span class="st">&quot;REGULAR INSTRUCTIONAL&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 7,372 × 10
##    school_name   district_name instruction_type  charter_type grade_range campus
##    &lt;chr&gt;         &lt;chr&gt;         &lt;chr&gt;             &lt;chr&gt;        &lt;chr&gt;       &lt;chr&gt; 
##  1 CAYUGA H S    CAYUGA ISD    REGULAR INSTRUCT… &lt;NA&gt;         &#39;09-12      00190…
##  2 CAYUGA MIDDLE CAYUGA ISD    REGULAR INSTRUCT… &lt;NA&gt;         &#39;06-08      00190…
##  3 CAYUGA EL     CAYUGA ISD    REGULAR INSTRUCT… &lt;NA&gt;         &#39;EE-05      00190…
##  4 ELKHART H S   ELKHART ISD   REGULAR INSTRUCT… &lt;NA&gt;         &#39;09-12      00190…
##  5 ELKHART MIDD… ELKHART ISD   REGULAR INSTRUCT… &lt;NA&gt;         &#39;06-08      00190…
##  6 ELKHART EL    ELKHART ISD   REGULAR INSTRUCT… &lt;NA&gt;         &#39;EE-02      00190…
##  7 ELKHART INT   ELKHART ISD   REGULAR INSTRUCT… &lt;NA&gt;         &#39;03-05      00190…
##  8 FRANKSTON H S FRANKSTON ISD REGULAR INSTRUCT… &lt;NA&gt;         &#39;09-12      00190…
##  9 FRANKSTON MI… FRANKSTON ISD REGULAR INSTRUCT… &lt;NA&gt;         &#39;06-08      00190…
## 10 FRANKSTON EL  FRANKSTON ISD REGULAR INSTRUCT… &lt;NA&gt;         &#39;EE-05      00190…
## # … with 7,362 more rows, and 4 more variables: sped_c_15 &lt;dbl&gt;,
## #   sped_p_15 &lt;dbl&gt;, sped_c_20 &lt;dbl&gt;, sped_p_20 &lt;dbl&gt;</code></pre>
<p>When you run this, you’ll see we now have only that you the about 7,372 rows instead of the 8,002 that we started with, and that also matches our “count” from above.</p>
<p>The arguments inside the <code>filter()</code> function work in this order:</p>
<ol style="list-style-type: decimal">
<li>What is the column (or variable) you are search in.</li>
<li>What is the logical test. In our case above we are looking for matches.</li>
<li>What is the value (or observation) you are looking for.</li>
</ol>
<p>Note the two equals signs <code>==</code> there. It’s important to use two of them when you are looking for “equal,” as a single <code>=</code> will not work, as that means something else in R.</p>
</div>
<div id="logical-tests" class="section level3" number="15.9.2">
<h3><span class="header-section-number">15.9.2</span> Logical tests</h3>
<p>There are a number of these logical test operations:</p>
<div class="figure">
<img src="images/transform-logical-test.png" width="500" alt="" />
<p class="caption">dplyr logical tests</p>
</div>
</div>
<div id="common-mistakes-with-filter" class="section level3" number="15.9.3">
<h3><span class="header-section-number">15.9.3</span> Common mistakes with filter</h3>
<p>Some common mistakes that happen when using filter.</p>
<div id="use-two-signs-for-true" class="section level4" number="15.9.3.1">
<h4><span class="header-section-number">15.9.3.1</span> Use two == signs for “true”</h4>
<p>DON’T DO THIS:</p>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="sped-transform.html#cb249-1" aria-hidden="true" tabindex="-1"></a>sped <span class="sc">%&gt;%</span> </span>
<span id="cb249-2"><a href="sped-transform.html#cb249-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="at">district_name =</span> <span class="st">&quot;AUSTIN ISD&quot;</span>)</span></code></pre></div>
<p>DO THIS:</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="sped-transform.html#cb250-1" aria-hidden="true" tabindex="-1"></a>sped <span class="sc">%&gt;%</span> </span>
<span id="cb250-2"><a href="sped-transform.html#cb250-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(district_name <span class="sc">==</span> <span class="st">&quot;AUSTIN ISD&quot;</span>)</span></code></pre></div>
</div>
<div id="forgetting-quotes" class="section level4" number="15.9.3.2">
<h4><span class="header-section-number">15.9.3.2</span> Forgetting quotes</h4>
<p>DON’T DO THIS:</p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="sped-transform.html#cb251-1" aria-hidden="true" tabindex="-1"></a>ratings <span class="sc">%&gt;%</span> </span>
<span id="cb251-2"><a href="sped-transform.html#cb251-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(grade_range <span class="sc">==</span> <span class="dv">09-12</span>)</span></code></pre></div>
<p>DO THIS:</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="sped-transform.html#cb252-1" aria-hidden="true" tabindex="-1"></a>ratings <span class="sc">%&gt;%</span> </span>
<span id="cb252-2"><a href="sped-transform.html#cb252-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(district_name <span class="sc">==</span> <span class="st">&quot;09-12&quot;</span>)</span></code></pre></div>
</div>
</div>
</div>
<div id="combining-filters" class="section level2" number="15.10">
<h2><span class="header-section-number">15.10</span> Combining filters</h2>
<p>You can filter for more than one thing at a time by using an operator: <code>&amp;</code>, <code>|</code>. <code>!</code>.</p>
<ul>
<li>Edit your existing code block to following code block and run it.</li>
<li>Then look at the code and the result and then <strong>write out what the filter is doing in your own words</strong>.</li>
</ul>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="sped-transform.html#cb253-1" aria-hidden="true" tabindex="-1"></a>sped <span class="sc">%&gt;%</span> </span>
<span id="cb253-2"><a href="sped-transform.html#cb253-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb253-3"><a href="sped-transform.html#cb253-3" aria-hidden="true" tabindex="-1"></a>    instruction_type <span class="sc">==</span> <span class="st">&quot;REGULAR INSTRUCTIONAL&quot;</span>,</span>
<span id="cb253-4"><a href="sped-transform.html#cb253-4" aria-hidden="true" tabindex="-1"></a>    charter_type <span class="sc">%&gt;%</span> <span class="fu">is.na</span>()</span>
<span id="cb253-5"><a href="sped-transform.html#cb253-5" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 6,962 × 10
##    school_name   district_name instruction_type  charter_type grade_range campus
##    &lt;chr&gt;         &lt;chr&gt;         &lt;chr&gt;             &lt;chr&gt;        &lt;chr&gt;       &lt;chr&gt; 
##  1 CAYUGA H S    CAYUGA ISD    REGULAR INSTRUCT… &lt;NA&gt;         &#39;09-12      00190…
##  2 CAYUGA MIDDLE CAYUGA ISD    REGULAR INSTRUCT… &lt;NA&gt;         &#39;06-08      00190…
##  3 CAYUGA EL     CAYUGA ISD    REGULAR INSTRUCT… &lt;NA&gt;         &#39;EE-05      00190…
##  4 ELKHART H S   ELKHART ISD   REGULAR INSTRUCT… &lt;NA&gt;         &#39;09-12      00190…
##  5 ELKHART MIDD… ELKHART ISD   REGULAR INSTRUCT… &lt;NA&gt;         &#39;06-08      00190…
##  6 ELKHART EL    ELKHART ISD   REGULAR INSTRUCT… &lt;NA&gt;         &#39;EE-02      00190…
##  7 ELKHART INT   ELKHART ISD   REGULAR INSTRUCT… &lt;NA&gt;         &#39;03-05      00190…
##  8 FRANKSTON H S FRANKSTON ISD REGULAR INSTRUCT… &lt;NA&gt;         &#39;09-12      00190…
##  9 FRANKSTON MI… FRANKSTON ISD REGULAR INSTRUCT… &lt;NA&gt;         &#39;06-08      00190…
## 10 FRANKSTON EL  FRANKSTON ISD REGULAR INSTRUCT… &lt;NA&gt;         &#39;EE-05      00190…
## # … with 6,952 more rows, and 4 more variables: sped_c_15 &lt;dbl&gt;,
## #   sped_p_15 &lt;dbl&gt;, sped_c_20 &lt;dbl&gt;, sped_p_20 &lt;dbl&gt;</code></pre>
<p>We rewrote the first filter to indent it differently so it was more clear that we have <strong>two logical tests</strong> here. The second test has a nested function, testing the <code>charter_type</code> field to see if it is blank, or <code>is.na()</code>, which is a special case. We could have written this line as <code>is.na(charter_type)</code>.</p>
<p>If you use a comma <code>,</code> or ampersand <code>&amp;</code> to separate two tests, then both of them have to be true. If you want OR, then you use a bar character <code>|</code> (the shift-key version of the backslash, above the Return key. That <code>|</code> is also sometimes referred to as a pipe character, but I’ll call it “bar” since we also have the <code>%&gt;%</code>.)</p>
<div class="figure">
<img src="images/transform-boolean.png" width="500" alt="" />
<p class="caption">Boolean operators</p>
</div>
<div id="common-mistakes-with-combining-filters" class="section level3" number="15.10.1">
<h3><span class="header-section-number">15.10.1</span> Common mistakes with combining filters</h3>
<p>Some things to watch when trying to combine filters.</p>
<div id="collapsing-multiple-tests-into-one" class="section level4" number="15.10.1.1">
<h4><span class="header-section-number">15.10.1.1</span> Collapsing multiple tests into one</h4>
<p>DON’T DO THIS:</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="sped-transform.html#cb255-1" aria-hidden="true" tabindex="-1"></a>sped <span class="sc">%&gt;%</span> </span>
<span id="cb255-2"><a href="sped-transform.html#cb255-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(district_name <span class="sc">==</span> <span class="st">&quot;AUSTIN ISD&quot;</span> <span class="sc">|</span> <span class="st">&quot;BASTROP ISD&quot;</span>)</span></code></pre></div>
<p>DO THIS:</p>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb256-1"><a href="sped-transform.html#cb256-1" aria-hidden="true" tabindex="-1"></a>sped <span class="sc">%&gt;%</span> </span>
<span id="cb256-2"><a href="sped-transform.html#cb256-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(district_name <span class="sc">==</span> <span class="st">&quot;AUSTIN ISD&quot;</span> <span class="sc">|</span> district_name <span class="sc">==</span><span class="st">&quot;BASTROP ISD&quot;</span>)</span></code></pre></div>
<p>BUT EVEN BETTER:</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="sped-transform.html#cb257-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding in Hays to the list as well</span></span>
<span id="cb257-2"><a href="sped-transform.html#cb257-2" aria-hidden="true" tabindex="-1"></a>sped <span class="sc">%&gt;%</span> </span>
<span id="cb257-3"><a href="sped-transform.html#cb257-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(district_name <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;AUSTIN ISD&quot;</span>, <span class="st">&quot;BASTROP ISD&quot;</span>, <span class="st">&quot;ROUND ROCK ISD&quot;</span>))</span></code></pre></div>
<p>If you want to combine a series of strings in your filter, you have to put them inside a “concatenate” function, which is shortened to <code>c()</code>, as in the example above. We’ll end up using this a lot.</p>
</div>
</div>
</div>
<div id="select" class="section level2" number="15.11">
<h2><span class="header-section-number">15.11</span> Select()</h2>
<p>When we were preparing our CSTUD data we used the <a href="https://dplyr.tidyverse.org/reference/select.html"><code>select()</code></a> function to select or exclude specific columns. We need to append to the filter we’ve been using to remove the <code>instruction_type</code> and <code>charter_type</code> columns now that we are done with them.</p>
<p>In the filter code chunk you’ve been building, modify it i the following ways:</p>
<ul>
<li>Add a select function and remove the <code>charter_type</code> and <code>instruction_type</code> columns.</li>
<li>Assign the result to a new data frame called <code>sped_reg</code>.</li>
<li>Print the data frame to the screen so you can poke around.</li>
</ul>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb258-1"><a href="sped-transform.html#cb258-1" aria-hidden="true" tabindex="-1"></a>sped_reg <span class="ot">&lt;-</span> sped <span class="sc">%&gt;%</span> </span>
<span id="cb258-2"><a href="sped-transform.html#cb258-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb258-3"><a href="sped-transform.html#cb258-3" aria-hidden="true" tabindex="-1"></a>    instruction_type <span class="sc">==</span> <span class="st">&quot;REGULAR INSTRUCTIONAL&quot;</span>,</span>
<span id="cb258-4"><a href="sped-transform.html#cb258-4" aria-hidden="true" tabindex="-1"></a>    charter_type <span class="sc">%&gt;%</span> <span class="fu">is.na</span>()</span>
<span id="cb258-5"><a href="sped-transform.html#cb258-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb258-6"><a href="sped-transform.html#cb258-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>charter_type, <span class="sc">-</span>instruction_type)</span>
<span id="cb258-7"><a href="sped-transform.html#cb258-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb258-8"><a href="sped-transform.html#cb258-8" aria-hidden="true" tabindex="-1"></a>sped_reg</span></code></pre></div>
<pre><code>## # A tibble: 6,962 × 8
##    school_name   district_name grade_range campus  sped_c_15 sped_p_15 sped_c_20
##    &lt;chr&gt;         &lt;chr&gt;         &lt;chr&gt;       &lt;chr&gt;       &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
##  1 CAYUGA H S    CAYUGA ISD    &#39;09-12      001902…        37      18          34
##  2 CAYUGA MIDDLE CAYUGA ISD    &#39;06-08      001902…        16      13.3        17
##  3 CAYUGA EL     CAYUGA ISD    &#39;EE-05      001902…        23       9.2        31
##  4 ELKHART H S   ELKHART ISD   &#39;09-12      001903…        33       9.3        44
##  5 ELKHART MIDD… ELKHART ISD   &#39;06-08      001903…        36      11.8        29
##  6 ELKHART EL    ELKHART ISD   &#39;EE-02      001903…        29       9.6        48
##  7 ELKHART INT   ELKHART ISD   &#39;03-05      001903…        27      10.5        26
##  8 FRANKSTON H S FRANKSTON ISD &#39;09-12      001904…        28      12.6        19
##  9 FRANKSTON MI… FRANKSTON ISD &#39;06-08      001904…        16       9.2        28
## 10 FRANKSTON EL  FRANKSTON ISD &#39;EE-05      001904…        34       8.4        44
## # … with 6,952 more rows, and 1 more variable: sped_p_20 &lt;dbl&gt;</code></pre>
<p>Note there are some other really cool ways to use select.</p>
<p>Here is an example capturing columns that end with "_name". (The <code>head()</code> function just gives us the first few rows of data since we don’t need to show the whole data set.)</p>
<blockquote>
<p>You don’t have to do this … I’m just showing you.</p>
</blockquote>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="sped-transform.html#cb260-1" aria-hidden="true" tabindex="-1"></a>sped_reg <span class="sc">%&gt;%</span> </span>
<span id="cb260-2"><a href="sped-transform.html#cb260-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">ends_with</span>(<span class="st">&quot;_name&quot;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb260-3"><a href="sped-transform.html#cb260-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 × 2
##   school_name    district_name
##   &lt;chr&gt;          &lt;chr&gt;        
## 1 CAYUGA H S     CAYUGA ISD   
## 2 CAYUGA MIDDLE  CAYUGA ISD   
## 3 CAYUGA EL      CAYUGA ISD   
## 4 ELKHART H S    ELKHART ISD  
## 5 ELKHART MIDDLE ELKHART ISD  
## 6 ELKHART EL     ELKHART ISD</code></pre>
</div>
<div id="how-to-describe-the-change" class="section level2" number="15.12">
<h2><span class="header-section-number">15.12</span> How to describe the change</h2>
<p>Now that we have all our data in the same data <code>sped_reg</code>, we can use create new columns compare the different years. Before we get into how, let’s talk about describing change.</p>
<p>We have two values for each year to work with: The “Count” of special education – <code>spec15</code> and <code>spec20</code> – which is the actual number of students in the program; and the “Percentage” of students in special education out of the total in that school – <code>spep15</code> and <code>spep20</code>.</p>
<p>We want to describe the change from one year to the next. You might review the Numbers in the Newsroom chapter on Measuring Change (p26) for further study. Here are some examples:</p>
<div id="describing-the-count-changes" class="section level3" number="15.12.1">
<h3><span class="header-section-number">15.12.1</span> Describing the count changes</h3>
<ul>
<li>We can show the <strong>simple difference</strong> (or actual change) in the <em>count</em> of students from one year to the next. We’ll assume there were <code>4</code> students in 2015 and <code>10</code> in 2020:
<ul>
<li><code>New Count - Old Count = Simple Difference</code>.</li>
<li>Example: <code>10 - 4 = 6</code>.</li>
<li>“The school served six more special education students in 2020 (10 students) compared to 2015 (four students).”</li>
</ul></li>
<li>We can show the <strong>percent change</strong> in the <em>count</em> of students from one year to the next:
<ul>
<li><code>((New Count - Old Count) / Old Count) * 100 = Percent change</code>.</li>
<li>Example: <code>((10 - 4) \ 4) * 100 = 150%</code>.</li>
<li>“The number of special education students served increased 150% from four in 2015 to 10 in 2020.”</li>
</ul></li>
</ul>
</div>
<div id="describing-percentage-differences" class="section level3" number="15.12.2">
<h3><span class="header-section-number">15.12.2</span> Describing percentage differences</h3>
<p>We also have the <em>percentage</em> of special education students in the school, which could be important. This is the share of students that are in the program compared to the total students in the school.</p>
<ul>
<li>We can find the <strong>percentage point difference</strong> from one year to the next using simple difference again, but we have the describe the change as the difference in percentage points:
<ul>
<li><code>New Percentage - Old Percentage = Percentage Point Difference</code>.</li>
<li>Example: <code>15.5% - 11% = 4.5 percentage points</code> (NOT 4.5%).</li>
<li>“The share of students in special education grew by 4.5 percentage points, from 11% in 2015 to 15.5% in 2020.”</li>
</ul></li>
<li>We can find the <strong>percent change of share</strong> from one year to the next, but we have to again be very specific about what we are talking about … the growth (or decrease) of the <em>share</em> of students in special education.
<ul>
<li><code>((New Percentage - Old Percentage) / Old Percentage * 100) = Change in share of students</code>.</li>
<li>Example: <code>((15.5 - 11) / 11) * 100 = 40.9</code>.</li>
<li>“The share of students in special education grew 40% from 11% of students in 2015 to 15.5% of students in 2020.” This describes the growth in the share of students in the program, not the number of special education students overall.</li>
</ul></li>
</ul>
<p>Describing a “percentage point difference” to readers can be difficult, but perhaps less confusing than describing the “percent change of a percent.”</p>
<p>Great, so which do we use for this story? That depends on what you want to describe. Schools that have fewer special education students to begin with will show a more pronounced percent change with any fluctuation. Then again, a school that has a large percentage of students could be gaining a lot of students with a small percentage change. In the end, we might need to use all of these values to describe different kinds of schools. We are talking about human beings, so perhaps the counts are important.</p>
</div>
</div>
<div id="mutate" class="section level2" number="15.13">
<h2><span class="header-section-number">15.13</span> Mutate()</h2>
<p>The <a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a> function allows us to change a column of data or create new columns based on others. We can do calculations across columns or change data types. It is useful in calculations and cleaning data.</p>
<p>For our Special Education data we need to create several calculations.</p>
<div id="simple-change-of-counts" class="section level3" number="15.13.1">
<h3><span class="header-section-number">15.13.1</span> Simple change of counts</h3>
<p>To create a column showing the number of students up or down from 2015 to 2020, we use a simple difference between our columns.</p>
<p>Let’s set up a new data frame to hold our calculations with a glimpse so we can view them as we go along.</p>
<p>Remember from our preparation steps, mutate works like this:</p>
<ol style="list-style-type: decimal">
<li>first name the new column</li>
<li>set it to <code>=</code> the new value</li>
<li>specify what the new result should be</li>
</ol>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="sped-transform.html#cb262-1" aria-hidden="true" tabindex="-1"></a>sped_calcs <span class="ot">&lt;-</span> sped_reg <span class="sc">%&gt;%</span> </span>
<span id="cb262-2"><a href="sped-transform.html#cb262-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb262-3"><a href="sped-transform.html#cb262-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># simple difference</span></span>
<span id="cb262-4"><a href="sped-transform.html#cb262-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">sped_c_diff =</span> sped_c_20 <span class="sc">-</span> sped_c_15</span>
<span id="cb262-5"><a href="sped-transform.html#cb262-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb262-6"><a href="sped-transform.html#cb262-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb262-7"><a href="sped-transform.html#cb262-7" aria-hidden="true" tabindex="-1"></a>sped_calcs <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 6,962
## Columns: 9
## $ school_name   &lt;chr&gt; &quot;CAYUGA H S&quot;, &quot;CAYUGA MIDDLE&quot;, &quot;CAYUGA EL&quot;, &quot;ELKHART H S…
## $ district_name &lt;chr&gt; &quot;CAYUGA ISD&quot;, &quot;CAYUGA ISD&quot;, &quot;CAYUGA ISD&quot;, &quot;ELKHART ISD&quot;,…
## $ grade_range   &lt;chr&gt; &quot;&#39;09-12&quot;, &quot;&#39;06-08&quot;, &quot;&#39;EE-05&quot;, &quot;&#39;09-12&quot;, &quot;&#39;06-08&quot;, &quot;&#39;EE-0…
## $ campus        &lt;chr&gt; &quot;001902001&quot;, &quot;001902041&quot;, &quot;001902103&quot;, &quot;001903001&quot;, &quot;001…
## $ sped_c_15     &lt;dbl&gt; 37, 16, 23, 33, 36, 29, 27, 28, 16, 34, 16, 25, 96, 44, …
## $ sped_p_15     &lt;dbl&gt; 18.0, 13.3, 9.2, 9.3, 11.8, 9.6, 10.5, 12.6, 9.2, 8.4, 1…
## $ sped_c_20     &lt;dbl&gt; 34, 17, 31, 44, 29, 48, 26, 19, 28, 44, 11, 14, 103, 70,…
## $ sped_p_20     &lt;dbl&gt; 19.8, 13.6, 11.9, 11.6, 11.2, 14.4, 9.4, 8.3, 15.9, 11.5…
## $ sped_c_diff   &lt;dbl&gt; -3, 1, 8, 11, -7, 19, -1, -9, 12, 10, -5, -11, 7, 26, 23…</code></pre>
<p>You can see the first value differences in the glimpse above: <strong>34 - 37 = -3</strong>. If that is difficult to see we could build a quick look to see just those columns:</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="sped-transform.html#cb264-1" aria-hidden="true" tabindex="-1"></a>sped_calcs <span class="sc">%&gt;%</span> </span>
<span id="cb264-2"><a href="sped-transform.html#cb264-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(school_name, sped_c_15, sped_c_20, sped_c_diff) <span class="sc">%&gt;%</span> </span>
<span id="cb264-3"><a href="sped-transform.html#cb264-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 × 4
##   school_name    sped_c_15 sped_c_20 sped_c_diff
##   &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
## 1 CAYUGA H S            37        34          -3
## 2 CAYUGA MIDDLE         16        17           1
## 3 CAYUGA EL             23        31           8
## 4 ELKHART H S           33        44          11
## 5 ELKHART MIDDLE        36        29          -7
## 6 ELKHART EL            29        48          19</code></pre>
<p>You always want to check your mutates to make sure they work!</p>
<p>We will continue to build on our <code>sped_calc</code> data frame with new calculations.</p>
</div>
<div id="calculate-percent-change" class="section level3" number="15.13.2">
<h3><span class="header-section-number">15.13.2</span> Calculate percent change</h3>
<p>For this calculation we have the more complex task of the percent-change math. We also have to round the result to a readable number, accomplished by piping the math result into the <code>round_half_up()</code> function, which takes the argument of how many places to round the result.</p>
<ul>
<li>Modify your calculations to include the <code>sped_c_prccng</code> result:</li>
</ul>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="sped-transform.html#cb266-1" aria-hidden="true" tabindex="-1"></a>sped_calcs <span class="ot">&lt;-</span> sped_reg <span class="sc">%&gt;%</span> </span>
<span id="cb266-2"><a href="sped-transform.html#cb266-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb266-3"><a href="sped-transform.html#cb266-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># simple diff</span></span>
<span id="cb266-4"><a href="sped-transform.html#cb266-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sped_c_diff =</span> sped_c_20 <span class="sc">-</span> sped_c_15,</span>
<span id="cb266-5"><a href="sped-transform.html#cb266-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># percent change</span></span>
<span id="cb266-6"><a href="sped-transform.html#cb266-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">spec_c_prccng =</span> ((sped_c_20 <span class="sc">-</span> sped_c_15) <span class="sc">/</span> sped_c_15 <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span> <span class="fu">round_half_up</span>(<span class="dv">1</span>),</span>
<span id="cb266-7"><a href="sped-transform.html#cb266-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># simple diff of percent</span></span>
<span id="cb266-8"><a href="sped-transform.html#cb266-8" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb266-9"><a href="sped-transform.html#cb266-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb266-10"><a href="sped-transform.html#cb266-10" aria-hidden="true" tabindex="-1"></a>sped_calcs <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 6,962
## Columns: 10
## $ school_name   &lt;chr&gt; &quot;CAYUGA H S&quot;, &quot;CAYUGA MIDDLE&quot;, &quot;CAYUGA EL&quot;, &quot;ELKHART H S…
## $ district_name &lt;chr&gt; &quot;CAYUGA ISD&quot;, &quot;CAYUGA ISD&quot;, &quot;CAYUGA ISD&quot;, &quot;ELKHART ISD&quot;,…
## $ grade_range   &lt;chr&gt; &quot;&#39;09-12&quot;, &quot;&#39;06-08&quot;, &quot;&#39;EE-05&quot;, &quot;&#39;09-12&quot;, &quot;&#39;06-08&quot;, &quot;&#39;EE-0…
## $ campus        &lt;chr&gt; &quot;001902001&quot;, &quot;001902041&quot;, &quot;001902103&quot;, &quot;001903001&quot;, &quot;001…
## $ sped_c_15     &lt;dbl&gt; 37, 16, 23, 33, 36, 29, 27, 28, 16, 34, 16, 25, 96, 44, …
## $ sped_p_15     &lt;dbl&gt; 18.0, 13.3, 9.2, 9.3, 11.8, 9.6, 10.5, 12.6, 9.2, 8.4, 1…
## $ sped_c_20     &lt;dbl&gt; 34, 17, 31, 44, 29, 48, 26, 19, 28, 44, 11, 14, 103, 70,…
## $ sped_p_20     &lt;dbl&gt; 19.8, 13.6, 11.9, 11.6, 11.2, 14.4, 9.4, 8.3, 15.9, 11.5…
## $ sped_c_diff   &lt;dbl&gt; -3, 1, 8, 11, -7, 19, -1, -9, 12, 10, -5, -11, 7, 26, 23…
## $ spec_c_prccng &lt;dbl&gt; -8.1, 6.3, 34.8, 33.3, -19.4, 65.5, -3.7, -32.1, 75.0, 2…</code></pre>
<p>Check your math: <strong>((34 - 37) / 37 * 100) = 8.108</strong>.</p>
</div>
<div id="calculate-percentage-point-difference" class="section level3" number="15.13.3">
<h3><span class="header-section-number">15.13.3</span> Calculate percentage point difference</h3>
<p>This is another simple difference, but this time with the percentage fields.</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb268-1"><a href="sped-transform.html#cb268-1" aria-hidden="true" tabindex="-1"></a>sped_calcs <span class="ot">&lt;-</span> sped_reg <span class="sc">%&gt;%</span> </span>
<span id="cb268-2"><a href="sped-transform.html#cb268-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb268-3"><a href="sped-transform.html#cb268-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># simple diff</span></span>
<span id="cb268-4"><a href="sped-transform.html#cb268-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sped_c_diff =</span> sped_c_20 <span class="sc">-</span> sped_c_15,</span>
<span id="cb268-5"><a href="sped-transform.html#cb268-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># percent change</span></span>
<span id="cb268-6"><a href="sped-transform.html#cb268-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sped_c_prccng =</span> ((sped_c_20 <span class="sc">-</span> sped_c_15) <span class="sc">/</span> sped_c_15 <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span> <span class="fu">round_half_up</span>(<span class="dv">1</span>),</span>
<span id="cb268-7"><a href="sped-transform.html#cb268-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># simple diff of percent</span></span>
<span id="cb268-8"><a href="sped-transform.html#cb268-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">sped_p_ppd =</span> sped_p_20 <span class="sc">-</span> sped_p_15</span>
<span id="cb268-9"><a href="sped-transform.html#cb268-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb268-10"><a href="sped-transform.html#cb268-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb268-11"><a href="sped-transform.html#cb268-11" aria-hidden="true" tabindex="-1"></a>sped_calcs <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 6,962
## Columns: 11
## $ school_name   &lt;chr&gt; &quot;CAYUGA H S&quot;, &quot;CAYUGA MIDDLE&quot;, &quot;CAYUGA EL&quot;, &quot;ELKHART H S…
## $ district_name &lt;chr&gt; &quot;CAYUGA ISD&quot;, &quot;CAYUGA ISD&quot;, &quot;CAYUGA ISD&quot;, &quot;ELKHART ISD&quot;,…
## $ grade_range   &lt;chr&gt; &quot;&#39;09-12&quot;, &quot;&#39;06-08&quot;, &quot;&#39;EE-05&quot;, &quot;&#39;09-12&quot;, &quot;&#39;06-08&quot;, &quot;&#39;EE-0…
## $ campus        &lt;chr&gt; &quot;001902001&quot;, &quot;001902041&quot;, &quot;001902103&quot;, &quot;001903001&quot;, &quot;001…
## $ sped_c_15     &lt;dbl&gt; 37, 16, 23, 33, 36, 29, 27, 28, 16, 34, 16, 25, 96, 44, …
## $ sped_p_15     &lt;dbl&gt; 18.0, 13.3, 9.2, 9.3, 11.8, 9.6, 10.5, 12.6, 9.2, 8.4, 1…
## $ sped_c_20     &lt;dbl&gt; 34, 17, 31, 44, 29, 48, 26, 19, 28, 44, 11, 14, 103, 70,…
## $ sped_p_20     &lt;dbl&gt; 19.8, 13.6, 11.9, 11.6, 11.2, 14.4, 9.4, 8.3, 15.9, 11.5…
## $ sped_c_diff   &lt;dbl&gt; -3, 1, 8, 11, -7, 19, -1, -9, 12, 10, -5, -11, 7, 26, 23…
## $ sped_c_prccng &lt;dbl&gt; -8.1, 6.3, 34.8, 33.3, -19.4, 65.5, -3.7, -32.1, 75.0, 2…
## $ sped_p_ppd    &lt;dbl&gt; 1.8, 0.3, 2.7, 2.3, -0.6, 4.8, -1.1, -4.3, 6.7, 3.1, -4.…</code></pre>
<p>Again, check your work: <strong>19.8 - 18.0 = 1.8</strong>.</p>
<p>Remember, the challenge with using this value in writing is to couch it as <strong>percentage point difference</strong> and not a percentage or percent change.</p>
</div>
<div id="calculating-our-special-education-threshold" class="section level3" number="15.13.4">
<h3><span class="header-section-number">15.13.4</span> Calculating our special education threshold</h3>
<p>As you may recall, the point of the Chronicle’s story was that schools that had 8.5% or higher of special education students had to go through hoops, forcing schools to try to avoid putting students in these programs. The reason we are comparing 2015 data to 2020 is to see if there are more schools with higher percentages of special education students.</p>
<p>The way we’ll do that is to create a “threshold” column for each year. We’ll use <code>mutate()</code> to create a column that says “Y” if the school is at or above the threshold, and “N” if it is not. Once we do this for both years, we can use some summaries to count them.</p>
<p>This process will introduce <a href="https://dplyr.tidyverse.org/reference/case_when.html"><code>case_when()</code></a> which compares to the <strong>IF=</strong> function in Excel.</p>
<p>It works like this <em>within</em> a mutate:</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="sped-transform.html#cb270-1" aria-hidden="true" tabindex="-1"></a>new_column <span class="ot">=</span> <span class="fu">case_when</span>(</span>
<span id="cb270-2"><a href="sped-transform.html#cb270-2" aria-hidden="true" tabindex="-1"></a>  test <span class="sc">~</span> <span class="st">&quot;result_if_true&quot;</span>,</span>
<span id="cb270-3"><a href="sped-transform.html#cb270-3" aria-hidden="true" tabindex="-1"></a>  <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&quot;result_if_false&quot;</span></span>
<span id="cb270-4"><a href="sped-transform.html#cb270-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>If that last <code>TRUE</code> confuses you that it is the false answer, then yeah … me too.</p>
<p>The power of this is you can add multiple test by adding more lines before the <code>TRUE</code> line, but we don’t need that here.</p>
<ul>
<li>Update your <code>sped_calcs</code> code chunk to include both of our threshold cases.</li>
</ul>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="sped-transform.html#cb271-1" aria-hidden="true" tabindex="-1"></a>sped_calcs <span class="ot">&lt;-</span> sped_reg <span class="sc">%&gt;%</span> </span>
<span id="cb271-2"><a href="sped-transform.html#cb271-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb271-3"><a href="sped-transform.html#cb271-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># simple diff</span></span>
<span id="cb271-4"><a href="sped-transform.html#cb271-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">sped_c_diff =</span> sped_c_20 <span class="sc">-</span> sped_c_15,</span>
<span id="cb271-5"><a href="sped-transform.html#cb271-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># percent change</span></span>
<span id="cb271-6"><a href="sped-transform.html#cb271-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">sped_c_prccng =</span> ((sped_c_20 <span class="sc">-</span> sped_c_15) <span class="sc">/</span> sped_c_15 <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span> <span class="fu">round_half_up</span>(<span class="dv">1</span>),</span>
<span id="cb271-7"><a href="sped-transform.html#cb271-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># simple diff of percent</span></span>
<span id="cb271-8"><a href="sped-transform.html#cb271-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">sped_p_ppd =</span> sped_p_20 <span class="sc">-</span> sped_p_15,</span>
<span id="cb271-9"><a href="sped-transform.html#cb271-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># meets threshold 8.5% 2015</span></span>
<span id="cb271-10"><a href="sped-transform.html#cb271-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">sped15_thsh =</span> <span class="fu">case_when</span>(</span>
<span id="cb271-11"><a href="sped-transform.html#cb271-11" aria-hidden="true" tabindex="-1"></a>      sped_p_15 <span class="sc">&gt;=</span> <span class="fl">8.5</span> <span class="sc">~</span> <span class="st">&quot;Y&quot;</span>,</span>
<span id="cb271-12"><a href="sped-transform.html#cb271-12" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&quot;N&quot;</span></span>
<span id="cb271-13"><a href="sped-transform.html#cb271-13" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb271-14"><a href="sped-transform.html#cb271-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># meets threhhold 8.5% 2020</span></span>
<span id="cb271-15"><a href="sped-transform.html#cb271-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">sped20_thsh =</span> <span class="fu">case_when</span>(</span>
<span id="cb271-16"><a href="sped-transform.html#cb271-16" aria-hidden="true" tabindex="-1"></a>      sped_p_20 <span class="sc">&gt;=</span> <span class="fl">8.5</span> <span class="sc">~</span> <span class="st">&quot;Y&quot;</span>,</span>
<span id="cb271-17"><a href="sped-transform.html#cb271-17" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&quot;N&quot;</span></span>
<span id="cb271-18"><a href="sped-transform.html#cb271-18" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb271-19"><a href="sped-transform.html#cb271-19" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb271-20"><a href="sped-transform.html#cb271-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb271-21"><a href="sped-transform.html#cb271-21" aria-hidden="true" tabindex="-1"></a>sped_calcs <span class="sc">%&gt;%</span> glimpse</span></code></pre></div>
<pre><code>## Rows: 6,962
## Columns: 13
## $ school_name   &lt;chr&gt; &quot;CAYUGA H S&quot;, &quot;CAYUGA MIDDLE&quot;, &quot;CAYUGA EL&quot;, &quot;ELKHART H S…
## $ district_name &lt;chr&gt; &quot;CAYUGA ISD&quot;, &quot;CAYUGA ISD&quot;, &quot;CAYUGA ISD&quot;, &quot;ELKHART ISD&quot;,…
## $ grade_range   &lt;chr&gt; &quot;&#39;09-12&quot;, &quot;&#39;06-08&quot;, &quot;&#39;EE-05&quot;, &quot;&#39;09-12&quot;, &quot;&#39;06-08&quot;, &quot;&#39;EE-0…
## $ campus        &lt;chr&gt; &quot;001902001&quot;, &quot;001902041&quot;, &quot;001902103&quot;, &quot;001903001&quot;, &quot;001…
## $ sped_c_15     &lt;dbl&gt; 37, 16, 23, 33, 36, 29, 27, 28, 16, 34, 16, 25, 96, 44, …
## $ sped_p_15     &lt;dbl&gt; 18.0, 13.3, 9.2, 9.3, 11.8, 9.6, 10.5, 12.6, 9.2, 8.4, 1…
## $ sped_c_20     &lt;dbl&gt; 34, 17, 31, 44, 29, 48, 26, 19, 28, 44, 11, 14, 103, 70,…
## $ sped_p_20     &lt;dbl&gt; 19.8, 13.6, 11.9, 11.6, 11.2, 14.4, 9.4, 8.3, 15.9, 11.5…
## $ sped_c_diff   &lt;dbl&gt; -3, 1, 8, 11, -7, 19, -1, -9, 12, 10, -5, -11, 7, 26, 23…
## $ sped_c_prccng &lt;dbl&gt; -8.1, 6.3, 34.8, 33.3, -19.4, 65.5, -3.7, -32.1, 75.0, 2…
## $ sped_p_ppd    &lt;dbl&gt; 1.8, 0.3, 2.7, 2.3, -0.6, 4.8, -1.1, -4.3, 6.7, 3.1, -4.…
## $ sped15_thsh   &lt;chr&gt; &quot;Y&quot;, &quot;Y&quot;, &quot;Y&quot;, &quot;Y&quot;, &quot;Y&quot;, &quot;Y&quot;, &quot;Y&quot;, &quot;Y&quot;, &quot;Y&quot;, &quot;N&quot;, &quot;Y&quot;, &quot;…
## $ sped20_thsh   &lt;chr&gt; &quot;Y&quot;, &quot;Y&quot;, &quot;Y&quot;, &quot;Y&quot;, &quot;Y&quot;, &quot;Y&quot;, &quot;Y&quot;, &quot;N&quot;, &quot;Y&quot;, &quot;Y&quot;, &quot;Y&quot;, &quot;…</code></pre>
<p>And then, of course, check the result to make sure it is right. Again, if you are having trouble seeing it in the glimpse, then build yourself a new R chunk to show you columns germane to your inspection:</p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb273-1"><a href="sped-transform.html#cb273-1" aria-hidden="true" tabindex="-1"></a>sped_calcs <span class="sc">%&gt;%</span> </span>
<span id="cb273-2"><a href="sped-transform.html#cb273-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb273-3"><a href="sped-transform.html#cb273-3" aria-hidden="true" tabindex="-1"></a>    school_name,</span>
<span id="cb273-4"><a href="sped-transform.html#cb273-4" aria-hidden="true" tabindex="-1"></a>    sped_p_15,</span>
<span id="cb273-5"><a href="sped-transform.html#cb273-5" aria-hidden="true" tabindex="-1"></a>    sped15_thsh,</span>
<span id="cb273-6"><a href="sped-transform.html#cb273-6" aria-hidden="true" tabindex="-1"></a>    sped_p_20</span>
<span id="cb273-7"><a href="sped-transform.html#cb273-7" aria-hidden="true" tabindex="-1"></a>    , sped20_thsh</span>
<span id="cb273-8"><a href="sped-transform.html#cb273-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb273-9"><a href="sped-transform.html#cb273-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">20</span>)</span></code></pre></div>
<pre><code>## # A tibble: 20 × 5
##    school_name                       sped_p_15 sped15_thsh sped_p_20 sped20_thsh
##    &lt;chr&gt;                                 &lt;dbl&gt; &lt;chr&gt;           &lt;dbl&gt; &lt;chr&gt;      
##  1 CAYUGA H S                             18   Y                19.8 Y          
##  2 CAYUGA MIDDLE                          13.3 Y                13.6 Y          
##  3 CAYUGA EL                               9.2 Y                11.9 Y          
##  4 ELKHART H S                             9.3 Y                11.6 Y          
##  5 ELKHART MIDDLE                         11.8 Y                11.2 Y          
##  6 ELKHART EL                              9.6 Y                14.4 Y          
##  7 ELKHART INT                            10.5 Y                 9.4 Y          
##  8 FRANKSTON H S                          12.6 Y                 8.3 N          
##  9 FRANKSTON MIDDLE                        9.2 Y                15.9 Y          
## 10 FRANKSTON EL                            8.4 N                11.5 Y          
## 11 NECHES H S                             14   Y                 9.9 Y          
## 12 NECHES EL                               9.8 Y                 5.8 N          
## 13 PALESTINE H S                          10.7 Y                10.4 Y          
## 14 PALESTINE J H                           9.3 Y                13.5 Y          
## 15 NORTHSIDE PRI                           5   N                 9.7 Y          
## 16 WASHINGTON EARLY CHILDHOOD CENTER       9.6 Y                 8.4 N          
## 17 SOUTHSIDE EL                            7.7 N                14.2 Y          
## 18 STORY INT                               9.2 Y                12.9 Y          
## 19 WESTWOOD H S                           10.5 Y                12.2 Y          
## 20 WESTWOOD J H                            9.7 Y                15   Y</code></pre>
</div>
</div>
<div id="export-your-computations" class="section level2" number="15.14">
<h2><span class="header-section-number">15.14</span> Export your computations</h2>
<p>We’re going to export this data so we can use it in multiple notebooks going forward. It might be overkill in this case, but this will allow us to do future notebooks on different districts if we want.</p>
<ul>
<li>Build a new export chunk and use <code>write_rds()</code> to create a file <code>02_sped_calcs.rds</code>.</li>
</ul>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="sped-transform.html#cb275-1" aria-hidden="true" tabindex="-1"></a>sped_calcs <span class="sc">%&gt;%</span> </span>
<span id="cb275-2"><a href="sped-transform.html#cb275-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">write_rds</span>(<span class="st">&quot;data-processed/02_sped_calcs.rds&quot;</span>)</span></code></pre></div>
<p>Again, we saved our processed data away from the raw data. We used a number to match which notebook it came from, and we used a descriptive name so we know what is inside the file.</p>
</div>
<div id="more-dplyr-in-next-lesson" class="section level2" number="15.15">
<h2><span class="header-section-number">15.15</span> More dplyr in next lesson</h2>
<p>We have covered a lot in our last two lessons, including some of our <a href="https://vimeo.com/showcase/7320305">Basic Data Journalism functions</a> of <strong>select</strong>, <strong>filter</strong> and <strong>join</strong>, and we learned to create new variables with with <strong>mutate</strong>.</p>
<p>There are several more dplyr functions that we haven’t used yet, but will in the next lesson: <code>arrange()</code>, <code>group_by()</code> and <code>summarize()</code>.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="sped-import.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="sped-summarize.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/31-sped-transform.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "lunr",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
