<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Summarize with math - import | Reporting with Data in R</title>
  <meta name="description" content="Chapter 5 Summarize with math - import | Reporting with Data in R is a series of lessons and instructions used in courses in the School of Journalism and Media, Moody College of Communication at the University of Texas at Austin. It is taught by Christian McDonald, assistant professor of practice." />
  <meta name="generator" content="bookdown 0.23 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Summarize with math - import | Reporting with Data in R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Chapter 5 Summarize with math - import | Reporting with Data in R is a series of lessons and instructions used in courses in the School of Journalism and Media, Moody College of Communication at the University of Texas at Austin. It is taught by Christian McDonald, assistant professor of practice." />
  <meta name="github-repo" content="utdata/rwdir" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Summarize with math - import | Reporting with Data in R" />
  
  <meta name="twitter:description" content="Chapter 5 Summarize with math - import | Reporting with Data in R is a series of lessons and instructions used in courses in the School of Journalism and Media, Moody College of Communication at the University of Texas at Austin. It is taught by Christian McDonald, assistant professor of practice." />
  

<meta name="author" content="Christian McDonald" />


<meta name="date" content="2021-09-20" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="wrangle.html"/>
<link rel="next" href="sums-analyze.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.19/datatables.js"></script>
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.20/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>
<style type="text/css">
  p.caption {
    color: #777;
    margin-top: 10px;
  }
  p code, pre, pre code, li code {
    background-color: #DCDCDC !important;
  }
</style>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Reporting with Data in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About this book</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#about-my-philosphy"><i class="fa fa-check"></i>About my philosphy</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#tips-on-my-writing-style"><i class="fa fa-check"></i>Tips on my writing style</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#things-to-do"><i class="fa fa-check"></i>Things to do</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#notes-some-important"><i class="fa fa-check"></i>Notes, some important</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#copy-code-blocks"><i class="fa fa-check"></i>Copy code blocks</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#about-the-author"><i class="fa fa-check"></i>About the author</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i>License</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#other-resources"><i class="fa fa-check"></i>Other resources</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="install.html"><a href="install.html"><i class="fa fa-check"></i><b>1</b> Install Party</a>
<ul>
<li class="chapter" data-level="1.1" data-path="install.html"><a href="install.html#mac-vs-pc"><i class="fa fa-check"></i><b>1.1</b> Mac vs PC</a></li>
<li class="chapter" data-level="1.2" data-path="install.html"><a href="install.html#installing-r"><i class="fa fa-check"></i><b>1.2</b> Installing R</a></li>
<li class="chapter" data-level="1.3" data-path="install.html"><a href="install.html#installing-rstudio"><i class="fa fa-check"></i><b>1.3</b> Installing RStudio</a></li>
<li class="chapter" data-level="1.4" data-path="install.html"><a href="install.html#class-project-folder"><i class="fa fa-check"></i><b>1.4</b> Class project folder</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction to R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="intro.html"><a href="intro.html#rstudio-tour"><i class="fa fa-check"></i><b>2.1</b> RStudio tour</a></li>
<li class="chapter" data-level="2.2" data-path="intro.html"><a href="intro.html#updating-preferences"><i class="fa fa-check"></i><b>2.2</b> Updating preferences</a></li>
<li class="chapter" data-level="2.3" data-path="intro.html"><a href="intro.html#starting-a-new-project"><i class="fa fa-check"></i><b>2.3</b> Starting a new Project</a></li>
<li class="chapter" data-level="2.4" data-path="intro.html"><a href="intro.html#using-r-notebooks"><i class="fa fa-check"></i><b>2.4</b> Using R Notebooks</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="intro.html"><a href="intro.html#create-your-first-notebook"><i class="fa fa-check"></i><b>2.4.1</b> Create your first notebook</a></li>
<li class="chapter" data-level="2.4.2" data-path="intro.html"><a href="intro.html#save-the-.rmd-file"><i class="fa fa-check"></i><b>2.4.2</b> Save the .Rmd file</a></li>
<li class="chapter" data-level="2.4.3" data-path="intro.html"><a href="intro.html#run-the-notebook"><i class="fa fa-check"></i><b>2.4.3</b> Run the notebook</a></li>
<li class="chapter" data-level="2.4.4" data-path="intro.html"><a href="intro.html#a-note-about-rmarkdown"><i class="fa fa-check"></i><b>2.4.4</b> A note about RMarkdown</a></li>
<li class="chapter" data-level="2.4.5" data-path="intro.html"><a href="intro.html#adding-new-code-chunks"><i class="fa fa-check"></i><b>2.4.5</b> Adding new code chunks</a></li>
<li class="chapter" data-level="2.4.6" data-path="intro.html"><a href="intro.html#practice-adding-code-chunks"><i class="fa fa-check"></i><b>2.4.6</b> Practice adding code chunks</a></li>
<li class="chapter" data-level="2.4.7" data-path="intro.html"><a href="intro.html#preview-the-report"><i class="fa fa-check"></i><b>2.4.7</b> Preview the report</a></li>
<li class="chapter" data-level="2.4.8" data-path="intro.html"><a href="intro.html#the-toolbar"><i class="fa fa-check"></i><b>2.4.8</b> The toolbar</a></li>
<li class="chapter" data-level="2.4.9" data-path="intro.html"><a href="intro.html#knit-the-final-workbook"><i class="fa fa-check"></i><b>2.4.9</b> Knit the final workbook</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="intro.html"><a href="intro.html#turning-in-our-projects"><i class="fa fa-check"></i><b>2.5</b> Turning in our projects</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="import.html"><a href="import.html"><i class="fa fa-check"></i><b>3</b> Import</a>
<ul>
<li class="chapter" data-level="3.1" data-path="import.html"><a href="import.html#learning-goals-of-this-lesson"><i class="fa fa-check"></i><b>3.1</b> Learning goals of this lesson</a></li>
<li class="chapter" data-level="3.2" data-path="import.html"><a href="import.html#basic-steps-of-this-lesson"><i class="fa fa-check"></i><b>3.2</b> Basic steps of this lesson</a></li>
<li class="chapter" data-level="3.3" data-path="import.html"><a href="import.html#create-a-new-project"><i class="fa fa-check"></i><b>3.3</b> Create a new project</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="import.html"><a href="import.html#describe-the-goals-of-the-notebook"><i class="fa fa-check"></i><b>3.3.1</b> Describe the goals of the notebook</a></li>
<li class="chapter" data-level="3.3.2" data-path="import.html"><a href="import.html#the-r-package-environment"><i class="fa fa-check"></i><b>3.3.2</b> The R Package environment</a></li>
<li class="chapter" data-level="3.3.3" data-path="import.html"><a href="import.html#installing-and-using-packages"><i class="fa fa-check"></i><b>3.3.3</b> Installing and using packages</a></li>
<li class="chapter" data-level="3.3.4" data-path="import.html"><a href="import.html#load-the-libraries"><i class="fa fa-check"></i><b>3.3.4</b> Load the libraries</a></li>
<li class="chapter" data-level="3.3.5" data-path="import.html"><a href="import.html#create-a-directory-for-your-data"><i class="fa fa-check"></i><b>3.3.5</b> Create a directory for your data</a></li>
<li class="chapter" data-level="3.3.6" data-path="import.html"><a href="import.html#lets-get-our-data"><i class="fa fa-check"></i><b>3.3.6</b> Let’s get our data</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="import.html"><a href="import.html#about-data-sources"><i class="fa fa-check"></i><b>3.4</b> About data sources</a></li>
<li class="chapter" data-level="3.5" data-path="import.html"><a href="import.html#our-project-data"><i class="fa fa-check"></i><b>3.5</b> Our project data</a></li>
<li class="chapter" data-level="3.6" data-path="import.html"><a href="import.html#data-dictionary"><i class="fa fa-check"></i><b>3.6</b> Data dictionary</a></li>
<li class="chapter" data-level="3.7" data-path="import.html"><a href="import.html#import-the-data"><i class="fa fa-check"></i><b>3.7</b> Import the data</a></li>
<li class="chapter" data-level="3.8" data-path="import.html"><a href="import.html#assign-our-import-to-a-tibble"><i class="fa fa-check"></i><b>3.8</b> Assign our import to a tibble</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="import.html"><a href="import.html#print-a-peek-to-the-screen"><i class="fa fa-check"></i><b>3.8.1</b> Print a peek to the screen</a></li>
<li class="chapter" data-level="3.8.2" data-path="import.html"><a href="import.html#glimpse-the-data"><i class="fa fa-check"></i><b>3.8.2</b> Glimpse the data</a></li>
<li class="chapter" data-level="3.8.3" data-path="import.html"><a href="import.html#about-the-pipe"><i class="fa fa-check"></i><b>3.8.3</b> About the pipe %&gt;%</a></li>
<li class="chapter" data-level="3.8.4" data-path="import.html"><a href="import.html#what-is-clean-data"><i class="fa fa-check"></i><b>3.8.4</b> What is clean data</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="import.html"><a href="import.html#cleaning-column-names"><i class="fa fa-check"></i><b>3.9</b> Cleaning column names</a></li>
<li class="chapter" data-level="3.10" data-path="import.html"><a href="import.html#fixing-the-date"><i class="fa fa-check"></i><b>3.10</b> Fixing the date</a>
<ul>
<li class="chapter" data-level="3.10.1" data-path="import.html"><a href="import.html#working-with-mutate"><i class="fa fa-check"></i><b>3.10.1</b> Working with mutate()</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="import.html"><a href="import.html#arrange-the-data"><i class="fa fa-check"></i><b>3.11</b> Arrange the data</a></li>
<li class="chapter" data-level="3.12" data-path="import.html"><a href="import.html#selecting-columns"><i class="fa fa-check"></i><b>3.12</b> Selecting columns</a></li>
<li class="chapter" data-level="3.13" data-path="import.html"><a href="import.html#exporting-data"><i class="fa fa-check"></i><b>3.13</b> Exporting data</a>
<ul>
<li class="chapter" data-level="3.13.1" data-path="import.html"><a href="import.html#single-notebook-philosophy"><i class="fa fa-check"></i><b>3.13.1</b> Single-notebook philosophy</a></li>
<li class="chapter" data-level="3.13.2" data-path="import.html"><a href="import.html#exporting-as-rds"><i class="fa fa-check"></i><b>3.13.2</b> Exporting as rds</a></li>
</ul></li>
<li class="chapter" data-level="3.14" data-path="import.html"><a href="import.html#naming-chunks"><i class="fa fa-check"></i><b>3.14</b> Naming chunks</a></li>
<li class="chapter" data-level="3.15" data-path="import.html"><a href="import.html#knit-your-page"><i class="fa fa-check"></i><b>3.15</b> Knit your page</a></li>
<li class="chapter" data-level="3.16" data-path="import.html"><a href="import.html#review-of-what-weve-learned-so-far"><i class="fa fa-check"></i><b>3.16</b> Review of what we’ve learned so far</a></li>
<li class="chapter" data-level="3.17" data-path="import.html"><a href="import.html#whats-next"><i class="fa fa-check"></i><b>3.17</b> What’s next</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="wrangle.html"><a href="wrangle.html"><i class="fa fa-check"></i><b>4</b> Wrangle</a>
<ul>
<li class="chapter" data-level="4.1" data-path="wrangle.html"><a href="wrangle.html#goals-of-this-lesson"><i class="fa fa-check"></i><b>4.1</b> Goals of this lesson</a></li>
<li class="chapter" data-level="4.2" data-path="wrangle.html"><a href="wrangle.html#about-the-story"><i class="fa fa-check"></i><b>4.2</b> About the story</a></li>
<li class="chapter" data-level="4.3" data-path="wrangle.html"><a href="wrangle.html#setting-up-an-analysis-notebook"><i class="fa fa-check"></i><b>4.3</b> Setting up an analysis notebook</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="wrangle.html"><a href="wrangle.html#import-the-data-on-your-own"><i class="fa fa-check"></i><b>4.3.1</b> Import the data on your own</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="wrangle.html"><a href="wrangle.html#introducing-dplyr"><i class="fa fa-check"></i><b>4.4</b> Introducing dplyr</a></li>
<li class="chapter" data-level="4.5" data-path="wrangle.html"><a href="wrangle.html#most-appearances"><i class="fa fa-check"></i><b>4.5</b> Most appearances</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="wrangle.html"><a href="wrangle.html#group-aggregate"><i class="fa fa-check"></i><b>4.5.1</b> Group &amp; Aggregate</a></li>
<li class="chapter" data-level="4.5.2" data-path="wrangle.html"><a href="wrangle.html#summarize"><i class="fa fa-check"></i><b>4.5.2</b> Summarize</a></li>
<li class="chapter" data-level="4.5.3" data-path="wrangle.html"><a href="wrangle.html#group-by"><i class="fa fa-check"></i><b>4.5.3</b> Group by</a></li>
<li class="chapter" data-level="4.5.4" data-path="wrangle.html"><a href="wrangle.html#arrange-the-results"><i class="fa fa-check"></i><b>4.5.4</b> Arrange the results</a></li>
<li class="chapter" data-level="4.5.5" data-path="wrangle.html"><a href="wrangle.html#get-the-top-of-the-list"><i class="fa fa-check"></i><b>4.5.5</b> Get the top of the list</a></li>
<li class="chapter" data-level="4.5.6" data-path="wrangle.html"><a href="wrangle.html#a-shortcut-count"><i class="fa fa-check"></i><b>4.5.6</b> A shortcut: count()</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="wrangle.html"><a href="wrangle.html#most-songs-to-reach-no.-1"><i class="fa fa-check"></i><b>4.6</b> Most songs to reach No. 1</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="wrangle.html"><a href="wrangle.html#filter"><i class="fa fa-check"></i><b>4.6.1</b> Filter</a></li>
<li class="chapter" data-level="4.6.2" data-path="wrangle.html"><a href="wrangle.html#comparisons-logical-tests"><i class="fa fa-check"></i><b>4.6.2</b> Comparisons: Logical tests</a></li>
<li class="chapter" data-level="4.6.3" data-path="wrangle.html"><a href="wrangle.html#filter-for-week_position"><i class="fa fa-check"></i><b>4.6.3</b> Filter for week_position</a></li>
<li class="chapter" data-level="4.6.4" data-path="wrangle.html"><a href="wrangle.html#complex-filters"><i class="fa fa-check"></i><b>4.6.4</b> Complex filters</a></li>
<li class="chapter" data-level="4.6.5" data-path="wrangle.html"><a href="wrangle.html#using-distinct"><i class="fa fa-check"></i><b>4.6.5</b> Using distinct()</a></li>
<li class="chapter" data-level="4.6.6" data-path="wrangle.html"><a href="wrangle.html#summarize-the-performers"><i class="fa fa-check"></i><b>4.6.6</b> Summarize the performers</a></li>
<li class="chapter" data-level="4.6.7" data-path="wrangle.html"><a href="wrangle.html#filter-after-summary"><i class="fa fa-check"></i><b>4.6.7</b> Filter after summary</a></li>
<li class="chapter" data-level="4.6.8" data-path="wrangle.html"><a href="wrangle.html#try-count-on-your-own"><i class="fa fa-check"></i><b>4.6.8</b> Try count on your own</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="wrangle.html"><a href="wrangle.html#no.-1-hits-in-last-five-years"><i class="fa fa-check"></i><b>4.7</b> No. 1 hits in last five years</a>
<ul>
<li class="chapter" data-level="4.7.1" data-path="wrangle.html"><a href="wrangle.html#group-on-your-own"><i class="fa fa-check"></i><b>4.7.1</b> Group on your own</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="wrangle.html"><a href="wrangle.html#top-10-hits-overall"><i class="fa fa-check"></i><b>4.8</b> Top 10 hits overall</a></li>
<li class="chapter" data-level="4.9" data-path="wrangle.html"><a href="wrangle.html#songperformer-with-most-appearances-at-any-position"><i class="fa fa-check"></i><b>4.9</b> Song/Performer with most appearances at any position</a></li>
<li class="chapter" data-level="4.10" data-path="wrangle.html"><a href="wrangle.html#songperformer-with-most-weeks-at-no.-1"><i class="fa fa-check"></i><b>4.10</b> Song/Performer with most weeks at No. 1</a></li>
<li class="chapter" data-level="4.11" data-path="wrangle.html"><a href="wrangle.html#review-of-what-weve-learned"><i class="fa fa-check"></i><b>4.11</b> Review of what we’ve learned</a></li>
<li class="chapter" data-level="4.12" data-path="wrangle.html"><a href="wrangle.html#turn-in-your-project"><i class="fa fa-check"></i><b>4.12</b> Turn in your project</a></li>
<li class="chapter" data-level="4.13" data-path="wrangle.html"><a href="wrangle.html#soundtrack-for-this-assignment"><i class="fa fa-check"></i><b>4.13</b> Soundtrack for this assignment</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="sums-import.html"><a href="sums-import.html"><i class="fa fa-check"></i><b>5</b> Summarize with math - import</a>
<ul>
<li class="chapter" data-level="5.1" data-path="sums-import.html"><a href="sums-import.html#about-the-story-military-surplus-transfers"><i class="fa fa-check"></i><b>5.1</b> About the story: Military surplus transfers</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="sums-import.html"><a href="sums-import.html#the-leso-program"><i class="fa fa-check"></i><b>5.1.1</b> The LESO program</a></li>
<li class="chapter" data-level="5.1.2" data-path="sums-import.html"><a href="sums-import.html#about-the-data"><i class="fa fa-check"></i><b>5.1.2</b> About the data</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="sums-import.html"><a href="sums-import.html#the-questions-we-will-answer"><i class="fa fa-check"></i><b>5.2</b> The questions we will answer</a></li>
<li class="chapter" data-level="5.3" data-path="sums-import.html"><a href="sums-import.html#create-your-project"><i class="fa fa-check"></i><b>5.3</b> Create your project</a></li>
<li class="chapter" data-level="5.4" data-path="sums-import.html"><a href="sums-import.html#importcleaning-notebook"><i class="fa fa-check"></i><b>5.4</b> Import/cleaning notebook</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="sums-import.html"><a href="sums-import.html#add-the-goals-of-the-notebook"><i class="fa fa-check"></i><b>5.4.1</b> Add the goals of the notebook</a></li>
<li class="chapter" data-level="5.4.2" data-path="sums-import.html"><a href="sums-import.html#add-a-setup-section"><i class="fa fa-check"></i><b>5.4.2</b> Add a setup section</a></li>
<li class="chapter" data-level="5.4.3" data-path="sums-import.html"><a href="sums-import.html#download-the-data"><i class="fa fa-check"></i><b>5.4.3</b> Download the data</a></li>
<li class="chapter" data-level="5.4.4" data-path="sums-import.html"><a href="sums-import.html#import-the-data-1"><i class="fa fa-check"></i><b>5.4.4</b> Import the data</a></li>
<li class="chapter" data-level="5.4.5" data-path="sums-import.html"><a href="sums-import.html#glimpse-the-data-1"><i class="fa fa-check"></i><b>5.4.5</b> Glimpse the data</a></li>
<li class="chapter" data-level="5.4.6" data-path="sums-import.html"><a href="sums-import.html#remove-unnecessary-columns"><i class="fa fa-check"></i><b>5.4.6</b> Remove unnecessary columns</a></li>
<li class="chapter" data-level="5.4.7" data-path="sums-import.html"><a href="sums-import.html#create-a-total_value-column"><i class="fa fa-check"></i><b>5.4.7</b> Create a total_value column</a></li>
<li class="chapter" data-level="5.4.8" data-path="sums-import.html"><a href="sums-import.html#filtering-our-data"><i class="fa fa-check"></i><b>5.4.8</b> Filtering our data</a></li>
<li class="chapter" data-level="5.4.9" data-path="sums-import.html"><a href="sums-import.html#export-cleaned-data"><i class="fa fa-check"></i><b>5.4.9</b> Export cleaned data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="sums-analyze.html"><a href="sums-analyze.html"><i class="fa fa-check"></i><b>6</b> Summarize with math - analysis</a>
<ul>
<li class="chapter" data-level="6.1" data-path="sums-analyze.html"><a href="sums-analyze.html#learning-goals-of-this-lesson-1"><i class="fa fa-check"></i><b>6.1</b> Learning goals of this lesson</a></li>
<li class="chapter" data-level="6.2" data-path="sums-analyze.html"><a href="sums-analyze.html#questions-to-answer"><i class="fa fa-check"></i><b>6.2</b> Questions to answer</a></li>
<li class="chapter" data-level="6.3" data-path="sums-analyze.html"><a href="sums-analyze.html#set-up-the-analysis-notebook"><i class="fa fa-check"></i><b>6.3</b> Set up the analysis notebook</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="sums-analyze.html"><a href="sums-analyze.html#load-the-data-into-a-tibble"><i class="fa fa-check"></i><b>6.3.1</b> Load the data into a tibble</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="sums-analyze.html"><a href="sums-analyze.html#how-to-tackle-summaries"><i class="fa fa-check"></i><b>6.4</b> How to tackle summaries</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="sums-analyze.html"><a href="sums-analyze.html#summaries-with-math"><i class="fa fa-check"></i><b>6.4.1</b> Summaries with math</a></li>
<li class="chapter" data-level="6.4.2" data-path="sums-analyze.html"><a href="sums-analyze.html#add-the-total_value"><i class="fa fa-check"></i><b>6.4.2</b> Add the total_value</a></li>
<li class="chapter" data-level="6.4.3" data-path="sums-analyze.html"><a href="sums-analyze.html#arrange-the-results-1"><i class="fa fa-check"></i><b>6.4.3</b> Arrange the results</a></li>
<li class="chapter" data-level="6.4.4" data-path="sums-analyze.html"><a href="sums-analyze.html#consider-the-results"><i class="fa fa-check"></i><b>6.4.4</b> Consider the results</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="sums-analyze.html"><a href="sums-analyze.html#looking-a-local-agencies"><i class="fa fa-check"></i><b>6.5</b> Looking a local agencies</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="sums-analyze.html"><a href="sums-analyze.html#filter-in-a-vector"><i class="fa fa-check"></i><b>6.5.1</b> Filter in a vector</a></li>
<li class="chapter" data-level="6.5.2" data-path="sums-analyze.html"><a href="sums-analyze.html#item-quantiies-totals-for-local-agencies"><i class="fa fa-check"></i><b>6.5.2</b> Item quantiies, totals for local agencies</a></li>
<li class="chapter" data-level="6.5.3" data-path="sums-analyze.html"><a href="sums-analyze.html#filter-from-a-collection"><i class="fa fa-check"></i><b>6.5.3</b> Filter from a collection</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="sums-analyze.html"><a href="sums-analyze.html#write-a-data-drop"><i class="fa fa-check"></i><b>6.6</b> Write a data drop</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="plots.html"><a href="plots.html"><i class="fa fa-check"></i><b>7</b> Plots</a>
<ul>
<li class="chapter" data-level="7.1" data-path="plots.html"><a href="plots.html#updates-needed"><i class="fa fa-check"></i><b>7.1</b> UPDATES NEEDED</a></li>
<li class="chapter" data-level="7.2" data-path="plots.html"><a href="plots.html#goals-for-this-section"><i class="fa fa-check"></i><b>7.2</b> Goals for this section</a></li>
<li class="chapter" data-level="7.3" data-path="plots.html"><a href="plots.html#introduction-ggplot"><i class="fa fa-check"></i><b>7.3</b> Introduction ggplot</a></li>
<li class="chapter" data-level="7.4" data-path="plots.html"><a href="plots.html#the-basic-ggplot-template"><i class="fa fa-check"></i><b>7.4</b> The basic ggplot template</a></li>
<li class="chapter" data-level="7.5" data-path="plots.html"><a href="plots.html#lets-plot"><i class="fa fa-check"></i><b>7.5</b> Let’s plot!</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="plots.html"><a href="plots.html#set-up-our-notebook"><i class="fa fa-check"></i><b>7.5.1</b> Set up our Notebook</a></li>
<li class="chapter" data-level="7.5.2" data-path="plots.html"><a href="plots.html#scatterplot"><i class="fa fa-check"></i><b>7.5.2</b> Scatterplot</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="plots.html"><a href="plots.html#plotting-our-wells-data"><i class="fa fa-check"></i><b>7.6</b> Plotting our wells data</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="plots.html"><a href="plots.html#total-wells-per-county"><i class="fa fa-check"></i><b>7.6.1</b> Total wells per county</a></li>
<li class="chapter" data-level="7.6.2" data-path="plots.html"><a href="plots.html#add-a-layer-of-text-labels"><i class="fa fa-check"></i><b>7.6.2</b> Add a layer of text labels</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="plots.html"><a href="plots.html#wells-per-county-over-time"><i class="fa fa-check"></i><b>7.7</b> Wells per county over time</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="plots.html"><a href="plots.html#work-up-the-data-frame"><i class="fa fa-check"></i><b>7.7.1</b> Work up the data frame</a></li>
<li class="chapter" data-level="7.7.2" data-path="plots.html"><a href="plots.html#draw-the-plot"><i class="fa fa-check"></i><b>7.7.2</b> Draw the plot</a></li>
<li class="chapter" data-level="7.7.3" data-path="plots.html"><a href="plots.html#your-turn-add-layers"><i class="fa fa-check"></i><b>7.7.3</b> Your turn: Add layers</a></li>
<li class="chapter" data-level="7.7.4" data-path="plots.html"><a href="plots.html#dates-as-numbers-and-the-problems-they-cause"><i class="fa fa-check"></i><b>7.7.4</b> Dates as numbers and the problems they cause</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="plots.html"><a href="plots.html#your-turn-build-a-line-chart"><i class="fa fa-check"></i><b>7.8</b> Your turn: Build a line chart</a></li>
<li class="chapter" data-level="7.9" data-path="plots.html"><a href="plots.html#review-of-ggplot"><i class="fa fa-check"></i><b>7.9</b> Review of ggplot</a></li>
<li class="chapter" data-level="7.10" data-path="plots.html"><a href="plots.html#plotly-for-more-interactive-graphics"><i class="fa fa-check"></i><b>7.10</b> Plotly for more interactive graphics</a>
<ul>
<li class="chapter" data-level="7.10.1" data-path="plots.html"><a href="plots.html#ggplotly"><i class="fa fa-check"></i><b>7.10.1</b> ggplotly</a></li>
<li class="chapter" data-level="7.10.2" data-path="plots.html"><a href="plots.html#more-with-plot_ly-function"><i class="fa fa-check"></i><b>7.10.2</b> More with <code>plot_ly()</code> function</a></li>
<li class="chapter" data-level="7.10.3" data-path="plots.html"><a href="plots.html#plotlys-freemium-model"><i class="fa fa-check"></i><b>7.10.3</b> Plotly’s freemium model</a></li>
</ul></li>
<li class="chapter" data-level="7.11" data-path="plots.html"><a href="plots.html#resources"><i class="fa fa-check"></i><b>7.11</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="tidy.html"><a href="tidy.html"><i class="fa fa-check"></i><b>8</b> Tidy data</a>
<ul>
<li class="chapter" data-level="8.1" data-path="tidy.html"><a href="tidy.html#updates-needed-1"><i class="fa fa-check"></i><b>8.1</b> UPDATES NEEDED</a></li>
<li class="chapter" data-level="8.2" data-path="tidy.html"><a href="tidy.html#goals-for-this-section-1"><i class="fa fa-check"></i><b>8.2</b> Goals for this section</a></li>
<li class="chapter" data-level="8.3" data-path="tidy.html"><a href="tidy.html#what-is-tidy-data"><i class="fa fa-check"></i><b>8.3</b> What is tidy data</a></li>
<li class="chapter" data-level="8.4" data-path="tidy.html"><a href="tidy.html#tidyr-package"><i class="fa fa-check"></i><b>8.4</b> Tidyr package</a></li>
<li class="chapter" data-level="8.5" data-path="tidy.html"><a href="tidy.html#the-tidyr-verbs"><i class="fa fa-check"></i><b>8.5</b> The tidyr verbs</a></li>
<li class="chapter" data-level="8.6" data-path="tidy.html"><a href="tidy.html#set-up-the-mixbev-project"><i class="fa fa-check"></i><b>8.6</b> Set up the mixbev project</a></li>
<li class="chapter" data-level="8.7" data-path="tidy.html"><a href="tidy.html#create-an-explore-notebook"><i class="fa fa-check"></i><b>8.7</b> Create an explore notebook</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="tidy.html"><a href="tidy.html#peruse-the-data"><i class="fa fa-check"></i><b>8.7.1</b> Peruse the data</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="tidy.html"><a href="tidy.html#what-might-we-learn-about-this-dataset"><i class="fa fa-check"></i><b>8.8</b> What might we learn about this dataset</a></li>
<li class="chapter" data-level="8.9" data-path="tidy.html"><a href="tidy.html#add-years-and-months-values"><i class="fa fa-check"></i><b>8.9</b> Add years and months values</a></li>
<li class="chapter" data-level="8.10" data-path="tidy.html"><a href="tidy.html#campus-bars"><i class="fa fa-check"></i><b>8.10</b> Campus bars</a>
<ul>
<li class="chapter" data-level="8.10.1" data-path="tidy.html"><a href="tidy.html#total-78705-sales-leaders-in-2018"><i class="fa fa-check"></i><b>8.10.1</b> Total 78705 sales leaders in 2018</a></li>
</ul></li>
<li class="chapter" data-level="8.11" data-path="tidy.html"><a href="tidy.html#west-campus-student-hot-spots"><i class="fa fa-check"></i><b>8.11</b> West Campus student hot spots</a></li>
<li class="chapter" data-level="8.12" data-path="tidy.html"><a href="tidy.html#campus-area-bar-sales-over-time"><i class="fa fa-check"></i><b>8.12</b> Campus-area bar sales over time</a>
<ul>
<li class="chapter" data-level="8.12.1" data-path="tidy.html"><a href="tidy.html#visualizing-your-visualization"><i class="fa fa-check"></i><b>8.12.1</b> Visualizing your visualization</a></li>
<li class="chapter" data-level="8.12.2" data-path="tidy.html"><a href="tidy.html#what-did-we-find"><i class="fa fa-check"></i><b>8.12.2</b> What did we find?</a></li>
</ul></li>
<li class="chapter" data-level="8.13" data-path="tidy.html"><a href="tidy.html#types-of-sales-within-student-bars"><i class="fa fa-check"></i><b>8.13</b> Types of sales within student bars</a></li>
<li class="chapter" data-level="8.14" data-path="tidy.html"><a href="tidy.html#how-gather-works"><i class="fa fa-check"></i><b>8.14</b> How gather() works</a></li>
<li class="chapter" data-level="8.15" data-path="tidy.html"><a href="tidy.html#applying-gather-to-beer-wine-and-liquor"><i class="fa fa-check"></i><b>8.15</b> Applying gather() to beer, wine and liquor</a>
<ul>
<li class="chapter" data-level="8.15.1" data-path="tidy.html"><a href="tidy.html#plot-sales-by-type-for-a-single-campus-area-bar"><i class="fa fa-check"></i><b>8.15.1</b> Plot sales by type for a single campus-area bar</a></li>
<li class="chapter" data-level="8.15.2" data-path="tidy.html"><a href="tidy.html#plot-sales-by-type-for-multiple-campus-area-bars"><i class="fa fa-check"></i><b>8.15.2</b> Plot sales by type for multiple campus-area bars</a></li>
<li class="chapter" data-level="8.15.3" data-path="tidy.html"><a href="tidy.html#what-did-we-learn"><i class="fa fa-check"></i><b>8.15.3</b> What did we learn?</a></li>
</ul></li>
<li class="chapter" data-level="8.16" data-path="tidy.html"><a href="tidy.html#the-spread-function"><i class="fa fa-check"></i><b>8.16</b> The spread() function</a></li>
<li class="chapter" data-level="8.17" data-path="tidy.html"><a href="tidy.html#practice-assignment-exploring-the-top-seller"><i class="fa fa-check"></i><b>8.17</b> Practice assignment: Exploring the top seller</a></li>
<li class="chapter" data-level="8.18" data-path="tidy.html"><a href="tidy.html#bonus-top-5-sellers-in-travis-county-over-three-years"><i class="fa fa-check"></i><b>8.18</b> Bonus: Top 5 sellers in Travis County over three years</a></li>
<li class="chapter" data-level="8.19" data-path="tidy.html"><a href="tidy.html#bonus-total-sales-by-county"><i class="fa fa-check"></i><b>8.19</b> Bonus: Total sales by county</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="review-plots.html"><a href="review-plots.html"><i class="fa fa-check"></i><b>9</b> Review: Plots</a>
<ul>
<li class="chapter" data-level="9.1" data-path="review-plots.html"><a href="review-plots.html#updates-needed-2"><i class="fa fa-check"></i><b>9.1</b> UPDATES NEEDED</a></li>
<li class="chapter" data-level="9.2" data-path="review-plots.html"><a href="review-plots.html#project-setup"><i class="fa fa-check"></i><b>9.2</b> Project setup</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="review-plots.html"><a href="review-plots.html#download-the-data-1"><i class="fa fa-check"></i><b>9.2.1</b> Download the data</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="review-plots.html"><a href="review-plots.html#the-story"><i class="fa fa-check"></i><b>9.3</b> The story</a></li>
<li class="chapter" data-level="9.4" data-path="review-plots.html"><a href="review-plots.html#explore-the-data"><i class="fa fa-check"></i><b>9.4</b> Explore the data</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="review-plots.html"><a href="review-plots.html#third-down-conversions"><i class="fa fa-check"></i><b>9.4.1</b> Third-down conversions</a></li>
<li class="chapter" data-level="9.4.2" data-path="review-plots.html"><a href="review-plots.html#scoring"><i class="fa fa-check"></i><b>9.4.2</b> Scoring</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="review-plots.html"><a href="review-plots.html#about-joins"><i class="fa fa-check"></i><b>9.5</b> About joins</a></li>
<li class="chapter" data-level="9.6" data-path="review-plots.html"><a href="review-plots.html#build-our-scatterplot"><i class="fa fa-check"></i><b>9.6</b> Build our scatterplot</a>
<ul>
<li class="chapter" data-level="9.6.1" data-path="review-plots.html"><a href="review-plots.html#add-a-fit-line"><i class="fa fa-check"></i><b>9.6.1</b> Add a fit line</a></li>
<li class="chapter" data-level="9.6.2" data-path="review-plots.html"><a href="review-plots.html#run-a-correlation-test"><i class="fa fa-check"></i><b>9.6.2</b> Run a correlation test</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="review-plots.html"><a href="review-plots.html#how-does-texas-compare"><i class="fa fa-check"></i><b>9.7</b> How does Texas compare?</a></li>
<li class="chapter" data-level="9.8" data-path="review-plots.html"><a href="review-plots.html#correlaton-test-for-texas"><i class="fa fa-check"></i><b>9.8</b> Correlaton test for Texas</a></li>
<li class="chapter" data-level="9.9" data-path="review-plots.html"><a href="review-plots.html#practice-1-compare-penn-state"><i class="fa fa-check"></i><b>9.9</b> Practice 1: Compare Penn State</a></li>
<li class="chapter" data-level="9.10" data-path="review-plots.html"><a href="review-plots.html#practice-2-penalties-vs-scoring"><i class="fa fa-check"></i><b>9.10</b> Practice 2: Penalties vs scoring</a></li>
<li class="chapter" data-level="9.11" data-path="review-plots.html"><a href="review-plots.html#using-bind_rows-to-merge-data-sets"><i class="fa fa-check"></i><b>9.11</b> Using bind_rows() to merge data sets</a>
<ul>
<li class="chapter" data-level="9.11.1" data-path="review-plots.html"><a href="review-plots.html#combine-data-with-a-group"><i class="fa fa-check"></i><b>9.11.1</b> Combine data with a group</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="reordering-factors.html"><a href="reordering-factors.html"><i class="fa fa-check"></i><b>10</b> Reordering factors</a>
<ul>
<li class="chapter" data-level="10.1" data-path="reordering-factors.html"><a href="reordering-factors.html#goals-for-this-section-2"><i class="fa fa-check"></i><b>10.1</b> Goals for this section</a></li>
<li class="chapter" data-level="10.2" data-path="reordering-factors.html"><a href="reordering-factors.html#create-our-survey-project"><i class="fa fa-check"></i><b>10.2</b> Create our survey project</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="reordering-factors.html"><a href="reordering-factors.html#setup"><i class="fa fa-check"></i><b>10.2.1</b> Setup</a></li>
<li class="chapter" data-level="10.2.2" data-path="reordering-factors.html"><a href="reordering-factors.html#libraries"><i class="fa fa-check"></i><b>10.2.2</b> Libraries</a></li>
<li class="chapter" data-level="10.2.3" data-path="reordering-factors.html"><a href="reordering-factors.html#import-the-data-2"><i class="fa fa-check"></i><b>10.2.3</b> Import the data</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="reordering-factors.html"><a href="reordering-factors.html#figuring-out-our-data-shape"><i class="fa fa-check"></i><b>10.3</b> Figuring out our data shape</a></li>
<li class="chapter" data-level="10.4" data-path="reordering-factors.html"><a href="reordering-factors.html#charting-the-popularity-of-princess"><i class="fa fa-check"></i><b>10.4</b> Charting the popularity of princess</a></li>
<li class="chapter" data-level="10.5" data-path="reordering-factors.html"><a href="reordering-factors.html#create-our-princess-plot"><i class="fa fa-check"></i><b>10.5</b> Create our princess plot</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="reordering-factors.html"><a href="reordering-factors.html#labels-and-titles"><i class="fa fa-check"></i><b>10.5.1</b> Labels and titles</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="reordering-factors.html"><a href="reordering-factors.html#factors"><i class="fa fa-check"></i><b>10.6</b> Factors</a></li>
<li class="chapter" data-level="10.7" data-path="reordering-factors.html"><a href="reordering-factors.html#reorder-princess"><i class="fa fa-check"></i><b>10.7</b> Reorder princess</a></li>
<li class="chapter" data-level="10.8" data-path="reordering-factors.html"><a href="reordering-factors.html#factors-recap"><i class="fa fa-check"></i><b>10.8</b> Factors recap</a></li>
<li class="chapter" data-level="10.9" data-path="reordering-factors.html"><a href="reordering-factors.html#practice-make-an-ice-cream-chart"><i class="fa fa-check"></i><b>10.9</b> Practice: Make an ice cream chart</a>
<ul>
<li class="chapter" data-level="10.9.1" data-path="reordering-factors.html"><a href="reordering-factors.html#turn-in-this-project"><i class="fa fa-check"></i><b>10.9.1</b> Turn in this project</a></li>
</ul></li>
<li class="chapter" data-level="10.10" data-path="reordering-factors.html"><a href="reordering-factors.html#resources-1"><i class="fa fa-check"></i><b>10.10</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="plotly.html"><a href="plotly.html"><i class="fa fa-check"></i><b>11</b> Plotly</a></li>
<li class="chapter" data-level="12" data-path="census.html"><a href="census.html"><i class="fa fa-check"></i><b>12</b> Census</a>
<ul>
<li class="chapter" data-level="12.1" data-path="census.html"><a href="census.html#goals-of-this-section"><i class="fa fa-check"></i><b>12.1</b> Goals of this section</a></li>
<li class="chapter" data-level="12.2" data-path="census.html"><a href="census.html#census-bureau-programs-and-platforms"><i class="fa fa-check"></i><b>12.2</b> Census Bureau programs and platforms</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="census.html"><a href="census.html#decennial-census"><i class="fa fa-check"></i><b>12.2.1</b> Decennial Census</a></li>
<li class="chapter" data-level="12.2.2" data-path="census.html"><a href="census.html#american-community-survey"><i class="fa fa-check"></i><b>12.2.2</b> American Community Survey</a></li>
<li class="chapter" data-level="12.2.3" data-path="census.html"><a href="census.html#population-estimates-program"><i class="fa fa-check"></i><b>12.2.3</b> Population Estimates Program</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="census.html"><a href="census.html#using-the-new-data-portal"><i class="fa fa-check"></i><b>12.3</b> Using the new data portal</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="census.html"><a href="census.html#tips-about-using-downloaded-portal-data-in-r"><i class="fa fa-check"></i><b>12.3.1</b> Tips about using downloaded portal data in R</a></li>
<li class="chapter" data-level="12.3.2" data-path="census.html"><a href="census.html#importing-downloaded-data"><i class="fa fa-check"></i><b>12.3.2</b> Importing downloaded data</a></li>
<li class="chapter" data-level="12.3.3" data-path="census.html"><a href="census.html#fields-made-to-join-with-other-data"><i class="fa fa-check"></i><b>12.3.3</b> Fields made to join with other data</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="census.html"><a href="census.html#using-the-census-api-in-r"><i class="fa fa-check"></i><b>12.4</b> Using the Census API in R</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="census.html"><a href="census.html#setting-up-an-api-key"><i class="fa fa-check"></i><b>12.4.1</b> Setting up an API key</a></li>
<li class="chapter" data-level="12.4.2" data-path="census.html"><a href="census.html#the-censusapi-package"><i class="fa fa-check"></i><b>12.4.2</b> The censusapi package</a></li>
<li class="chapter" data-level="12.4.3" data-path="census.html"><a href="census.html#the-tidycensus-package"><i class="fa fa-check"></i><b>12.4.3</b> The tidycensus package</a></li>
<li class="chapter" data-level="12.4.4" data-path="census.html"><a href="census.html#adding-geometry-to-tidycensus"><i class="fa fa-check"></i><b>12.4.4</b> Adding geometry to tidycensus</a></li>
<li class="chapter" data-level="12.4.5" data-path="census.html"><a href="census.html#map-shapes-only-with-tigris"><i class="fa fa-check"></i><b>12.4.5</b> Map shapes only with tigris</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="census.html"><a href="census.html#interactive-maps-with-leaflet"><i class="fa fa-check"></i><b>12.5</b> Interactive maps with leaflet</a></li>
<li class="chapter" data-level="12.6" data-path="census.html"><a href="census.html#resources-2"><i class="fa fa-check"></i><b>12.6</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="review---data-wrangling.html"><a href="review---data-wrangling.html"><i class="fa fa-check"></i><b>13</b> Review - Data wrangling</a>
<ul>
<li class="chapter" data-level="13.1" data-path="review---data-wrangling.html"><a href="review---data-wrangling.html#start-a-new-project"><i class="fa fa-check"></i><b>13.1</b> Start a new project</a></li>
<li class="chapter" data-level="13.2" data-path="review---data-wrangling.html"><a href="review---data-wrangling.html#downloading-our-data"><i class="fa fa-check"></i><b>13.2</b> Downloading our data</a></li>
<li class="chapter" data-level="13.3" data-path="review---data-wrangling.html"><a href="review---data-wrangling.html#importing-from-an-excel-spreadsheet"><i class="fa fa-check"></i><b>13.3</b> Importing from an Excel spreadsheet</a></li>
<li class="chapter" data-level="13.4" data-path="review---data-wrangling.html"><a href="review---data-wrangling.html#a-quick-look-at-our-data"><i class="fa fa-check"></i><b>13.4</b> A quick look at our data</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="cleaning.html"><a href="cleaning.html"><i class="fa fa-check"></i><b>14</b> Cleaning</a>
<ul>
<li class="chapter" data-level="14.1" data-path="cleaning.html"><a href="cleaning.html#not-finished-needs-rewrite"><i class="fa fa-check"></i><b>14.1</b> NOT FINISHED, NEEDS REWRITE</a></li>
<li class="chapter" data-level="14.2" data-path="cleaning.html"><a href="cleaning.html#goals-for-this-section-3"><i class="fa fa-check"></i><b>14.2</b> Goals for this section</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="cleaning.html"><a href="cleaning.html#resources-3"><i class="fa fa-check"></i><b>14.2.1</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="cleaning.html"><a href="cleaning.html#explain-thyself"><i class="fa fa-check"></i><b>14.3</b> Explain thyself</a></li>
<li class="chapter" data-level="14.4" data-path="cleaning.html"><a href="cleaning.html#syntax-etiquette"><i class="fa fa-check"></i><b>14.4</b> Syntax etiquette</a></li>
<li class="chapter" data-level="14.5" data-path="cleaning.html"><a href="cleaning.html#recode-the-apd_race-column"><i class="fa fa-check"></i><b>14.5</b> Recode the <code>apd_race</code> column</a></li>
<li class="chapter" data-level="14.6" data-path="cleaning.html"><a href="cleaning.html#filter-out-data-we-dont-need"><i class="fa fa-check"></i><b>14.6</b> Filter out data we don’t need</a>
<ul>
<li class="chapter" data-level="14.6.1" data-path="cleaning.html"><a href="cleaning.html#about-marijuana-charges"><i class="fa fa-check"></i><b>14.6.1</b> About marijuana charges</a></li>
<li class="chapter" data-level="14.6.2" data-path="cleaning.html"><a href="cleaning.html#filter-out-delivery-charges"><i class="fa fa-check"></i><b>14.6.2</b> Filter out delivery charges</a></li>
<li class="chapter" data-level="14.6.3" data-path="cleaning.html"><a href="cleaning.html#remove-controlled-substance"><i class="fa fa-check"></i><b>14.6.3</b> Remove controlled substance</a></li>
<li class="chapter" data-level="14.6.4" data-path="cleaning.html"><a href="cleaning.html#remove-drug-free-zones"><i class="fa fa-check"></i><b>14.6.4</b> Remove drug free zones</a></li>
<li class="chapter" data-level="14.6.5" data-path="cleaning.html"><a href="cleaning.html#remove-request-to-apprehend"><i class="fa fa-check"></i><b>14.6.5</b> Remove request to apprehend</a></li>
<li class="chapter" data-level="14.6.6" data-path="cleaning.html"><a href="cleaning.html#removing-more-unwated-records"><i class="fa fa-check"></i><b>14.6.6</b> Removing more unwated records</a></li>
</ul></li>
<li class="chapter" data-level="14.7" data-path="cleaning.html"><a href="cleaning.html#finding-just-b-misdemeanors"><i class="fa fa-check"></i><b>14.7</b> Finding just B misdemeanors</a></li>
<li class="chapter" data-level="14.8" data-path="cleaning.html"><a href="cleaning.html#export-your-updated-data-frame"><i class="fa fa-check"></i><b>14.8</b> Export your updated data frame</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="sped-import.html"><a href="sped-import.html"><i class="fa fa-check"></i><b>15</b> SPED Joins</a>
<ul>
<li class="chapter" data-level="15.1" data-path="sped-import.html"><a href="sped-import.html#goals-for-this-section-4"><i class="fa fa-check"></i><b>15.1</b> Goals for this section</a></li>
<li class="chapter" data-level="15.2" data-path="sped-import.html"><a href="sped-import.html#our-project-data-1"><i class="fa fa-check"></i><b>15.2</b> Our project data</a></li>
<li class="chapter" data-level="15.3" data-path="sped-import.html"><a href="sped-import.html#about-data-sources-1"><i class="fa fa-check"></i><b>15.3</b> About data sources</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="sped-import.html"><a href="sped-import.html#what-is-clean-data-1"><i class="fa fa-check"></i><b>15.3.1</b> What is clean data</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="sped-import.html"><a href="sped-import.html#create-a-new-project-1"><i class="fa fa-check"></i><b>15.4</b> Create a new project</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="sped-import.html"><a href="sped-import.html#the-r-package-environment-1"><i class="fa fa-check"></i><b>15.4.1</b> The R Package environment</a></li>
<li class="chapter" data-level="15.4.2" data-path="sped-import.html"><a href="sped-import.html#installing-and-using-packages-1"><i class="fa fa-check"></i><b>15.4.2</b> Installing and using packages</a></li>
<li class="chapter" data-level="15.4.3" data-path="sped-import.html"><a href="sped-import.html#load-the-libraries-1"><i class="fa fa-check"></i><b>15.4.3</b> Load the libraries</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="sped-import.html"><a href="sped-import.html#downloading-raw-data"><i class="fa fa-check"></i><b>15.5</b> Downloading raw data</a>
<ul>
<li class="chapter" data-level="15.5.1" data-path="sped-import.html"><a href="sped-import.html#create-a-directory-for-your-data-1"><i class="fa fa-check"></i><b>15.5.1</b> Create a directory for your data</a></li>
<li class="chapter" data-level="15.5.2" data-path="sped-import.html"><a href="sped-import.html#lets-get-some-data"><i class="fa fa-check"></i><b>15.5.2</b> Let’s get some data</a></li>
<li class="chapter" data-level="15.5.3" data-path="sped-import.html"><a href="sped-import.html#peek-at-the-data-file"><i class="fa fa-check"></i><b>15.5.3</b> Peek at the data file</a></li>
<li class="chapter" data-level="15.5.4" data-path="sped-import.html"><a href="sped-import.html#import-csv-as-data"><i class="fa fa-check"></i><b>15.5.4</b> Import csv as data</a></li>
</ul></li>
<li class="chapter" data-level="15.6" data-path="sped-import.html"><a href="sped-import.html#assign-our-import-to-a-data-frame"><i class="fa fa-check"></i><b>15.6</b> Assign our import to a data frame</a>
<ul>
<li class="chapter" data-level="15.6.1" data-path="sped-import.html"><a href="sped-import.html#print-a-peek-to-the-screen-1"><i class="fa fa-check"></i><b>15.6.1</b> Print a peek to the screen</a></li>
<li class="chapter" data-level="15.6.2" data-path="sped-import.html"><a href="sped-import.html#glimpse-the-data-2"><i class="fa fa-check"></i><b>15.6.2</b> Glimpse the data</a></li>
<li class="chapter" data-level="15.6.3" data-path="sped-import.html"><a href="sped-import.html#about-the-pipe-1"><i class="fa fa-check"></i><b>15.6.3</b> About the pipe %&gt;%</a></li>
<li class="chapter" data-level="15.6.4" data-path="sped-import.html"><a href="sped-import.html#creating-consistent-column-names"><i class="fa fa-check"></i><b>15.6.4</b> Creating consistent column names</a></li>
<li class="chapter" data-level="15.6.5" data-path="sped-import.html"><a href="sped-import.html#import-other-data-frames"><i class="fa fa-check"></i><b>15.6.5</b> Import other data frames</a></li>
</ul></li>
<li class="chapter" data-level="15.7" data-path="sped-import.html"><a href="sped-import.html#prepare-data-for-joining"><i class="fa fa-check"></i><b>15.7</b> Prepare data for joining</a>
<ul>
<li class="chapter" data-level="15.7.1" data-path="sped-import.html"><a href="sped-import.html#prepare-the-directory-data"><i class="fa fa-check"></i><b>15.7.1</b> Prepare the directory data</a></li>
<li class="chapter" data-level="15.7.2" data-path="sped-import.html"><a href="sped-import.html#prepare-cstud-data"><i class="fa fa-check"></i><b>15.7.2</b> Prepare CSTUD data</a></li>
</ul></li>
<li class="chapter" data-level="15.8" data-path="sped-import.html"><a href="sped-import.html#joining-the-data-together"><i class="fa fa-check"></i><b>15.8</b> Joining the data together</a></li>
<li class="chapter" data-level="15.9" data-path="sped-import.html"><a href="sped-import.html#exporting-data-1"><i class="fa fa-check"></i><b>15.9</b> Exporting data</a>
<ul>
<li class="chapter" data-level="15.9.1" data-path="sped-import.html"><a href="sped-import.html#single-notebook-philosophy-1"><i class="fa fa-check"></i><b>15.9.1</b> Single-notebook philosophy</a></li>
<li class="chapter" data-level="15.9.2" data-path="sped-import.html"><a href="sped-import.html#exporting-as-rds-1"><i class="fa fa-check"></i><b>15.9.2</b> Exporting as rds</a></li>
</ul></li>
<li class="chapter" data-level="15.10" data-path="sped-import.html"><a href="sped-import.html#review-of-what-weve-learned-so-far-1"><i class="fa fa-check"></i><b>15.10</b> Review of what we’ve learned so far</a></li>
<li class="chapter" data-level="15.11" data-path="sped-import.html"><a href="sped-import.html#resources-4"><i class="fa fa-check"></i><b>15.11</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="sped-transform.html"><a href="sped-transform.html"><i class="fa fa-check"></i><b>16</b> Transform</a>
<ul>
<li class="chapter" data-level="16.1" data-path="sped-transform.html"><a href="sped-transform.html#rewite-tasks"><i class="fa fa-check"></i><b>16.1</b> Rewite tasks</a></li>
<li class="chapter" data-level="16.2" data-path="sped-transform.html"><a href="sped-transform.html#goals-for-the-section"><i class="fa fa-check"></i><b>16.2</b> Goals for the section</a></li>
<li class="chapter" data-level="16.3" data-path="sped-transform.html"><a href="sped-transform.html#introducing-dplyr-1"><i class="fa fa-check"></i><b>16.3</b> Introducing dplyr</a></li>
<li class="chapter" data-level="16.4" data-path="sped-transform.html"><a href="sped-transform.html#start-a-new-r-notebook"><i class="fa fa-check"></i><b>16.4</b> Start a new R Notebook</a></li>
<li class="chapter" data-level="16.5" data-path="sped-transform.html"><a href="sped-transform.html#record-our-goals"><i class="fa fa-check"></i><b>16.5</b> Record our goals</a></li>
<li class="chapter" data-level="16.6" data-path="sped-transform.html"><a href="sped-transform.html#setup-1"><i class="fa fa-check"></i><b>16.6</b> Setup</a>
<ul>
<li class="chapter" data-level="16.6.1" data-path="sped-transform.html"><a href="sped-transform.html#naming-our-chunks"><i class="fa fa-check"></i><b>16.6.1</b> Naming our chunks</a></li>
</ul></li>
<li class="chapter" data-level="16.7" data-path="sped-transform.html"><a href="sped-transform.html#import-our-data"><i class="fa fa-check"></i><b>16.7</b> Import our data</a></li>
<li class="chapter" data-level="16.8" data-path="sped-transform.html"><a href="sped-transform.html#explore-instruction-type"><i class="fa fa-check"></i><b>16.8</b> Explore instruction type</a></li>
<li class="chapter" data-level="16.9" data-path="sped-transform.html"><a href="sped-transform.html#filter-1"><i class="fa fa-check"></i><b>16.9</b> Filter()</a>
<ul>
<li class="chapter" data-level="16.9.1" data-path="sped-transform.html"><a href="sped-transform.html#filter-for-regular-instructional-schools"><i class="fa fa-check"></i><b>16.9.1</b> Filter for Regular Instructional schools</a></li>
<li class="chapter" data-level="16.9.2" data-path="sped-transform.html"><a href="sped-transform.html#logical-tests"><i class="fa fa-check"></i><b>16.9.2</b> Logical tests</a></li>
<li class="chapter" data-level="16.9.3" data-path="sped-transform.html"><a href="sped-transform.html#common-mistakes-with-filter"><i class="fa fa-check"></i><b>16.9.3</b> Common mistakes with filter</a></li>
</ul></li>
<li class="chapter" data-level="16.10" data-path="sped-transform.html"><a href="sped-transform.html#combining-filters"><i class="fa fa-check"></i><b>16.10</b> Combining filters</a>
<ul>
<li class="chapter" data-level="16.10.1" data-path="sped-transform.html"><a href="sped-transform.html#common-mistakes-with-combining-filters"><i class="fa fa-check"></i><b>16.10.1</b> Common mistakes with combining filters</a></li>
</ul></li>
<li class="chapter" data-level="16.11" data-path="sped-transform.html"><a href="sped-transform.html#select"><i class="fa fa-check"></i><b>16.11</b> Select()</a></li>
<li class="chapter" data-level="16.12" data-path="sped-transform.html"><a href="sped-transform.html#how-to-describe-the-change"><i class="fa fa-check"></i><b>16.12</b> How to describe the change</a>
<ul>
<li class="chapter" data-level="16.12.1" data-path="sped-transform.html"><a href="sped-transform.html#describing-the-count-changes"><i class="fa fa-check"></i><b>16.12.1</b> Describing the count changes</a></li>
<li class="chapter" data-level="16.12.2" data-path="sped-transform.html"><a href="sped-transform.html#describing-percentage-differences"><i class="fa fa-check"></i><b>16.12.2</b> Describing percentage differences</a></li>
</ul></li>
<li class="chapter" data-level="16.13" data-path="sped-transform.html"><a href="sped-transform.html#mutate"><i class="fa fa-check"></i><b>16.13</b> Mutate()</a>
<ul>
<li class="chapter" data-level="16.13.1" data-path="sped-transform.html"><a href="sped-transform.html#simple-change-of-counts"><i class="fa fa-check"></i><b>16.13.1</b> Simple change of counts</a></li>
<li class="chapter" data-level="16.13.2" data-path="sped-transform.html"><a href="sped-transform.html#calculate-percent-change"><i class="fa fa-check"></i><b>16.13.2</b> Calculate percent change</a></li>
<li class="chapter" data-level="16.13.3" data-path="sped-transform.html"><a href="sped-transform.html#calculate-percentage-point-difference"><i class="fa fa-check"></i><b>16.13.3</b> Calculate percentage point difference</a></li>
<li class="chapter" data-level="16.13.4" data-path="sped-transform.html"><a href="sped-transform.html#calculating-our-special-education-threshold"><i class="fa fa-check"></i><b>16.13.4</b> Calculating our special education threshold</a></li>
</ul></li>
<li class="chapter" data-level="16.14" data-path="sped-transform.html"><a href="sped-transform.html#export-your-computations"><i class="fa fa-check"></i><b>16.14</b> Export your computations</a></li>
<li class="chapter" data-level="16.15" data-path="sped-transform.html"><a href="sped-transform.html#more-dplyr-in-next-lesson"><i class="fa fa-check"></i><b>16.15</b> More dplyr in next lesson</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="sped-summarize.html"><a href="sped-summarize.html"><i class="fa fa-check"></i><b>17</b> Summarize</a>
<ul>
<li class="chapter" data-level="17.1" data-path="sped-summarize.html"><a href="sped-summarize.html#new-task-new-notebook"><i class="fa fa-check"></i><b>17.1</b> New task, new notebook</a>
<ul>
<li class="chapter" data-level="17.1.1" data-path="sped-summarize.html"><a href="sped-summarize.html#create-analysis-notebook"><i class="fa fa-check"></i><b>17.1.1</b> Create analysis notebook</a></li>
<li class="chapter" data-level="17.1.2" data-path="sped-summarize.html"><a href="sped-summarize.html#import-1"><i class="fa fa-check"></i><b>17.1.2</b> Import</a></li>
<li class="chapter" data-level="17.1.3" data-path="sped-summarize.html"><a href="sped-summarize.html#filter-to-austin-isd"><i class="fa fa-check"></i><b>17.1.3</b> Filter to Austin ISD</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="sped-summarize.html"><a href="sped-summarize.html#sorting-with-arrange"><i class="fa fa-check"></i><b>17.2</b> Sorting with arrange()</a>
<ul>
<li class="chapter" data-level="17.2.1" data-path="sped-summarize.html"><a href="sped-summarize.html#about-arrange"><i class="fa fa-check"></i><b>17.2.1</b> About arrange</a></li>
<li class="chapter" data-level="17.2.2" data-path="sped-summarize.html"><a href="sped-summarize.html#most-new-special-education-students"><i class="fa fa-check"></i><b>17.2.2</b> Most new special education students</a></li>
<li class="chapter" data-level="17.2.3" data-path="sped-summarize.html"><a href="sped-summarize.html#the-head-command"><i class="fa fa-check"></i><b>17.2.3</b> The head() command</a></li>
<li class="chapter" data-level="17.2.4" data-path="sped-summarize.html"><a href="sped-summarize.html#highest-share-of-special-education-students-in-2020"><i class="fa fa-check"></i><b>17.2.4</b> Highest share of special education students in 2020</a></li>
<li class="chapter" data-level="17.2.5" data-path="sped-summarize.html"><a href="sped-summarize.html#greatest-change-in-share-of-special-education-students"><i class="fa fa-check"></i><b>17.2.5</b> Greatest change in share of special education students</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="sped-summarize.html"><a href="sped-summarize.html#aggregates-with-summarize"><i class="fa fa-check"></i><b>17.3</b> Aggregates with summarize()</a></li>
<li class="chapter" data-level="17.4" data-path="sped-summarize.html"><a href="sped-summarize.html#group_by"><i class="fa fa-check"></i><b>17.4</b> Group_by()</a>
<ul>
<li class="chapter" data-level="17.4.1" data-path="sped-summarize.html"><a href="sped-summarize.html#group-and-count"><i class="fa fa-check"></i><b>17.4.1</b> Group and count</a></li>
<li class="chapter" data-level="17.4.2" data-path="sped-summarize.html"><a href="sped-summarize.html#the-count-function-shortcut"><i class="fa fa-check"></i><b>17.4.2</b> The count() function shortcut</a></li>
<li class="chapter" data-level="17.4.3" data-path="sped-summarize.html"><a href="sped-summarize.html#comparing-thresholds-for-2015-and-2020"><i class="fa fa-check"></i><b>17.4.3</b> Comparing thresholds for 2015 and 2020</a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="sped-summarize.html"><a href="sped-summarize.html#more-on-summarize"><i class="fa fa-check"></i><b>17.5</b> More on summarize</a>
<ul>
<li class="chapter" data-level="17.5.1" data-path="sped-summarize.html"><a href="sped-summarize.html#ignoring-na-values"><i class="fa fa-check"></i><b>17.5.1</b> Ignoring NA values</a></li>
</ul></li>
<li class="chapter" data-level="17.6" data-path="sped-summarize.html"><a href="sped-summarize.html#review-what-we-learned"><i class="fa fa-check"></i><b>17.6</b> Review what we learned</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html"><i class="fa fa-check"></i><b>18</b> How to tackle a new dataset</a>
<ul>
<li class="chapter" data-level="18.1" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#needs-review"><i class="fa fa-check"></i><b>18.1</b> NEEDS REVIEW</a></li>
<li class="chapter" data-level="18.2" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#start-by-listing-questions"><i class="fa fa-check"></i><b>18.2</b> Start by listing questions</a></li>
<li class="chapter" data-level="18.3" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#understand-your-data"><i class="fa fa-check"></i><b>18.3</b> Understand your data</a></li>
<li class="chapter" data-level="18.4" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#counting-and-aggregation"><i class="fa fa-check"></i><b>18.4</b> Counting and aggregation</a>
<ul>
<li class="chapter" data-level="18.4.1" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#counting-rows-based-on-a-column"><i class="fa fa-check"></i><b>18.4.1</b> Counting rows based on a column</a></li>
<li class="chapter" data-level="18.4.2" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#sum-mean-and-other-aggregations"><i class="fa fa-check"></i><b>18.4.2</b> Sum, mean and other aggregations</a></li>
<li class="chapter" data-level="18.4.3" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#creating-columns-to-show-difference"><i class="fa fa-check"></i><b>18.4.3</b> Creating columns to show difference</a></li>
</ul></li>
<li class="chapter" data-level="18.5" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#cleaning-up-categorical-data"><i class="fa fa-check"></i><b>18.5</b> Cleaning up categorical data</a></li>
<li class="chapter" data-level="18.6" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#time-as-a-variable"><i class="fa fa-check"></i><b>18.6</b> Time as a variable</a></li>
<li class="chapter" data-level="18.7" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#explore-the-distributions-in-your-data"><i class="fa fa-check"></i><b>18.7</b> Explore the distributions in your data</a>
<ul>
<li class="chapter" data-level="18.7.1" data-path="how-to-tackle-a-new-dataset.html"><a href="how-to-tackle-a-new-dataset.html#more-on-histograms"><i class="fa fa-check"></i><b>18.7.1</b> More on histograms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="19" data-path="verbs.html"><a href="verbs.html"><i class="fa fa-check"></i><b>19</b> Verbs</a>
<ul>
<li class="chapter" data-level="19.1" data-path="verbs.html"><a href="verbs.html#needs-review-1"><i class="fa fa-check"></i><b>19.1</b> NEEDS REVIEW</a></li>
<li class="chapter" data-level="19.2" data-path="verbs.html"><a href="verbs.html#importexport"><i class="fa fa-check"></i><b>19.2</b> Import/Export</a></li>
<li class="chapter" data-level="19.3" data-path="verbs.html"><a href="verbs.html#data-manipulation"><i class="fa fa-check"></i><b>19.3</b> Data manipulation</a></li>
<li class="chapter" data-level="19.4" data-path="verbs.html"><a href="verbs.html#aggregation"><i class="fa fa-check"></i><b>19.4</b> Aggregation</a></li>
<li class="chapter" data-level="19.5" data-path="verbs.html"><a href="verbs.html#math"><i class="fa fa-check"></i><b>19.5</b> Math</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="chart-examples.html"><a href="chart-examples.html"><i class="fa fa-check"></i><b>20</b> Chart examples</a>
<ul>
<li class="chapter" data-level="20.1" data-path="chart-examples.html"><a href="chart-examples.html#needs-review-2"><i class="fa fa-check"></i><b>20.1</b> NEEDS REVIEW</a></li>
<li class="chapter" data-level="20.2" data-path="chart-examples.html"><a href="chart-examples.html#bar-charts"><i class="fa fa-check"></i><b>20.2</b> Bar charts</a>
<ul>
<li class="chapter" data-level="20.2.1" data-path="chart-examples.html"><a href="chart-examples.html#explanaton"><i class="fa fa-check"></i><b>20.2.1</b> Explanaton</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="chart-examples.html"><a href="chart-examples.html#column-chart"><i class="fa fa-check"></i><b>20.3</b> Column chart</a></li>
<li class="chapter" data-level="20.4" data-path="chart-examples.html"><a href="chart-examples.html#a-line-chart"><i class="fa fa-check"></i><b>20.4</b> A line chart</a>
<ul>
<li class="chapter" data-level="20.4.1" data-path="chart-examples.html"><a href="chart-examples.html#explanation"><i class="fa fa-check"></i><b>20.4.1</b> Explanation</a></li>
</ul></li>
<li class="chapter" data-level="20.5" data-path="chart-examples.html"><a href="chart-examples.html#scatterplot-1"><i class="fa fa-check"></i><b>20.5</b> Scatterplot</a>
<ul>
<li class="chapter" data-level="20.5.1" data-path="chart-examples.html"><a href="chart-examples.html#explanation-1"><i class="fa fa-check"></i><b>20.5.1</b> Explanation</a></li>
</ul></li>
<li class="chapter" data-level="20.6" data-path="chart-examples.html"><a href="chart-examples.html#histogram"><i class="fa fa-check"></i><b>20.6</b> Histogram</a></li>
<li class="chapter" data-level="20.7" data-path="chart-examples.html"><a href="chart-examples.html#titles-labels-and-other-cleanup"><i class="fa fa-check"></i><b>20.7</b> Titles, labels and other cleanup</a>
<ul>
<li class="chapter" data-level="20.7.1" data-path="chart-examples.html"><a href="chart-examples.html#title-and-axis-labels"><i class="fa fa-check"></i><b>20.7.1</b> Title and axis labels</a></li>
<li class="chapter" data-level="20.7.2" data-path="chart-examples.html"><a href="chart-examples.html#flip-the-graphic"><i class="fa fa-check"></i><b>20.7.2</b> Flip the graphic</a></li>
<li class="chapter" data-level="20.7.3" data-path="chart-examples.html"><a href="chart-examples.html#fix-exponential-numbers-on-an-axis"><i class="fa fa-check"></i><b>20.7.3</b> Fix exponential numbers on an axis</a></li>
</ul></li>
<li class="chapter" data-level="20.8" data-path="chart-examples.html"><a href="chart-examples.html#interactivity-with-plotly"><i class="fa fa-check"></i><b>20.8</b> Interactivity with plotly</a></li>
<li class="chapter" data-level="20.9" data-path="chart-examples.html"><a href="chart-examples.html#resources-5"><i class="fa fa-check"></i><b>20.9</b> Resources</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="publishing-your-findings.html"><a href="publishing-your-findings.html"><i class="fa fa-check"></i><b>21</b> Publishing your findings</a>
<ul>
<li class="chapter" data-level="21.1" data-path="publishing-your-findings.html"><a href="publishing-your-findings.html#needs-review-3"><i class="fa fa-check"></i><b>21.1</b> NEEDS REVIEW</a></li>
<li class="chapter" data-level="21.2" data-path="publishing-your-findings.html"><a href="publishing-your-findings.html#examples"><i class="fa fa-check"></i><b>21.2</b> Examples</a></li>
<li class="chapter" data-level="21.3" data-path="publishing-your-findings.html"><a href="publishing-your-findings.html#how-to-publish-your-projects"><i class="fa fa-check"></i><b>21.3</b> How to publish your projects</a>
<ul>
<li class="chapter" data-level="21.3.1" data-path="publishing-your-findings.html"><a href="publishing-your-findings.html#using-github-pages"><i class="fa fa-check"></i><b>21.3.1</b> Using Github Pages</a></li>
</ul></li>
<li class="chapter" data-level="21.4" data-path="publishing-your-findings.html"><a href="publishing-your-findings.html#making-branded-graphics"><i class="fa fa-check"></i><b>21.4</b> Making branded graphics</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Reporting with Data in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="sums-import" class="section level1" number="5">
<h1><span class="header-section-number">Chapter 5</span> Summarize with math - import</h1>
<blockquote>
<p>First draft of Sept 2021 rewrite</p>
</blockquote>
<p>With our Billboard assignment, we went through some common data wrangling processes — importing data, cleaning it and querying it for answers. All of our answers involved counting numbers of rows and we did so with two methods: The summary trio: <code>group_by</code>, <code>summmarize</code> and <code>arrange</code> (which I dub GSA), and then the shortcut <code>count()</code> that allows us to do all of that in one line.</p>
<p>For this data story we need to leave <code>count</code> behind and stick with the summary trio GSA because now we must do different kinds of math in our summarize functions, mainly <code>sum()</code>.</p>
<div id="about-the-story-military-surplus-transfers" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> About the story: Military surplus transfers</h2>
<p>In June 2020, Buzzfeed published the story <a href="https://www.buzzfeednews.com/article/johntemplon/police-departments-military-gear-1033-program"><em>Police Departments Have Received Hundreds Of Millions Of Dollars In Military Equipment Since Ferguson</em></a> about the amount of military equipment transferred to local law enforcement agencies since Michael Brown was killed in Ferguson, Missouri. After Brown’s death there was a public outcry after “what appeared to be a massively disproportionate show of force during protests brought scrutiny to a federal program that transfers unused military equipment to local law enforcement.” Reporter John Templon used data from the <a href="https://www.dla.mil/DispositionServices/Offers/Reutilization/LawEnforcement/PublicInformation/">Law Enforcement Support Office</a> for the update on the program and published his <a href="https://github.com/BuzzFeedNews/2020-06-leso-1033-transfers-since-ferguson">data analysis</a>, which he did in Python.</p>
<p>You will analyze the same dataset focusing on some local police agencies and write a short data drop about transfers to those agencies.</p>
<div id="the-leso-program" class="section level3" number="5.1.1">
<h3><span class="header-section-number">5.1.1</span> The LESO program</h3>
<p>The Defense Logistics Agency transfers surplus military equipment to local law enforcement through its <a href="https://www.dla.mil/DispositionServices/Offers/Reutilization/LawEnforcement/PublicInformation/">Law Enforcement Support Office</a>. You can find more information <a href="https://www.dla.mil/DispositionServices/Offers/Reutilization/LawEnforcement/ProgramFAQs/">about the program here</a>.</p>
<p>The agency updates the data quarterly and the data I’ve collected contains transfers through <strong>June 30, 2021</strong>. The original file is linked from the headline “ALASKA - WYOMING AND US TERRITORIES.”</p>
<p>The data there comes in an Excel spreadsheet that has a new sheet for each state. I used R to pull the data from each sheet and combine it into a single data set and I’ll cover the process I used in class, but you won’t have to do that part.</p>
<p><strong>I will supply a link to the combined data below.</strong></p>
</div>
<div id="about-the-data" class="section level3" number="5.1.2">
<h3><span class="header-section-number">5.1.2</span> About the data</h3>
<p>There is no data dictionary or record layout included with the data but I have corresponded with the Defense Logistics Agency to get a decent understanding of what is included. Columns in bold are those we care about the most.</p>
<ul>
<li>sheet: Which sheet the data came from. This is an artifact from the data merging script.</li>
<li><strong>state</strong>: A two-letter designation for the state of the agency.</li>
<li><strong>agency_name</strong>: This is the agency that got the equipment.</li>
<li>nsn: A special number that identifies the item. It is not germane to this specific assignment.</li>
<li><strong>item_name</strong>: The item transferred. Googling the names can sometimes yield more info on specific items.</li>
<li><strong>quantity</strong>: The number of the “units” the agency received.</li>
<li>ui: Unit of measurement (item, kit, etc.)</li>
<li><strong>acquisition_value</strong>: a cost <em>per unit</em> for the item.</li>
<li>demil_code: Another special code not germane to this assignment.</li>
<li>demil_ic: Another special code not germane to this assignment.</li>
<li><strong>ship_date</strong>: The date the item(s) were sent to the agency.</li>
<li>station_type: What kind of law enforcement agency made the request.</li>
</ul>
<p>Here is a sample of our main columns of interest, except for the date:</p>
<div id="htmlwidget-806527c84956e7cde1dd" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-806527c84956e7cde1dd">{"x":{"filter":"none","vertical":false,"data":[["KY","SC","CA","TX","OH"],["MEADE COUNTY SHERIFF DEPT","PROSPERITY POLICE DEPT","KERN COUNTY SHERIFF OFFICE","LEAGUE CITY POLICE DEPT","TRUMBULL COUNTY SHERIFF'S OFFICE"],["GENERATOR SET,DIESEL ENGINE","RIFLE,7.62 MILLIMETER","MARKER,TUBE TYPE","RIFLE,5.56 MILLIMETER","RIFLE,5.56 MILLIMETER"],[5,1,32,1,1],[4623.09,138,16.91,749,749]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th>state<\/th>\n      <th>agency_name<\/th>\n      <th>item_name<\/th>\n      <th>quantity<\/th>\n      <th>acquisition_value<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"dom":"t","columnDefs":[{"className":"dt-right","targets":[3,4]}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
<p><br></p>
<p>Each row of data is a transfer of a particular type of item from the U.S. Department of Defense to a local law enforcement agency. The row includes the name of the item, the quantity, and the value ($) of a single unit.</p>
<p>What the data doesn’t have is the <strong>total value</strong> of the items in the shipment. If there are 5 generators as noted in the first row above and the cost of each one is $4623.09, we have to multiply the <code>quantity</code> times the <code>acquisition_value</code> to get the total value of that equipment. We will do that as part of the assignment.</p>
<p>The local agencies really only pay the shipping costs for the item, <em>so you can’t say they paid for the items</em>, so the <strong>total value</strong> you calculate is the “value” of the items, not their cost to the local agency.</p>
</div>
</div>
<div id="the-questions-we-will-answer" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> The questions we will answer</h2>
<p>All answers will be based on data from <strong>Jan. 1, 2010</strong> to present. In addition, we’ll only consider <strong>Texas</strong> agencies as you answer the following.</p>
<ul>
<li>For each agency in Texas, find the summed <strong>quantity</strong> and summed <strong>total value</strong> of the equipment they received. (When I say “summed” that means we’ll add together all the values in the column.)
<ul>
<li>Once you have the list, we’ll think about what stands out and why?</li>
</ul></li>
<li>We’ll take the list above, but filter that summary to show only the following local agencies:
<ul>
<li>AUSTIN POLICE DEPT</li>
<li>SAN MARCOS POLICE DEPT</li>
<li>TRAVIS COUNTY SHERIFFS OFFICE</li>
<li>UNIV OF TEXAS SYSTEM POLICE HI_ED</li>
<li>WILLIAMSON COUNTY SHERIFF’S OFFICE</li>
</ul></li>
<li>For each of the agencies above we’ll summarize the <strong>total quantity</strong> and <strong>acquisition_value</strong> of each <strong>item</strong> shipped to the agency. We’ll arrange the list by agency so we can write about each one.</li>
<li>You’ll research some of the more interesting items the agencies received (i.e. Google the names) so you can include them in your data drop.</li>
</ul>
</div>
<div id="create-your-project" class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> Create your project</h2>
<p>We will build the same project structure that we did with the Billboard project. In fact, all our class projects will have this structure. Since we’ve done this before, some of the directions are less detailed.</p>
<ol style="list-style-type: decimal">
<li>With RStudio open, make sure you don’t have a project open. Go to File &gt; Close project.</li>
<li>Use the create project button (or File &gt; New project) to create a new project in a “New Directory.” Name the directory “yourname-military-surplus.”</li>
<li>Create two folders: <code>data-raw</code> and <code>data-processed</code>.</li>
</ol>
</div>
<div id="importcleaning-notebook" class="section level2" number="5.4">
<h2><span class="header-section-number">5.4</span> Import/cleaning notebook</h2>
<p>Again, like Billboard, we’ll create a notebook specifically for downloading, cleaning and prepping our data.</p>
<ol style="list-style-type: decimal">
<li>Create your RNotebook.</li>
<li>Rename the title “Military Surplus import/clean.”</li>
<li>Remove the rest of the boilerplate template.</li>
</ol>
<div id="add-the-goals-of-the-notebook" class="section level3" number="5.4.1">
<h3><span class="header-section-number">5.4.1</span> Add the goals of the notebook</h3>
<ol style="list-style-type: decimal">
<li>In Markdown, add a headline noting these are notebook goals.</li>
<li>Add the goals below:</li>
</ol>
<pre class="text"><code>- Download the data
- Import the data
- Clean datatypes
- Remove unnecessary columns
- Create a total_value column
- Filter to Texas agencies
- Filter the date range (since )
- Export the cleaned data</code></pre>
<blockquote>
<p>NOTE: Most of these are pretty standard in a import/cleaning notebook. Filtering to Texas agencies is specific to this data set, but we would do all these other things in all projects.</p>
</blockquote>
</div>
<div id="add-a-setup-section" class="section level3" number="5.4.2">
<h3><span class="header-section-number">5.4.2</span> Add a setup section</h3>
<p>This is the section where we add our libraries and such. Again, every notebook has this section, though the packages may vary on need.</p>
<ol style="list-style-type: decimal">
<li>Add a headline and text about what we are doing: Our project setup.</li>
<li>Add a code chunk to load the libraries. You should only need <code>tidyverse</code> for this notebook because the data already has clean names (no need for janitor) and the dates will import correctly (no need for lubridate).</li>
</ol>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="sums-import.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
</div>
<div id="download-the-data" class="section level3" number="5.4.3">
<h3><span class="header-section-number">5.4.3</span> Download the data</h3>
<ol style="list-style-type: decimal">
<li>A new section means a new headline and description. Add it. It is good practice to describe and link to the data you will be using. You can use this:</li>
</ol>
<pre class="text"><code>The Defense Logistics Agency transfers surplus military equipment to local law enforcement through its [Law Enforcement Support Office](https://www.dla.mil/DispositionServices/Offers/Reutilization/LawEnforcement/PublicInformation/). You can find more information [about the program here](https://www.dla.mil/DispositionServices/Offers/Reutilization/LawEnforcement/ProgramFAQs/).</code></pre>
<ol style="list-style-type: decimal">
<li>Use the <code>download.file()</code> function to download the date into your <code>data-raw</code> folder. Remember you need two arguments:</li>
</ol>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="sums-import.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(<span class="st">&quot;url_to_data&quot;</span>, <span class="st">&quot;path_to_folder/filename.csv&quot;</span>)</span></code></pre></div>
<ul>
<li>The data can be found at this url: <code>https://github.com/utdata/rwd-r-leso/blob/main/data-processed/leso.csv?raw=true</code></li>
<li>It should be saved in our <code>data-raw</code> folder with a name for the file.</li>
</ul>
<p>Once you’ve built your code chunk and run it, you should make sure the file downloaded into the correct place: in your <code>data-raw</code> folder.</p>
<details>
<summary>
You should be able to do this on your own. Really.
</summary>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="sums-import.html#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># You can comment the line below once you have the data</span></span>
<span id="cb69-2"><a href="sums-import.html#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(<span class="st">&quot;https://github.com/utdata/rwd-r-leso/blob/main/data-processed/leso.csv?raw=true&quot;</span>,</span>
<span id="cb69-3"><a href="sums-import.html#cb69-3" aria-hidden="true" tabindex="-1"></a>              <span class="st">&quot;data-raw/leso.csv&quot;</span>)</span></code></pre></div>
</details>
</div>
<div id="import-the-data-1" class="section level3" number="5.4.4">
<h3><span class="header-section-number">5.4.4</span> Import the data</h3>
<p>We are again working with a CSV, or comma-separated-values text file. I suggest you build the code chunk a bit at a time in this order:</p>
<ol style="list-style-type: decimal">
<li>Use <code>read_csv()</code> to read the file from our <code>data-raw</code> folder.</li>
<li>Edit that line to put the result into a tibble object using <code>&lt;-</code>. Name your new tibble <code>leso</code>.</li>
<li>Print the tibble as a table to the screen again by putting the tibble object on a new line and running it. This allows you to see it in columnar form.</li>
</ol>
<details>
<summary>
Try real hard first before clicking here for the answer
</summary>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="sums-import.html#cb70-1" aria-hidden="true" tabindex="-1"></a>leso <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data-raw/leso.csv&quot;</span>)</span></code></pre></div>
<pre><code>## Rows: 129348 Columns: 12</code></pre>
<pre><code>## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr  (7): state, agency_name, nsn, item_name, ui, demil_code, station_type
## dbl  (4): sheet, quantity, acquisition_value, demil_ic
## dttm (1): ship_date</code></pre>
<pre><code>## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="sums-import.html#cb74-1" aria-hidden="true" tabindex="-1"></a>leso</span></code></pre></div>
<pre><code>## # A tibble: 129,348 × 12
##    sheet state agency_name           nsn   item_name quantity ui    acquisition_val…
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;                 &lt;chr&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;
##  1     1 AL    ABBEVILLE POLICE DEPT 1005… MOUNT,RI…       10 Each             1626 
##  2     1 AL    ABBEVILLE POLICE DEPT 1240… SIGHT,RE…        9 Each              333 
##  3     1 AL    ABBEVILLE POLICE DEPT 1240… OPTICAL …        1 Each              246.
##  4     1 AL    ABBEVILLE POLICE DEPT 1385… UNMANNED…        1 Each            10000 
##  5     1 AL    ABBEVILLE POLICE DEPT 2320… TRUCK,UT…        1 Each            62627 
##  6     1 AL    ABBEVILLE POLICE DEPT 2320… TRUCK,UT…        1 Each            62627 
##  7     1 AL    ABBEVILLE POLICE DEPT 2355… MINE RES…        1 Each           658000 
##  8     1 AL    ABBEVILLE POLICE DEPT 2540… BALLISTI…       10 Kit             15872.
##  9     1 AL    ABBEVILLE POLICE DEPT 5855… ILLUMINA…       10 Each              926 
## 10     1 AL    ABBEVILLE POLICE DEPT 6760… CAMERA R…        1 Each             1500 
## # … with 129,338 more rows, and 4 more variables: demil_code &lt;chr&gt;,
## #   demil_ic &lt;dbl&gt;, ship_date &lt;dttm&gt;, station_type &lt;chr&gt;</code></pre>
</details>
</div>
<div id="glimpse-the-data-1" class="section level3" number="5.4.5">
<h3><span class="header-section-number">5.4.5</span> Glimpse the data</h3>
<ol style="list-style-type: decimal">
<li>In a new block, print the tibble but pipe it into <code>glimpse()</code> so you can see all the column names.</li>
</ol>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="sums-import.html#cb76-1" aria-hidden="true" tabindex="-1"></a>leso <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 129,348
## Columns: 12
## $ sheet             &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ state             &lt;chr&gt; &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;…
## $ agency_name       &lt;chr&gt; &quot;ABBEVILLE POLICE DEPT&quot;, &quot;ABBEVILLE POLICE DEPT&quot;, &quot;A…
## $ nsn               &lt;chr&gt; &quot;1005-01-587-7175&quot;, &quot;1240-01-411-1265&quot;, &quot;1240-DS-OPT…
## $ item_name         &lt;chr&gt; &quot;MOUNT,RIFLE&quot;, &quot;SIGHT,REFLEX&quot;, &quot;OPTICAL SIGHTING AND…
## $ quantity          &lt;dbl&gt; 10, 9, 1, 1, 1, 1, 1, 10, 10, 1, 5, 10, 11, 10, 1, 3…
## $ ui                &lt;chr&gt; &quot;Each&quot;, &quot;Each&quot;, &quot;Each&quot;, &quot;Each&quot;, &quot;Each&quot;, &quot;Each&quot;, &quot;Eac…
## $ acquisition_value &lt;dbl&gt; 1626.00, 333.00, 245.88, 10000.00, 62627.00, 62627.0…
## $ demil_code        &lt;chr&gt; &quot;D&quot;, &quot;D&quot;, &quot;D&quot;, &quot;Q&quot;, &quot;C&quot;, &quot;C&quot;, &quot;C&quot;, &quot;D&quot;, &quot;D&quot;, &quot;D&quot;, &quot;D…
## $ demil_ic          &lt;dbl&gt; 1, 1, NA, 3, 1, 1, 1, 1, 1, 7, 1, 1, 1, 1, 1, NA, 1,…
## $ ship_date         &lt;dttm&gt; 2016-09-19, 2016-09-14, 2016-06-02, 2017-03-28, 201…
## $ station_type      &lt;chr&gt; &quot;State&quot;, &quot;State&quot;, &quot;State&quot;, &quot;State&quot;, &quot;State&quot;, &quot;State&quot;…</code></pre>
<div id="checking-datatypes" class="section level4" number="5.4.5.1">
<h4><span class="header-section-number">5.4.5.1</span> Checking datatypes</h4>
<p>Take a look at your glimpse returns. These are the things to watch for:</p>
<ul>
<li>Are your variable names (column names) clean? All lowercase with <code>_</code> separating words?</li>
<li>Are dates saved in a date format? <code>ship_date</code> looks good at <code>&lt;dttm&gt;</code>, which means “datetime.”</li>
<li>Are your numbers really numbers? <code>acquisition_value</code> is the column we are most concerned about here, and it looks good.</li>
</ul>
<p>This data set looks good (because I pre-prepared it fo you), but you always want to check and make corrections, like we did to fix the date in the Billboard assignment.</p>
</div>
</div>
<div id="remove-unnecessary-columns" class="section level3" number="5.4.6">
<h3><span class="header-section-number">5.4.6</span> Remove unnecessary columns</h3>
<p>Sometimes at this point in a project, you might not know what columns you need to keep and which you could do without. The nice thing about doing this with code in a notebook is we can always go back, make corrections and run our notebook again. In this case, I’m going to tell you which columns you can remove so we have a tighter data set to work with. We’ll also learn a cool trick with <code>select()</code>.</p>
<ol style="list-style-type: decimal">
<li>Start a new section with a headline, text to explain you are removing unneeded columns.</li>
<li>Add the following code. I’ll explain it below.</li>
</ol>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="sums-import.html#cb78-1" aria-hidden="true" tabindex="-1"></a>leso_tight <span class="ot">&lt;-</span> leso <span class="sc">%&gt;%</span> </span>
<span id="cb78-2"><a href="sums-import.html#cb78-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb78-3"><a href="sums-import.html#cb78-3" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>sheet,</span>
<span id="cb78-4"><a href="sums-import.html#cb78-4" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span>nsn,</span>
<span id="cb78-5"><a href="sums-import.html#cb78-5" aria-hidden="true" tabindex="-1"></a>    <span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">&quot;demil&quot;</span>)</span>
<span id="cb78-6"><a href="sums-import.html#cb78-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb78-7"><a href="sums-import.html#cb78-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-8"><a href="sums-import.html#cb78-8" aria-hidden="true" tabindex="-1"></a>leso_tight <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 129,348
## Columns: 8
## $ state             &lt;chr&gt; &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;…
## $ agency_name       &lt;chr&gt; &quot;ABBEVILLE POLICE DEPT&quot;, &quot;ABBEVILLE POLICE DEPT&quot;, &quot;A…
## $ item_name         &lt;chr&gt; &quot;MOUNT,RIFLE&quot;, &quot;SIGHT,REFLEX&quot;, &quot;OPTICAL SIGHTING AND…
## $ quantity          &lt;dbl&gt; 10, 9, 1, 1, 1, 1, 1, 10, 10, 1, 5, 10, 11, 10, 1, 3…
## $ ui                &lt;chr&gt; &quot;Each&quot;, &quot;Each&quot;, &quot;Each&quot;, &quot;Each&quot;, &quot;Each&quot;, &quot;Each&quot;, &quot;Eac…
## $ acquisition_value &lt;dbl&gt; 1626.00, 333.00, 245.88, 10000.00, 62627.00, 62627.0…
## $ ship_date         &lt;dttm&gt; 2016-09-19, 2016-09-14, 2016-06-02, 2017-03-28, 201…
## $ station_type      &lt;chr&gt; &quot;State&quot;, &quot;State&quot;, &quot;State&quot;, &quot;State&quot;, &quot;State&quot;, &quot;State&quot;…</code></pre>
<p>We did a select like this with billboard, but note the third item within the <code>select()</code>: <code>-starts_with("demil")</code>. This removes both the <code>demil_code</code> and <code>demil_ic</code> columns in one move.</p>
<p>There are other special operators like that: <code>ends_with()</code>, <code>contains()</code> and many more. <a href="https://dplyr.tidyverse.org/reference/select.html">Check out the docs on the select function</a>.</p>
<p>So now we have a tibble called <code>leso_tight</code> that we will work with in the next section.</p>
</div>
<div id="create-a-total_value-column" class="section level3" number="5.4.7">
<h3><span class="header-section-number">5.4.7</span> Create a total_value column</h3>
<p>When we used <code>mutate()</code> to convert the date in the Billboard assignment, we were reassigning values in each row of a column back into the same column.</p>
<p>In this assignment, we will use <code>mutate()</code> to create a <strong>new</strong> column with new values based on a calculation – <code>quantity</code> multiplied by the <code>acquisition_value</code> – for each row. Let’s review the concept first</p>
<p>If you started with data like this:</p>
<table>
<thead>
<tr class="header">
<th>item</th>
<th align="right">item_count</th>
<th align="right">item_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bread</td>
<td align="right">2</td>
<td align="right">1.5</td>
</tr>
<tr class="even">
<td>Milk</td>
<td align="right">1</td>
<td align="right">2.75</td>
</tr>
<tr class="odd">
<td>Beer</td>
<td align="right">3</td>
<td align="right">9</td>
</tr>
</tbody>
</table>
<p>And wanted to create a total value of each item in the table, you would use <code>mutate()</code>:</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="sums-import.html#cb80-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb80-2"><a href="sums-import.html#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_value =</span> item_count <span class="sc">*</span> item_value)</span></code></pre></div>
<p>And you would get a return like this, with your new <code>total_value</code> column added at the end:</p>
<table>
<thead>
<tr class="header">
<th>item</th>
<th align="right">item_count</th>
<th align="right">item_value</th>
<th align="right">total_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bread</td>
<td align="right">2</td>
<td align="right">1.5</td>
<td align="right">3</td>
</tr>
<tr class="even">
<td>Milk</td>
<td align="right">1</td>
<td align="right">2.75</td>
<td align="right">2.75</td>
</tr>
<tr class="odd">
<td>Beer</td>
<td align="right">3</td>
<td align="right">9</td>
<td align="right">27</td>
</tr>
</tbody>
</table>
<p>Other math operators work as well: <code>+</code>, <code>-</code>, <code>*</code> and <code>/</code>.</p>
<p>So, now that we’ve talked about how it is done, I want you to:</p>
<ol style="list-style-type: decimal">
<li>Use <code>mutate()</code> to create= a new <code>total_value</code> column that multiplies <code>quantity</code> times <code>acquisition_value</code>.</li>
<li>Put the results into a new tibble called <code>leso_total</code> so we can all be on the same page.</li>
<li>Glimpse the new tibble so you can check the results.</li>
</ol>
<details>
<summary>
Try it on your own. You can figure it out!
</summary>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="sums-import.html#cb81-1" aria-hidden="true" tabindex="-1"></a>leso_total <span class="ot">&lt;-</span> leso_tight <span class="sc">%&gt;%</span> </span>
<span id="cb81-2"><a href="sums-import.html#cb81-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb81-3"><a href="sums-import.html#cb81-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_value =</span> quantity <span class="sc">*</span> acquisition_value</span>
<span id="cb81-4"><a href="sums-import.html#cb81-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb81-5"><a href="sums-import.html#cb81-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-6"><a href="sums-import.html#cb81-6" aria-hidden="true" tabindex="-1"></a>leso_total <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 129,348
## Columns: 9
## $ state             &lt;chr&gt; &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;, &quot;AL&quot;…
## $ agency_name       &lt;chr&gt; &quot;ABBEVILLE POLICE DEPT&quot;, &quot;ABBEVILLE POLICE DEPT&quot;, &quot;A…
## $ item_name         &lt;chr&gt; &quot;MOUNT,RIFLE&quot;, &quot;SIGHT,REFLEX&quot;, &quot;OPTICAL SIGHTING AND…
## $ quantity          &lt;dbl&gt; 10, 9, 1, 1, 1, 1, 1, 10, 10, 1, 5, 10, 11, 10, 1, 3…
## $ ui                &lt;chr&gt; &quot;Each&quot;, &quot;Each&quot;, &quot;Each&quot;, &quot;Each&quot;, &quot;Each&quot;, &quot;Each&quot;, &quot;Eac…
## $ acquisition_value &lt;dbl&gt; 1626.00, 333.00, 245.88, 10000.00, 62627.00, 62627.0…
## $ ship_date         &lt;dttm&gt; 2016-09-19, 2016-09-14, 2016-06-02, 2017-03-28, 201…
## $ station_type      &lt;chr&gt; &quot;State&quot;, &quot;State&quot;, &quot;State&quot;, &quot;State&quot;, &quot;State&quot;, &quot;State&quot;…
## $ total_value       &lt;dbl&gt; 16260.00, 2997.00, 245.88, 10000.00, 62627.00, 62627…</code></pre>
</details>
<p><strong>Check that it worked!!</strong>. Use the glimpsed data to check the first item: For me, 10 * 1626.00 = 16260.00, which is correct!</p>
<p>Note that new columns are added at the end of the tibble. That is why I suggested you glimpse the data instead of printing the tibble so you can easily see results on one screen.</p>
</div>
<div id="filtering-our-data" class="section level3" number="5.4.8">
<h3><span class="header-section-number">5.4.8</span> Filtering our data</h3>
<p>You used filter in the Billboard lesson to get No. 1 songs and to get a date range of data. We need to do something similar here to get only Texas data of a certain date range, but we’ll build the filters one at a time so we can check the results.</p>
<div id="apply-the-tx-filter" class="section level4" number="5.4.8.1">
<h4><span class="header-section-number">5.4.8.1</span> Apply the TX filter</h4>
<ol style="list-style-type: decimal">
<li>Create a new section with headlines and text that denote you are filtering the data to Texas and since Jan. 1, 2010</li>
<li>Create the code chunk and start your filter process using the <code>leso_total</code> tibble.</li>
<li>Use <code>filter()</code> on the <code>state</code> column to keep all rows with “TX.”</li>
</ol>
<details>
<summary>
Really, you got this.
</summary>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="sums-import.html#cb83-1" aria-hidden="true" tabindex="-1"></a>leso_total <span class="sc">%&gt;%</span> </span>
<span id="cb83-2"><a href="sums-import.html#cb83-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb83-3"><a href="sums-import.html#cb83-3" aria-hidden="true" tabindex="-1"></a>    state <span class="sc">==</span> <span class="st">&quot;TX&quot;</span></span>
<span id="cb83-4"><a href="sums-import.html#cb83-4" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 8,684 × 9
##    state agency_name           item_name                    quantity ui    acquisition_val…
##    &lt;chr&gt; &lt;chr&gt;                 &lt;chr&gt;                           &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;
##  1 TX    ABERNATHY POLICE DEPT PISTOL,CALIBER .45,AUTOMATIC        1 Each              58.7
##  2 TX    ABERNATHY POLICE DEPT PISTOL,CALIBER .45,AUTOMATIC        1 Each              58.7
##  3 TX    ABERNATHY POLICE DEPT PISTOL,CALIBER .45,AUTOMATIC        1 Each              58.7
##  4 TX    ABERNATHY POLICE DEPT PISTOL,CALIBER .45,AUTOMATIC        1 Each              58.7
##  5 TX    ABERNATHY POLICE DEPT PISTOL,CALIBER .45,AUTOMATIC        1 Each              58.7
##  6 TX    ABERNATHY POLICE DEPT RIFLE,5.56 MILLIMETER               1 Each             749  
##  7 TX    ABERNATHY POLICE DEPT RIFLE,5.56 MILLIMETER               1 Each             749  
##  8 TX    ABERNATHY POLICE DEPT SIGHT,REFLEX                        5 Each             333  
##  9 TX    ABERNATHY POLICE DEPT TRUCK,UTILITY                       1 Each           62627  
## 10 TX    ABILENE POLICE DEPT   RIFLE,5.56 MILLIMETER               1 Each             499  
## # … with 8,674 more rows, and 3 more variables: ship_date &lt;dttm&gt;,
## #   station_type &lt;chr&gt;, total_value &lt;dbl&gt;</code></pre>
</details>
<p>How do you know if it worked? Well the first column in the data is the <code>state</code> column, so they should all start with “TX.” Also note you started with nearly 130k observations (rows), and there are only 8,600+ in Texas.</p>
</div>
<div id="add-the-date-filter" class="section level4" number="5.4.8.2">
<h4><span class="header-section-number">5.4.8.2</span> Add the date filter</h4>
<ol style="list-style-type: decimal">
<li>Now, <strong>EDIT THAT SAME CHUNK</strong> to add a new part to your filter to also get rows with a <code>ship_date</code> of 2010-01-01 or later.</li>
</ol>
<details>
<summary>
If you do this on your own, treat yourself to a cookie
</summary>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="sums-import.html#cb85-1" aria-hidden="true" tabindex="-1"></a>leso_total <span class="sc">%&gt;%</span> </span>
<span id="cb85-2"><a href="sums-import.html#cb85-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb85-3"><a href="sums-import.html#cb85-3" aria-hidden="true" tabindex="-1"></a>    state <span class="sc">==</span> <span class="st">&quot;TX&quot;</span>,</span>
<span id="cb85-4"><a href="sums-import.html#cb85-4" aria-hidden="true" tabindex="-1"></a>    ship_date <span class="sc">&gt;=</span> <span class="st">&quot;2010-01-01&quot;</span></span>
<span id="cb85-5"><a href="sums-import.html#cb85-5" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 7,407 × 9
##    state agency_name           item_name                    quantity ui    acquisition_val…
##    &lt;chr&gt; &lt;chr&gt;                 &lt;chr&gt;                           &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;
##  1 TX    ABERNATHY POLICE DEPT PISTOL,CALIBER .45,AUTOMATIC        1 Each              58.7
##  2 TX    ABERNATHY POLICE DEPT PISTOL,CALIBER .45,AUTOMATIC        1 Each              58.7
##  3 TX    ABERNATHY POLICE DEPT PISTOL,CALIBER .45,AUTOMATIC        1 Each              58.7
##  4 TX    ABERNATHY POLICE DEPT PISTOL,CALIBER .45,AUTOMATIC        1 Each              58.7
##  5 TX    ABERNATHY POLICE DEPT PISTOL,CALIBER .45,AUTOMATIC        1 Each              58.7
##  6 TX    ABERNATHY POLICE DEPT RIFLE,5.56 MILLIMETER               1 Each             749  
##  7 TX    ABERNATHY POLICE DEPT RIFLE,5.56 MILLIMETER               1 Each             749  
##  8 TX    ABERNATHY POLICE DEPT SIGHT,REFLEX                        5 Each             333  
##  9 TX    ABERNATHY POLICE DEPT TRUCK,UTILITY                       1 Each           62627  
## 10 TX    ALLEN POLICE DEPT     SIGHT,REFLEX                        1 Each             333  
## # … with 7,397 more rows, and 3 more variables: ship_date &lt;dttm&gt;,
## #   station_type &lt;chr&gt;, total_value &lt;dbl&gt;</code></pre>
</details>
</div>
<div id="checking-the-results-with-summary" class="section level4" number="5.4.8.3">
<h4><span class="header-section-number">5.4.8.3</span> Checking the results with summary()</h4>
<p>How do you know this date filter worked? Well, we went from 8600+ rows to 7400+ rows, so we did something. You might look at the results table and click over to the <code>ship_date</code> columns so you can see some of the results, but you can’t be sure the top row is the oldest. We could use an <code>arrange()</code> to test that, but I have another suggestion: <code>summary()</code>.</p>
<p>Now, <code>summary()</code> is different than <code>summarize()</code>, which we’ll do plenty of in a mintue. The summary function will show you some results about each column in your data, and when it is a number or date, it will give you some basic stats like min, max and median values.</p>
<ol style="list-style-type: decimal">
<li>Use the image below to add a <code>summary()</code> function to your filtering data chunk.</li>
<li>Once you’ve confirmed that the “Min.” of <code>ship_date</code> is not older than 2010, then <strong>REMOVE THE SUMMARY STATEMENT</strong>.</li>
</ol>
<p>If you leave the summary statement there when we create our updated tibble, then you’ll “save” the summary and not the data.</p>
<div class="figure">
<img src="images/military-date-summary.png" alt="" />
<p class="caption">Summary function</p>
</div>
</div>
<div id="add-filtered-data-to-new-tibble" class="section level4" number="5.4.8.4">
<h4><span class="header-section-number">5.4.8.4</span> Add filtered data to new tibble</h4>
<p>Once you’ve checked and removed the summary, you can save your filtered data into a new tibble.</p>
<ol style="list-style-type: decimal">
<li>Edit the filtering chunk to put the results into a new tibble called <code>leso_filtered</code>.</li>
</ol>
<details>
<summary>
Seriously? You were going to look?
</summary>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="sums-import.html#cb87-1" aria-hidden="true" tabindex="-1"></a>leso_filtered <span class="ot">&lt;-</span> leso_total <span class="sc">%&gt;%</span> </span>
<span id="cb87-2"><a href="sums-import.html#cb87-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(</span>
<span id="cb87-3"><a href="sums-import.html#cb87-3" aria-hidden="true" tabindex="-1"></a>    state <span class="sc">==</span> <span class="st">&quot;TX&quot;</span>,</span>
<span id="cb87-4"><a href="sums-import.html#cb87-4" aria-hidden="true" tabindex="-1"></a>    ship_date <span class="sc">&gt;=</span> <span class="st">&quot;2010-01-01&quot;</span></span>
<span id="cb87-5"><a href="sums-import.html#cb87-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb87-6"><a href="sums-import.html#cb87-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-7"><a href="sums-import.html#cb87-7" aria-hidden="true" tabindex="-1"></a>leso_filtered <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code></pre></div>
<pre><code>## Rows: 7,407
## Columns: 9
## $ state             &lt;chr&gt; &quot;TX&quot;, &quot;TX&quot;, &quot;TX&quot;, &quot;TX&quot;, &quot;TX&quot;, &quot;TX&quot;, &quot;TX&quot;, &quot;TX&quot;, &quot;TX&quot;…
## $ agency_name       &lt;chr&gt; &quot;ABERNATHY POLICE DEPT&quot;, &quot;ABERNATHY POLICE DEPT&quot;, &quot;A…
## $ item_name         &lt;chr&gt; &quot;PISTOL,CALIBER .45,AUTOMATIC&quot;, &quot;PISTOL,CALIBER .45,…
## $ quantity          &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ ui                &lt;chr&gt; &quot;Each&quot;, &quot;Each&quot;, &quot;Each&quot;, &quot;Each&quot;, &quot;Each&quot;, &quot;Each&quot;, &quot;Eac…
## $ acquisition_value &lt;dbl&gt; 58.71, 58.71, 58.71, 58.71, 58.71, 749.00, 749.00, 3…
## $ ship_date         &lt;dttm&gt; 2011-11-03, 2011-11-03, 2011-11-03, 2011-11-03, 201…
## $ station_type      &lt;chr&gt; &quot;State&quot;, &quot;State&quot;, &quot;State&quot;, &quot;State&quot;, &quot;State&quot;, &quot;State&quot;…
## $ total_value       &lt;dbl&gt; 58.71, 58.71, 58.71, 58.71, 58.71, 749.00, 749.00, 1…</code></pre>
</details>
</div>
</div>
<div id="export-cleaned-data" class="section level3" number="5.4.9">
<h3><span class="header-section-number">5.4.9</span> Export cleaned data</h3>
<p>Now that we have our data selected, mutated and filtered how we want it, we can export your <code>leso_filtered</code> tibble into an <code>.rds</code> file to use in our analysis notebook. If you recall, we use the <code>.rds</code> format because it will remember data types and such.</p>
<ol style="list-style-type: decimal">
<li>Create a new section with headline and text explaining that you are exporting the data.</li>
<li>Do it. The function you need is called <code>write_rds</code> and you need to give it a path/name that saves the file in the <code>data-processed</code> folder. Name it <code>01-leso-tx.rds</code> so you know it a) came from the first notebook b) is the Texas only data. <strong>Well-formatted, descriptive file names are important to your future self and other colleagues</strong>.</li>
</ol>
<details>
<summary>
Try it
</summary>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="sums-import.html#cb89-1" aria-hidden="true" tabindex="-1"></a>leso_filtered <span class="sc">%&gt;%</span> <span class="fu">write_rds</span>(<span class="st">&quot;data-processed/01-leso-tx.rds&quot;</span>)</span></code></pre></div>
</details>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="wrangle.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="sums-analyze.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/05-sums-import.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "lunr",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
