# Notes {-}

> From 03-import

## Practice assignment: Import census

To practice these skills on your own, you'll create a new project and use new data. You'll work on it through multiple lessons, applying what you've learned along the way.

- Close your School Ratings project first!
- Create a **new Project** called "firstname-census-practice". You'll want to save that inside your "rwd" folder so you can use it later. We'll keep building on it.
- Create a new folder in your project called "data-raw".
- Download this CSV file and put it into your data-raw folder: [DEC_10_SF1_TX_County_population.csv](https://drive.google.com/file/d/1L51qQbdW3dHXTdlvlHx3z5p8Py5Cgv2a/view). The data is 2010 Census populations by county and race for Texas.
- Start a new R Notebook with a good title and filename.
- Write text to describe the data set.
- Import the data using `read_csv()` and print the data to the screen.
- Compare the imported data to the original csv file and note any problems you might see with the column names or data types that you might want to fix.
- Save, Knit, and Zip the project folder and upload to the "Practice: Import" assignment.
